package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;
import java.util.Date;

public class BTR_CONTROLVO extends BaseVO {
    /**
     * This field corresponds to the database column BTR_CONTROL.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column BTR_CONTROL.CLIENT_CODE
     */
    private BigDecimal CLIENT_CODE;

    /**
     * This field corresponds to the database column BTR_CONTROL.CLIENT_BRIEF_DESC
     */
    private String CLIENT_BRIEF_DESC;

    /**
     * This field corresponds to the database column BTR_CONTROL.NATIONALITY
     */
    private BigDecimal NATIONALITY;

    /**
     * This field corresponds to the database column BTR_CONTROL.EMP_BASE_COUNTRY
     */
    private BigDecimal EMP_BASE_COUNTRY;

    /**
     * This field corresponds to the database column BTR_CONTROL.USD_CY_CODE
     */
    private BigDecimal USD_CY_CODE;

    /**
     * This field corresponds to the database column BTR_CONTROL.CSV_PATH
     */
    private String CSV_PATH;

    /**
     * This field corresponds to the database column BTR_CONTROL.BANK_ID
     */
    private BigDecimal BANK_ID;

    /**
     * This field corresponds to the database column BTR_CONTROL.REPORT_LANG
     */
    private String REPORT_LANG;

    /**
     * This field corresponds to the database column BTR_CONTROL.BTR_WEEKEND_DAY
     */
    private BigDecimal BTR_WEEKEND_DAY;

    /**
     * This field corresponds to the database column BTR_CONTROL.DEF_NOSTRO_GL
     */
    private BigDecimal DEF_NOSTRO_GL;

    /**
     * This field corresponds to the database column BTR_CONTROL.RDS_PARENT_REF
     */
    private String RDS_PARENT_REF;

    /**
     * This field corresponds to the database column BTR_CONTROL.RDS_FOLDER_NAME
     */
    private String RDS_FOLDER_NAME;

    /**
     * This field corresponds to the database column BTR_CONTROL.ACBRD_AMOUNT
     */
    private BigDecimal ACBRD_AMOUNT;

    /**
     * This field corresponds to the database column BTR_CONTROL.SCHED_PATH
     */
    private String SCHED_PATH;

    /**
     * This field corresponds to the database column BTR_CONTROL.CDR_AMT
     */
    private BigDecimal CDR_AMT;

    /**
     * This field corresponds to the database column BTR_CONTROL.ADD_REF
     */
    private String ADD_REF;

    /**
     * This field corresponds to the database column BTR_CONTROL.CB_COUNTRY_CODE
     */
    private String CB_COUNTRY_CODE;

    /**
     * This field corresponds to the database column BTR_CONTROL.TRADE_VALUE
     */
    private String TRADE_VALUE;

    /**
     * This field corresponds to the database column BTR_CONTROL.SITCOM_ENABLE_YN
     */
    private String SITCOM_ENABLE_YN;

    /**
     * This field corresponds to the database column BTR_CONTROL.SITCOM_TEXT
     */
    private String SITCOM_TEXT;

    /**
     * This field corresponds to the database column BTR_CONTROL.SITCOM_LOCATION
     */
    private String SITCOM_LOCATION;

    /**
     * This field corresponds to the database column BTR_CONTROL.DATE_UPDATED
     */
    private Date DATE_UPDATED;
    
    /**
     * This field corresponds to the database column BTR_CONTROL.ARGUMENTS_ENABLE_YN
     */
    private String ARGUMENTS_ENABLE_YN;
	
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTR_CONTROL.COMP_CODE
     *
     * @return the value of BTR_CONTROL.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTR_CONTROL.COMP_CODE
     *
     * @param COMP_CODE the value for BTR_CONTROL.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTR_CONTROL.CLIENT_CODE
     *
     * @return the value of BTR_CONTROL.CLIENT_CODE
     */
    public BigDecimal getCLIENT_CODE() {
        return CLIENT_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTR_CONTROL.CLIENT_CODE
     *
     * @param CLIENT_CODE the value for BTR_CONTROL.CLIENT_CODE
     */
    public void setCLIENT_CODE(BigDecimal CLIENT_CODE) {
        this.CLIENT_CODE = CLIENT_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTR_CONTROL.CLIENT_BRIEF_DESC
     *
     * @return the value of BTR_CONTROL.CLIENT_BRIEF_DESC
     */
    public String getCLIENT_BRIEF_DESC() {
        return CLIENT_BRIEF_DESC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTR_CONTROL.CLIENT_BRIEF_DESC
     *
     * @param CLIENT_BRIEF_DESC the value for BTR_CONTROL.CLIENT_BRIEF_DESC
     */
    public void setCLIENT_BRIEF_DESC(String CLIENT_BRIEF_DESC) {
        this.CLIENT_BRIEF_DESC = CLIENT_BRIEF_DESC == null ? null : CLIENT_BRIEF_DESC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTR_CONTROL.NATIONALITY
     *
     * @return the value of BTR_CONTROL.NATIONALITY
     */
    public BigDecimal getNATIONALITY() {
        return NATIONALITY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTR_CONTROL.NATIONALITY
     *
     * @param NATIONALITY the value for BTR_CONTROL.NATIONALITY
     */
    public void setNATIONALITY(BigDecimal NATIONALITY) {
        this.NATIONALITY = NATIONALITY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTR_CONTROL.EMP_BASE_COUNTRY
     *
     * @return the value of BTR_CONTROL.EMP_BASE_COUNTRY
     */
    public BigDecimal getEMP_BASE_COUNTRY() {
        return EMP_BASE_COUNTRY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTR_CONTROL.EMP_BASE_COUNTRY
     *
     * @param EMP_BASE_COUNTRY the value for BTR_CONTROL.EMP_BASE_COUNTRY
     */
    public void setEMP_BASE_COUNTRY(BigDecimal EMP_BASE_COUNTRY) {
        this.EMP_BASE_COUNTRY = EMP_BASE_COUNTRY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTR_CONTROL.USD_CY_CODE
     *
     * @return the value of BTR_CONTROL.USD_CY_CODE
     */
    public BigDecimal getUSD_CY_CODE() {
        return USD_CY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTR_CONTROL.USD_CY_CODE
     *
     * @param USD_CY_CODE the value for BTR_CONTROL.USD_CY_CODE
     */
    public void setUSD_CY_CODE(BigDecimal USD_CY_CODE) {
        this.USD_CY_CODE = USD_CY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTR_CONTROL.CSV_PATH
     *
     * @return the value of BTR_CONTROL.CSV_PATH
     */
    public String getCSV_PATH() {
        return CSV_PATH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTR_CONTROL.CSV_PATH
     *
     * @param CSV_PATH the value for BTR_CONTROL.CSV_PATH
     */
    public void setCSV_PATH(String CSV_PATH) {
        this.CSV_PATH = CSV_PATH == null ? null : CSV_PATH.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTR_CONTROL.BANK_ID
     *
     * @return the value of BTR_CONTROL.BANK_ID
     */
    public BigDecimal getBANK_ID() {
        return BANK_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTR_CONTROL.BANK_ID
     *
     * @param BANK_ID the value for BTR_CONTROL.BANK_ID
     */
    public void setBANK_ID(BigDecimal BANK_ID) {
        this.BANK_ID = BANK_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTR_CONTROL.REPORT_LANG
     *
     * @return the value of BTR_CONTROL.REPORT_LANG
     */
    public String getREPORT_LANG() {
        return REPORT_LANG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTR_CONTROL.REPORT_LANG
     *
     * @param REPORT_LANG the value for BTR_CONTROL.REPORT_LANG
     */
    public void setREPORT_LANG(String REPORT_LANG) {
        this.REPORT_LANG = REPORT_LANG == null ? null : REPORT_LANG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTR_CONTROL.BTR_WEEKEND_DAY
     *
     * @return the value of BTR_CONTROL.BTR_WEEKEND_DAY
     */
    public BigDecimal getBTR_WEEKEND_DAY() {
        return BTR_WEEKEND_DAY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTR_CONTROL.BTR_WEEKEND_DAY
     *
     * @param BTR_WEEKEND_DAY the value for BTR_CONTROL.BTR_WEEKEND_DAY
     */
    public void setBTR_WEEKEND_DAY(BigDecimal BTR_WEEKEND_DAY) {
        this.BTR_WEEKEND_DAY = BTR_WEEKEND_DAY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTR_CONTROL.DEF_NOSTRO_GL
     *
     * @return the value of BTR_CONTROL.DEF_NOSTRO_GL
     */
    public BigDecimal getDEF_NOSTRO_GL() {
        return DEF_NOSTRO_GL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTR_CONTROL.DEF_NOSTRO_GL
     *
     * @param DEF_NOSTRO_GL the value for BTR_CONTROL.DEF_NOSTRO_GL
     */
    public void setDEF_NOSTRO_GL(BigDecimal DEF_NOSTRO_GL) {
        this.DEF_NOSTRO_GL = DEF_NOSTRO_GL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTR_CONTROL.RDS_PARENT_REF
     *
     * @return the value of BTR_CONTROL.RDS_PARENT_REF
     */
    public String getRDS_PARENT_REF() {
        return RDS_PARENT_REF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTR_CONTROL.RDS_PARENT_REF
     *
     * @param RDS_PARENT_REF the value for BTR_CONTROL.RDS_PARENT_REF
     */
    public void setRDS_PARENT_REF(String RDS_PARENT_REF) {
        this.RDS_PARENT_REF = RDS_PARENT_REF == null ? null : RDS_PARENT_REF.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTR_CONTROL.RDS_FOLDER_NAME
     *
     * @return the value of BTR_CONTROL.RDS_FOLDER_NAME
     */
    public String getRDS_FOLDER_NAME() {
        return RDS_FOLDER_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTR_CONTROL.RDS_FOLDER_NAME
     *
     * @param RDS_FOLDER_NAME the value for BTR_CONTROL.RDS_FOLDER_NAME
     */
    public void setRDS_FOLDER_NAME(String RDS_FOLDER_NAME) {
        this.RDS_FOLDER_NAME = RDS_FOLDER_NAME == null ? null : RDS_FOLDER_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTR_CONTROL.ACBRD_AMOUNT
     *
     * @return the value of BTR_CONTROL.ACBRD_AMOUNT
     */
    public BigDecimal getACBRD_AMOUNT() {
        return ACBRD_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTR_CONTROL.ACBRD_AMOUNT
     *
     * @param ACBRD_AMOUNT the value for BTR_CONTROL.ACBRD_AMOUNT
     */
    public void setACBRD_AMOUNT(BigDecimal ACBRD_AMOUNT) {
        this.ACBRD_AMOUNT = ACBRD_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTR_CONTROL.SCHED_PATH
     *
     * @return the value of BTR_CONTROL.SCHED_PATH
     */
    public String getSCHED_PATH() {
        return SCHED_PATH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTR_CONTROL.SCHED_PATH
     *
     * @param SCHED_PATH the value for BTR_CONTROL.SCHED_PATH
     */
    public void setSCHED_PATH(String SCHED_PATH) {
        this.SCHED_PATH = SCHED_PATH == null ? null : SCHED_PATH.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTR_CONTROL.CDR_AMT
     *
     * @return the value of BTR_CONTROL.CDR_AMT
     */
    public BigDecimal getCDR_AMT() {
        return CDR_AMT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTR_CONTROL.CDR_AMT
     *
     * @param CDR_AMT the value for BTR_CONTROL.CDR_AMT
     */
    public void setCDR_AMT(BigDecimal CDR_AMT) {
        this.CDR_AMT = CDR_AMT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTR_CONTROL.ADD_REF
     *
     * @return the value of BTR_CONTROL.ADD_REF
     */
    public String getADD_REF() {
        return ADD_REF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTR_CONTROL.ADD_REF
     *
     * @param ADD_REF the value for BTR_CONTROL.ADD_REF
     */
    public void setADD_REF(String ADD_REF) {
        this.ADD_REF = ADD_REF == null ? null : ADD_REF.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTR_CONTROL.CB_COUNTRY_CODE
     *
     * @return the value of BTR_CONTROL.CB_COUNTRY_CODE
     */
    public String getCB_COUNTRY_CODE() {
        return CB_COUNTRY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTR_CONTROL.CB_COUNTRY_CODE
     *
     * @param CB_COUNTRY_CODE the value for BTR_CONTROL.CB_COUNTRY_CODE
     */
    public void setCB_COUNTRY_CODE(String CB_COUNTRY_CODE) {
        this.CB_COUNTRY_CODE = CB_COUNTRY_CODE == null ? null : CB_COUNTRY_CODE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTR_CONTROL.TRADE_VALUE
     *
     * @return the value of BTR_CONTROL.TRADE_VALUE
     */
    public String getTRADE_VALUE() {
        return TRADE_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTR_CONTROL.TRADE_VALUE
     *
     * @param TRADE_VALUE the value for BTR_CONTROL.TRADE_VALUE
     */
    public void setTRADE_VALUE(String TRADE_VALUE) {
        this.TRADE_VALUE = TRADE_VALUE == null ? null : TRADE_VALUE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTR_CONTROL.SITCOM_ENABLE_YN
     *
     * @return the value of BTR_CONTROL.SITCOM_ENABLE_YN
     */
    public String getSITCOM_ENABLE_YN() {
        return SITCOM_ENABLE_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTR_CONTROL.SITCOM_ENABLE_YN
     *
     * @param SITCOM_ENABLE_YN the value for BTR_CONTROL.SITCOM_ENABLE_YN
     */
    public void setSITCOM_ENABLE_YN(String SITCOM_ENABLE_YN) {
        this.SITCOM_ENABLE_YN = SITCOM_ENABLE_YN == null ? null : SITCOM_ENABLE_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTR_CONTROL.SITCOM_TEXT
     *
     * @return the value of BTR_CONTROL.SITCOM_TEXT
     */
    public String getSITCOM_TEXT() {
        return SITCOM_TEXT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTR_CONTROL.SITCOM_TEXT
     *
     * @param SITCOM_TEXT the value for BTR_CONTROL.SITCOM_TEXT
     */
    public void setSITCOM_TEXT(String SITCOM_TEXT) {
        this.SITCOM_TEXT = SITCOM_TEXT == null ? null : SITCOM_TEXT.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTR_CONTROL.SITCOM_LOCATION
     *
     * @return the value of BTR_CONTROL.SITCOM_LOCATION
     */
    public String getSITCOM_LOCATION() {
        return SITCOM_LOCATION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTR_CONTROL.SITCOM_LOCATION
     *
     * @param SITCOM_LOCATION the value for BTR_CONTROL.SITCOM_LOCATION
     */
    public void setSITCOM_LOCATION(String SITCOM_LOCATION) {
        this.SITCOM_LOCATION = SITCOM_LOCATION == null ? null : SITCOM_LOCATION.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTR_CONTROL.DATE_UPDATED
     *
     * @return the value of BTR_CONTROL.DATE_UPDATED
     */
    public Date getDATE_UPDATED() {
        return DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTR_CONTROL.DATE_UPDATED
     *
     * @param DATE_UPDATED the value for BTR_CONTROL.DATE_UPDATED
     */
    public void setDATE_UPDATED(Date DATE_UPDATED) {
        this.DATE_UPDATED = DATE_UPDATED;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTR_CONTROL.ARGUMENTS_ENABLE_YN
     *
     * @return the value of BTR_CONTROL.ARGUMENTS_ENABLE_YN
     */
    public String getARGUMENTS_ENABLE_YN() {
        return ARGUMENTS_ENABLE_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTR_CONTROL.ARGUMENTS_ENABLE_YN
     *
     * @param ARGUMENTS_ENABLE_YN the value for BTR_CONTROL.ARGUMENTS_ENABLE_YN
     */
    public void setARGUMENTS_ENABLE_YN(String ARGUMENTS_ENABLE_YN) {
        this.ARGUMENTS_ENABLE_YN = ARGUMENTS_ENABLE_YN ;
    }
}