package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;
import java.util.Date;

public class CBK_RPT_LINEVO extends BaseVO {
    /**
     * This field corresponds to the database column CBK_RPT_LINE.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column CBK_RPT_LINE.LINE_NBR
     */
    private BigDecimal LINE_NBR;

    /**
     * This field corresponds to the database column CBK_RPT_LINE.REP_REF
     */
    private String REP_REF;

    /**
     * This field corresponds to the database column CBK_RPT_LINE.CSV_ITEM_ID
     */
    private String CSV_ITEM_ID;

    /**
     * This field corresponds to the database column CBK_RPT_LINE.DATE_UPDATED
     */
    private Date DATE_UPDATED;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CBK_RPT_LINE.COMP_CODE
     *
     * @return the value of CBK_RPT_LINE.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CBK_RPT_LINE.COMP_CODE
     *
     * @param COMP_CODE the value for CBK_RPT_LINE.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CBK_RPT_LINE.LINE_NBR
     *
     * @return the value of CBK_RPT_LINE.LINE_NBR
     */
    public BigDecimal getLINE_NBR() {
        return LINE_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CBK_RPT_LINE.LINE_NBR
     *
     * @param LINE_NBR the value for CBK_RPT_LINE.LINE_NBR
     */
    public void setLINE_NBR(BigDecimal LINE_NBR) {
        this.LINE_NBR = LINE_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CBK_RPT_LINE.REP_REF
     *
     * @return the value of CBK_RPT_LINE.REP_REF
     */
    public String getREP_REF() {
        return REP_REF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CBK_RPT_LINE.REP_REF
     *
     * @param REP_REF the value for CBK_RPT_LINE.REP_REF
     */
    public void setREP_REF(String REP_REF) {
        this.REP_REF = REP_REF == null ? null : REP_REF.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CBK_RPT_LINE.CSV_ITEM_ID
     *
     * @return the value of CBK_RPT_LINE.CSV_ITEM_ID
     */
    public String getCSV_ITEM_ID() {
        return CSV_ITEM_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CBK_RPT_LINE.CSV_ITEM_ID
     *
     * @param CSV_ITEM_ID the value for CBK_RPT_LINE.CSV_ITEM_ID
     */
    public void setCSV_ITEM_ID(String CSV_ITEM_ID) {
        this.CSV_ITEM_ID = CSV_ITEM_ID == null ? null : CSV_ITEM_ID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CBK_RPT_LINE.DATE_UPDATED
     *
     * @return the value of CBK_RPT_LINE.DATE_UPDATED
     */
    public Date getDATE_UPDATED() {
        return DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CBK_RPT_LINE.DATE_UPDATED
     *
     * @param DATE_UPDATED the value for CBK_RPT_LINE.DATE_UPDATED
     */
    public void setDATE_UPDATED(Date DATE_UPDATED) {
        this.DATE_UPDATED = DATE_UPDATED;
    }
}