package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;
import java.util.Date;

public class COLMNTMPLTVO extends BaseVO {
    /**
     * This field corresponds to the database column COLMNTMPLT.CODE
     */
    private BigDecimal CODE;

    /**
     * This field corresponds to the database column COLMNTMPLT.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column COLMNTMPLT.LINE_NBR
     */
    private BigDecimal LINE_NBR;

    /**
     * This field corresponds to the database column COLMNTMPLT.BRIEF_NAME_ENG
     */
    private String BRIEF_NAME_ENG;

    /**
     * This field corresponds to the database column COLMNTMPLT.BRIEF_NAME_ARAB
     */
    private String BRIEF_NAME_ARAB;

    /**
     * This field corresponds to the database column COLMNTMPLT.COL_TYPE
     */
    private String COL_TYPE;

    /**
     * This field corresponds to the database column COLMNTMPLT.FROM_DATE
     */
    private Date FROM_DATE;

    /**
     * This field corresponds to the database column COLMNTMPLT.TO_DATE
     */
    private Date TO_DATE;

    /**
     * This field corresponds to the database column COLMNTMPLT.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column COLMNTMPLT.DATE_CREATED
     */
    private Date DATE_CREATED;

    /**
     * This field corresponds to the database column COLMNTMPLT.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column COLMNTMPLT.DATE_MODIFIED
     */
    private Date DATE_MODIFIED;

    /**
     * This field corresponds to the database column COLMNTMPLT.COMP
     */
    private BigDecimal COMP;

    /**
     * This field corresponds to the database column COLMNTMPLT.FROM_BRANCH
     */
    private BigDecimal FROM_BRANCH;

    /**
     * This field corresponds to the database column COLMNTMPLT.TO_BRANCH
     */
    private BigDecimal TO_BRANCH;

    /**
     * This field corresponds to the database column COLMNTMPLT.FROM_CY
     */
    private BigDecimal FROM_CY;

    /**
     * This field corresponds to the database column COLMNTMPLT.TO_CY
     */
    private BigDecimal TO_CY;

    /**
     * This field corresponds to the database column COLMNTMPLT.FROM_DIV
     */
    private BigDecimal FROM_DIV;

    /**
     * This field corresponds to the database column COLMNTMPLT.TO_DIV
     */
    private BigDecimal TO_DIV;

    /**
     * This field corresponds to the database column COLMNTMPLT.FROM_DEPT
     */
    private BigDecimal FROM_DEPT;

    /**
     * This field corresponds to the database column COLMNTMPLT.TO_DEPT
     */
    private BigDecimal TO_DEPT;

    /**
     * This field corresponds to the database column COLMNTMPLT.FROM_UNIT
     */
    private BigDecimal FROM_UNIT;

    /**
     * This field corresponds to the database column COLMNTMPLT.TO_UNIT
     */
    private BigDecimal TO_UNIT;

    /**
     * This field corresponds to the database column COLMNTMPLT.PRINT_PAPER_SIZE
     */
    private BigDecimal PRINT_PAPER_SIZE;

    /**
     * This field corresponds to the database column COLMNTMPLT.PRINT_PAPER_ORIENTATION
     */
    private BigDecimal PRINT_PAPER_ORIENTATION;

    /**
     * This field corresponds to the database column COLMNTMPLT.BOLD
     */
    private String BOLD;

    /**
     * This field corresponds to the database column COLMNTMPLT.DISP_COL_TOT_ZERO
     */
    private String DISP_COL_TOT_ZERO;

    /**
     * This field corresponds to the database column COLMNTMPLT.EXPRESSION_LINES
     */
    private String EXPRESSION_LINES;

    /**
     * This field corresponds to the database column COLMNTMPLT.ALL_CRITERIA
     */
    private String ALL_CRITERIA;

    /**
     * This field corresponds to the database column COLMNTMPLT.FROM_REGION
     */
    private BigDecimal FROM_REGION;

    /**
     * This field corresponds to the database column COLMNTMPLT.TO_REGION
     */
    private BigDecimal TO_REGION;

    /**
     * This field corresponds to the database column COLMNTMPLT.DATE_UPDATED
     */
    private Date DATE_UPDATED;

    /**
     * This field corresponds to the database column COLMNTMPLT.SPECIFY_DAY
     */
    private String SPECIFY_DAY;

    /**
     * This field corresponds to the database column COLMNTMPLT.SPECIFY_MONTH
     */
    private String SPECIFY_MONTH;

    /**
     * This field corresponds to the database column COLMNTMPLT.EXPRESSION
     */
    private String EXPRESSION;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLMNTMPLT.CODE
     *
     * @return the value of COLMNTMPLT.CODE
     */
    public BigDecimal getCODE() {
        return CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLMNTMPLT.CODE
     *
     * @param CODE the value for COLMNTMPLT.CODE
     */
    public void setCODE(BigDecimal CODE) {
        this.CODE = CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLMNTMPLT.COMP_CODE
     *
     * @return the value of COLMNTMPLT.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLMNTMPLT.COMP_CODE
     *
     * @param COMP_CODE the value for COLMNTMPLT.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLMNTMPLT.LINE_NBR
     *
     * @return the value of COLMNTMPLT.LINE_NBR
     */
    public BigDecimal getLINE_NBR() {
        return LINE_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLMNTMPLT.LINE_NBR
     *
     * @param LINE_NBR the value for COLMNTMPLT.LINE_NBR
     */
    public void setLINE_NBR(BigDecimal LINE_NBR) {
        this.LINE_NBR = LINE_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLMNTMPLT.BRIEF_NAME_ENG
     *
     * @return the value of COLMNTMPLT.BRIEF_NAME_ENG
     */
    public String getBRIEF_NAME_ENG() {
        return BRIEF_NAME_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLMNTMPLT.BRIEF_NAME_ENG
     *
     * @param BRIEF_NAME_ENG the value for COLMNTMPLT.BRIEF_NAME_ENG
     */
    public void setBRIEF_NAME_ENG(String BRIEF_NAME_ENG) {
        this.BRIEF_NAME_ENG = BRIEF_NAME_ENG == null ? null : BRIEF_NAME_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLMNTMPLT.BRIEF_NAME_ARAB
     *
     * @return the value of COLMNTMPLT.BRIEF_NAME_ARAB
     */
    public String getBRIEF_NAME_ARAB() {
        return BRIEF_NAME_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLMNTMPLT.BRIEF_NAME_ARAB
     *
     * @param BRIEF_NAME_ARAB the value for COLMNTMPLT.BRIEF_NAME_ARAB
     */
    public void setBRIEF_NAME_ARAB(String BRIEF_NAME_ARAB) {
        this.BRIEF_NAME_ARAB = BRIEF_NAME_ARAB == null ? null : BRIEF_NAME_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLMNTMPLT.COL_TYPE
     *
     * @return the value of COLMNTMPLT.COL_TYPE
     */
    public String getCOL_TYPE() {
        return COL_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLMNTMPLT.COL_TYPE
     *
     * @param COL_TYPE the value for COLMNTMPLT.COL_TYPE
     */
    public void setCOL_TYPE(String COL_TYPE) {
        this.COL_TYPE = COL_TYPE == null ? null : COL_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLMNTMPLT.FROM_DATE
     *
     * @return the value of COLMNTMPLT.FROM_DATE
     */
    public Date getFROM_DATE() {
        return FROM_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLMNTMPLT.FROM_DATE
     *
     * @param FROM_DATE the value for COLMNTMPLT.FROM_DATE
     */
    public void setFROM_DATE(Date FROM_DATE) {
        this.FROM_DATE = FROM_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLMNTMPLT.TO_DATE
     *
     * @return the value of COLMNTMPLT.TO_DATE
     */
    public Date getTO_DATE() {
        return TO_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLMNTMPLT.TO_DATE
     *
     * @param TO_DATE the value for COLMNTMPLT.TO_DATE
     */
    public void setTO_DATE(Date TO_DATE) {
        this.TO_DATE = TO_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLMNTMPLT.CREATED_BY
     *
     * @return the value of COLMNTMPLT.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLMNTMPLT.CREATED_BY
     *
     * @param CREATED_BY the value for COLMNTMPLT.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLMNTMPLT.DATE_CREATED
     *
     * @return the value of COLMNTMPLT.DATE_CREATED
     */
    public Date getDATE_CREATED() {
        return DATE_CREATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLMNTMPLT.DATE_CREATED
     *
     * @param DATE_CREATED the value for COLMNTMPLT.DATE_CREATED
     */
    public void setDATE_CREATED(Date DATE_CREATED) {
        this.DATE_CREATED = DATE_CREATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLMNTMPLT.MODIFIED_BY
     *
     * @return the value of COLMNTMPLT.MODIFIED_BY
     */
    public String getMODIFIED_BY() {
        return MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLMNTMPLT.MODIFIED_BY
     *
     * @param MODIFIED_BY the value for COLMNTMPLT.MODIFIED_BY
     */
    public void setMODIFIED_BY(String MODIFIED_BY) {
        this.MODIFIED_BY = MODIFIED_BY == null ? null : MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLMNTMPLT.DATE_MODIFIED
     *
     * @return the value of COLMNTMPLT.DATE_MODIFIED
     */
    public Date getDATE_MODIFIED() {
        return DATE_MODIFIED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLMNTMPLT.DATE_MODIFIED
     *
     * @param DATE_MODIFIED the value for COLMNTMPLT.DATE_MODIFIED
     */
    public void setDATE_MODIFIED(Date DATE_MODIFIED) {
        this.DATE_MODIFIED = DATE_MODIFIED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLMNTMPLT.COMP
     *
     * @return the value of COLMNTMPLT.COMP
     */
    public BigDecimal getCOMP() {
        return COMP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLMNTMPLT.COMP
     *
     * @param COMP the value for COLMNTMPLT.COMP
     */
    public void setCOMP(BigDecimal COMP) {
        this.COMP = COMP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLMNTMPLT.FROM_BRANCH
     *
     * @return the value of COLMNTMPLT.FROM_BRANCH
     */
    public BigDecimal getFROM_BRANCH() {
        return FROM_BRANCH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLMNTMPLT.FROM_BRANCH
     *
     * @param FROM_BRANCH the value for COLMNTMPLT.FROM_BRANCH
     */
    public void setFROM_BRANCH(BigDecimal FROM_BRANCH) {
        this.FROM_BRANCH = FROM_BRANCH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLMNTMPLT.TO_BRANCH
     *
     * @return the value of COLMNTMPLT.TO_BRANCH
     */
    public BigDecimal getTO_BRANCH() {
        return TO_BRANCH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLMNTMPLT.TO_BRANCH
     *
     * @param TO_BRANCH the value for COLMNTMPLT.TO_BRANCH
     */
    public void setTO_BRANCH(BigDecimal TO_BRANCH) {
        this.TO_BRANCH = TO_BRANCH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLMNTMPLT.FROM_CY
     *
     * @return the value of COLMNTMPLT.FROM_CY
     */
    public BigDecimal getFROM_CY() {
        return FROM_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLMNTMPLT.FROM_CY
     *
     * @param FROM_CY the value for COLMNTMPLT.FROM_CY
     */
    public void setFROM_CY(BigDecimal FROM_CY) {
        this.FROM_CY = FROM_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLMNTMPLT.TO_CY
     *
     * @return the value of COLMNTMPLT.TO_CY
     */
    public BigDecimal getTO_CY() {
        return TO_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLMNTMPLT.TO_CY
     *
     * @param TO_CY the value for COLMNTMPLT.TO_CY
     */
    public void setTO_CY(BigDecimal TO_CY) {
        this.TO_CY = TO_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLMNTMPLT.FROM_DIV
     *
     * @return the value of COLMNTMPLT.FROM_DIV
     */
    public BigDecimal getFROM_DIV() {
        return FROM_DIV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLMNTMPLT.FROM_DIV
     *
     * @param FROM_DIV the value for COLMNTMPLT.FROM_DIV
     */
    public void setFROM_DIV(BigDecimal FROM_DIV) {
        this.FROM_DIV = FROM_DIV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLMNTMPLT.TO_DIV
     *
     * @return the value of COLMNTMPLT.TO_DIV
     */
    public BigDecimal getTO_DIV() {
        return TO_DIV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLMNTMPLT.TO_DIV
     *
     * @param TO_DIV the value for COLMNTMPLT.TO_DIV
     */
    public void setTO_DIV(BigDecimal TO_DIV) {
        this.TO_DIV = TO_DIV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLMNTMPLT.FROM_DEPT
     *
     * @return the value of COLMNTMPLT.FROM_DEPT
     */
    public BigDecimal getFROM_DEPT() {
        return FROM_DEPT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLMNTMPLT.FROM_DEPT
     *
     * @param FROM_DEPT the value for COLMNTMPLT.FROM_DEPT
     */
    public void setFROM_DEPT(BigDecimal FROM_DEPT) {
        this.FROM_DEPT = FROM_DEPT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLMNTMPLT.TO_DEPT
     *
     * @return the value of COLMNTMPLT.TO_DEPT
     */
    public BigDecimal getTO_DEPT() {
        return TO_DEPT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLMNTMPLT.TO_DEPT
     *
     * @param TO_DEPT the value for COLMNTMPLT.TO_DEPT
     */
    public void setTO_DEPT(BigDecimal TO_DEPT) {
        this.TO_DEPT = TO_DEPT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLMNTMPLT.FROM_UNIT
     *
     * @return the value of COLMNTMPLT.FROM_UNIT
     */
    public BigDecimal getFROM_UNIT() {
        return FROM_UNIT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLMNTMPLT.FROM_UNIT
     *
     * @param FROM_UNIT the value for COLMNTMPLT.FROM_UNIT
     */
    public void setFROM_UNIT(BigDecimal FROM_UNIT) {
        this.FROM_UNIT = FROM_UNIT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLMNTMPLT.TO_UNIT
     *
     * @return the value of COLMNTMPLT.TO_UNIT
     */
    public BigDecimal getTO_UNIT() {
        return TO_UNIT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLMNTMPLT.TO_UNIT
     *
     * @param TO_UNIT the value for COLMNTMPLT.TO_UNIT
     */
    public void setTO_UNIT(BigDecimal TO_UNIT) {
        this.TO_UNIT = TO_UNIT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLMNTMPLT.PRINT_PAPER_SIZE
     *
     * @return the value of COLMNTMPLT.PRINT_PAPER_SIZE
     */
    public BigDecimal getPRINT_PAPER_SIZE() {
        return PRINT_PAPER_SIZE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLMNTMPLT.PRINT_PAPER_SIZE
     *
     * @param PRINT_PAPER_SIZE the value for COLMNTMPLT.PRINT_PAPER_SIZE
     */
    public void setPRINT_PAPER_SIZE(BigDecimal PRINT_PAPER_SIZE) {
        this.PRINT_PAPER_SIZE = PRINT_PAPER_SIZE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLMNTMPLT.PRINT_PAPER_ORIENTATION
     *
     * @return the value of COLMNTMPLT.PRINT_PAPER_ORIENTATION
     */
    public BigDecimal getPRINT_PAPER_ORIENTATION() {
        return PRINT_PAPER_ORIENTATION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLMNTMPLT.PRINT_PAPER_ORIENTATION
     *
     * @param PRINT_PAPER_ORIENTATION the value for COLMNTMPLT.PRINT_PAPER_ORIENTATION
     */
    public void setPRINT_PAPER_ORIENTATION(BigDecimal PRINT_PAPER_ORIENTATION) {
        this.PRINT_PAPER_ORIENTATION = PRINT_PAPER_ORIENTATION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLMNTMPLT.BOLD
     *
     * @return the value of COLMNTMPLT.BOLD
     */
    public String getBOLD() {
        return BOLD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLMNTMPLT.BOLD
     *
     * @param BOLD the value for COLMNTMPLT.BOLD
     */
    public void setBOLD(String BOLD) {
        this.BOLD = BOLD == null ? null : BOLD.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLMNTMPLT.DISP_COL_TOT_ZERO
     *
     * @return the value of COLMNTMPLT.DISP_COL_TOT_ZERO
     */
    public String getDISP_COL_TOT_ZERO() {
        return DISP_COL_TOT_ZERO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLMNTMPLT.DISP_COL_TOT_ZERO
     *
     * @param DISP_COL_TOT_ZERO the value for COLMNTMPLT.DISP_COL_TOT_ZERO
     */
    public void setDISP_COL_TOT_ZERO(String DISP_COL_TOT_ZERO) {
        this.DISP_COL_TOT_ZERO = DISP_COL_TOT_ZERO == null ? null : DISP_COL_TOT_ZERO.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLMNTMPLT.EXPRESSION_LINES
     *
     * @return the value of COLMNTMPLT.EXPRESSION_LINES
     */
    public String getEXPRESSION_LINES() {
        return EXPRESSION_LINES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLMNTMPLT.EXPRESSION_LINES
     *
     * @param EXPRESSION_LINES the value for COLMNTMPLT.EXPRESSION_LINES
     */
    public void setEXPRESSION_LINES(String EXPRESSION_LINES) {
        this.EXPRESSION_LINES = EXPRESSION_LINES == null ? null : EXPRESSION_LINES.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLMNTMPLT.ALL_CRITERIA
     *
     * @return the value of COLMNTMPLT.ALL_CRITERIA
     */
    public String getALL_CRITERIA() {
        return ALL_CRITERIA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLMNTMPLT.ALL_CRITERIA
     *
     * @param ALL_CRITERIA the value for COLMNTMPLT.ALL_CRITERIA
     */
    public void setALL_CRITERIA(String ALL_CRITERIA) {
        this.ALL_CRITERIA = ALL_CRITERIA == null ? null : ALL_CRITERIA.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLMNTMPLT.FROM_REGION
     *
     * @return the value of COLMNTMPLT.FROM_REGION
     */
    public BigDecimal getFROM_REGION() {
        return FROM_REGION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLMNTMPLT.FROM_REGION
     *
     * @param FROM_REGION the value for COLMNTMPLT.FROM_REGION
     */
    public void setFROM_REGION(BigDecimal FROM_REGION) {
        this.FROM_REGION = FROM_REGION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLMNTMPLT.TO_REGION
     *
     * @return the value of COLMNTMPLT.TO_REGION
     */
    public BigDecimal getTO_REGION() {
        return TO_REGION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLMNTMPLT.TO_REGION
     *
     * @param TO_REGION the value for COLMNTMPLT.TO_REGION
     */
    public void setTO_REGION(BigDecimal TO_REGION) {
        this.TO_REGION = TO_REGION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLMNTMPLT.DATE_UPDATED
     *
     * @return the value of COLMNTMPLT.DATE_UPDATED
     */
    public Date getDATE_UPDATED() {
        return DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLMNTMPLT.DATE_UPDATED
     *
     * @param DATE_UPDATED the value for COLMNTMPLT.DATE_UPDATED
     */
    public void setDATE_UPDATED(Date DATE_UPDATED) {
        this.DATE_UPDATED = DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLMNTMPLT.SPECIFY_DAY
     *
     * @return the value of COLMNTMPLT.SPECIFY_DAY
     */
    public String getSPECIFY_DAY() {
        return SPECIFY_DAY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLMNTMPLT.SPECIFY_DAY
     *
     * @param SPECIFY_DAY the value for COLMNTMPLT.SPECIFY_DAY
     */
    public void setSPECIFY_DAY(String SPECIFY_DAY) {
        this.SPECIFY_DAY = SPECIFY_DAY == null ? null : SPECIFY_DAY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLMNTMPLT.SPECIFY_MONTH
     *
     * @return the value of COLMNTMPLT.SPECIFY_MONTH
     */
    public String getSPECIFY_MONTH() {
        return SPECIFY_MONTH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLMNTMPLT.SPECIFY_MONTH
     *
     * @param SPECIFY_MONTH the value for COLMNTMPLT.SPECIFY_MONTH
     */
    public void setSPECIFY_MONTH(String SPECIFY_MONTH) {
        this.SPECIFY_MONTH = SPECIFY_MONTH == null ? null : SPECIFY_MONTH.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLMNTMPLT.EXPRESSION
     *
     * @return the value of COLMNTMPLT.EXPRESSION
     */
    public String getEXPRESSION() {
        return EXPRESSION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLMNTMPLT.EXPRESSION
     *
     * @param EXPRESSION the value for COLMNTMPLT.EXPRESSION
     */
    public void setEXPRESSION(String EXPRESSION) {
        this.EXPRESSION = EXPRESSION == null ? null : EXPRESSION.trim();
    }
}