package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;
import java.util.Date;

public class FTR_TMPLT_EXPRVO extends BaseVO {
    /**
     * This field corresponds to the database column FTR_TMPLT_EXPR.CODE
     */
    private BigDecimal CODE;

    /**
     * This field corresponds to the database column FTR_TMPLT_EXPR.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column FTR_TMPLT_EXPR.LINE_NO
     */
    private BigDecimal LINE_NO;

    /**
     * This field corresponds to the database column FTR_TMPLT_EXPR.TMPLT_LINE_NO
     */
    private BigDecimal TMPLT_LINE_NO;

    /**
     * This field corresponds to the database column FTR_TMPLT_EXPR.TMPLT_TYPE
     */
    private String TMPLT_TYPE;

    /**
     * This field corresponds to the database column FTR_TMPLT_EXPR.EXP_TYPE
     */
    private String EXP_TYPE;

    /**
     * This field corresponds to the database column FTR_TMPLT_EXPR.LEFT_OPERATOR
     */
    private String LEFT_OPERATOR;

    /**
     * This field corresponds to the database column FTR_TMPLT_EXPR.EXP_LINE
     */
    private BigDecimal EXP_LINE;

    /**
     * This field corresponds to the database column FTR_TMPLT_EXPR.EXP_VALUE
     */
    private BigDecimal EXP_VALUE;

    /**
     * This field corresponds to the database column FTR_TMPLT_EXPR.RIGHT_OPERATOR
     */
    private String RIGHT_OPERATOR;

    /**
     * This field corresponds to the database column FTR_TMPLT_EXPR.OPERATOR
     */
    private String OPERATOR;

    /**
     * This field corresponds to the database column FTR_TMPLT_EXPR.DATE_UPDATED
     */
    private Date DATE_UPDATED;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FTR_TMPLT_EXPR.CODE
     *
     * @return the value of FTR_TMPLT_EXPR.CODE
     */
    public BigDecimal getCODE() {
        return CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FTR_TMPLT_EXPR.CODE
     *
     * @param CODE the value for FTR_TMPLT_EXPR.CODE
     */
    public void setCODE(BigDecimal CODE) {
        this.CODE = CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FTR_TMPLT_EXPR.COMP_CODE
     *
     * @return the value of FTR_TMPLT_EXPR.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FTR_TMPLT_EXPR.COMP_CODE
     *
     * @param COMP_CODE the value for FTR_TMPLT_EXPR.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FTR_TMPLT_EXPR.LINE_NO
     *
     * @return the value of FTR_TMPLT_EXPR.LINE_NO
     */
    public BigDecimal getLINE_NO() {
        return LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FTR_TMPLT_EXPR.LINE_NO
     *
     * @param LINE_NO the value for FTR_TMPLT_EXPR.LINE_NO
     */
    public void setLINE_NO(BigDecimal LINE_NO) {
        this.LINE_NO = LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FTR_TMPLT_EXPR.TMPLT_LINE_NO
     *
     * @return the value of FTR_TMPLT_EXPR.TMPLT_LINE_NO
     */
    public BigDecimal getTMPLT_LINE_NO() {
        return TMPLT_LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FTR_TMPLT_EXPR.TMPLT_LINE_NO
     *
     * @param TMPLT_LINE_NO the value for FTR_TMPLT_EXPR.TMPLT_LINE_NO
     */
    public void setTMPLT_LINE_NO(BigDecimal TMPLT_LINE_NO) {
        this.TMPLT_LINE_NO = TMPLT_LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FTR_TMPLT_EXPR.TMPLT_TYPE
     *
     * @return the value of FTR_TMPLT_EXPR.TMPLT_TYPE
     */
    public String getTMPLT_TYPE() {
        return TMPLT_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FTR_TMPLT_EXPR.TMPLT_TYPE
     *
     * @param TMPLT_TYPE the value for FTR_TMPLT_EXPR.TMPLT_TYPE
     */
    public void setTMPLT_TYPE(String TMPLT_TYPE) {
        this.TMPLT_TYPE = TMPLT_TYPE == null ? null : TMPLT_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FTR_TMPLT_EXPR.EXP_TYPE
     *
     * @return the value of FTR_TMPLT_EXPR.EXP_TYPE
     */
    public String getEXP_TYPE() {
        return EXP_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FTR_TMPLT_EXPR.EXP_TYPE
     *
     * @param EXP_TYPE the value for FTR_TMPLT_EXPR.EXP_TYPE
     */
    public void setEXP_TYPE(String EXP_TYPE) {
        this.EXP_TYPE = EXP_TYPE == null ? null : EXP_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FTR_TMPLT_EXPR.LEFT_OPERATOR
     *
     * @return the value of FTR_TMPLT_EXPR.LEFT_OPERATOR
     */
    public String getLEFT_OPERATOR() {
        return LEFT_OPERATOR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FTR_TMPLT_EXPR.LEFT_OPERATOR
     *
     * @param LEFT_OPERATOR the value for FTR_TMPLT_EXPR.LEFT_OPERATOR
     */
    public void setLEFT_OPERATOR(String LEFT_OPERATOR) {
        this.LEFT_OPERATOR = LEFT_OPERATOR == null ? null : LEFT_OPERATOR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FTR_TMPLT_EXPR.EXP_LINE
     *
     * @return the value of FTR_TMPLT_EXPR.EXP_LINE
     */
    public BigDecimal getEXP_LINE() {
        return EXP_LINE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FTR_TMPLT_EXPR.EXP_LINE
     *
     * @param EXP_LINE the value for FTR_TMPLT_EXPR.EXP_LINE
     */
    public void setEXP_LINE(BigDecimal EXP_LINE) {
        this.EXP_LINE = EXP_LINE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FTR_TMPLT_EXPR.EXP_VALUE
     *
     * @return the value of FTR_TMPLT_EXPR.EXP_VALUE
     */
    public BigDecimal getEXP_VALUE() {
        return EXP_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FTR_TMPLT_EXPR.EXP_VALUE
     *
     * @param EXP_VALUE the value for FTR_TMPLT_EXPR.EXP_VALUE
     */
    public void setEXP_VALUE(BigDecimal EXP_VALUE) {
        this.EXP_VALUE = EXP_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FTR_TMPLT_EXPR.RIGHT_OPERATOR
     *
     * @return the value of FTR_TMPLT_EXPR.RIGHT_OPERATOR
     */
    public String getRIGHT_OPERATOR() {
        return RIGHT_OPERATOR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FTR_TMPLT_EXPR.RIGHT_OPERATOR
     *
     * @param RIGHT_OPERATOR the value for FTR_TMPLT_EXPR.RIGHT_OPERATOR
     */
    public void setRIGHT_OPERATOR(String RIGHT_OPERATOR) {
        this.RIGHT_OPERATOR = RIGHT_OPERATOR == null ? null : RIGHT_OPERATOR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FTR_TMPLT_EXPR.OPERATOR
     *
     * @return the value of FTR_TMPLT_EXPR.OPERATOR
     */
    public String getOPERATOR() {
        return OPERATOR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FTR_TMPLT_EXPR.OPERATOR
     *
     * @param OPERATOR the value for FTR_TMPLT_EXPR.OPERATOR
     */
    public void setOPERATOR(String OPERATOR) {
        this.OPERATOR = OPERATOR == null ? null : OPERATOR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FTR_TMPLT_EXPR.DATE_UPDATED
     *
     * @return the value of FTR_TMPLT_EXPR.DATE_UPDATED
     */
    public Date getDATE_UPDATED() {
        return DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FTR_TMPLT_EXPR.DATE_UPDATED
     *
     * @param DATE_UPDATED the value for FTR_TMPLT_EXPR.DATE_UPDATED
     */
    public void setDATE_UPDATED(Date DATE_UPDATED) {
        this.DATE_UPDATED = DATE_UPDATED;
    }
}