package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class FTR_CB_CODEVOKey extends BaseVO {
    /**
     * This field corresponds to the database column FTR_CB_CODE.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column FTR_CB_CODE.ENTITY_CODE
     */
    private BigDecimal ENTITY_CODE;

    /**
     * This field corresponds to the database column FTR_CB_CODE.ENTITY_TYPE
     */
    private String ENTITY_TYPE;

    /**
     * This field corresponds to the database column FTR_CB_CODE.SUB_ENTITY_CODE
     */
    private BigDecimal SUB_ENTITY_CODE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FTR_CB_CODE.COMP_CODE
     *
     * @return the value of FTR_CB_CODE.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FTR_CB_CODE.COMP_CODE
     *
     * @param COMP_CODE the value for FTR_CB_CODE.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FTR_CB_CODE.ENTITY_CODE
     *
     * @return the value of FTR_CB_CODE.ENTITY_CODE
     */
    public BigDecimal getENTITY_CODE() {
        return ENTITY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FTR_CB_CODE.ENTITY_CODE
     *
     * @param ENTITY_CODE the value for FTR_CB_CODE.ENTITY_CODE
     */
    public void setENTITY_CODE(BigDecimal ENTITY_CODE) {
        this.ENTITY_CODE = ENTITY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FTR_CB_CODE.ENTITY_TYPE
     *
     * @return the value of FTR_CB_CODE.ENTITY_TYPE
     */
    public String getENTITY_TYPE() {
        return ENTITY_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FTR_CB_CODE.ENTITY_TYPE
     *
     * @param ENTITY_TYPE the value for FTR_CB_CODE.ENTITY_TYPE
     */
    public void setENTITY_TYPE(String ENTITY_TYPE) {
        this.ENTITY_TYPE = ENTITY_TYPE == null ? null : ENTITY_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FTR_CB_CODE.SUB_ENTITY_CODE
     *
     * @return the value of FTR_CB_CODE.SUB_ENTITY_CODE
     */
    public BigDecimal getSUB_ENTITY_CODE() {
        return SUB_ENTITY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FTR_CB_CODE.SUB_ENTITY_CODE
     *
     * @param SUB_ENTITY_CODE the value for FTR_CB_CODE.SUB_ENTITY_CODE
     */
    public void setSUB_ENTITY_CODE(BigDecimal SUB_ENTITY_CODE) {
        this.SUB_ENTITY_CODE = SUB_ENTITY_CODE;
    }
}