package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;
import java.util.Date;

public class FTR_ACCOUNTSVO extends BaseVO {
    /**
     * This field corresponds to the database column FTR_ACCOUNTS.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;

    /**
     * This field corresponds to the database column FTR_ACCOUNTS.CIF_SUB_NO
     */
    private BigDecimal CIF_SUB_NO;

    /**
     * This field corresponds to the database column FTR_ACCOUNTS.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column FTR_ACCOUNTS.CURRENCY_CODE
     */
    private BigDecimal CURRENCY_CODE;

    /**
     * This field corresponds to the database column FTR_ACCOUNTS.GL_CODE
     */
    private BigDecimal GL_CODE;

    /**
     * This field corresponds to the database column FTR_ACCOUNTS.SL_NO
     */
    private BigDecimal SL_NO;

    /**
     * This field corresponds to the database column FTR_ACCOUNTS.SUB_LINE_NBR
     */
    private BigDecimal SUB_LINE_NBR;

    /**
     * This field corresponds to the database column FTR_ACCOUNTS.TEMP_CODE
     */
    private BigDecimal TEMP_CODE;

    /**
     * This field corresponds to the database column FTR_ACCOUNTS.TMPLT_LINE_NBR
     */
    private BigDecimal TMPLT_LINE_NBR;

    /**
     * This field corresponds to the database column FTR_ACCOUNTS.INCLUDE
     */
    private String INCLUDE;

    /**
     * This field corresponds to the database column FTR_ACCOUNTS.DATE_UPDATED
     */
    private Date DATE_UPDATED;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FTR_ACCOUNTS.BRANCH_CODE
     *
     * @return the value of FTR_ACCOUNTS.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FTR_ACCOUNTS.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for FTR_ACCOUNTS.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FTR_ACCOUNTS.CIF_SUB_NO
     *
     * @return the value of FTR_ACCOUNTS.CIF_SUB_NO
     */
    public BigDecimal getCIF_SUB_NO() {
        return CIF_SUB_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FTR_ACCOUNTS.CIF_SUB_NO
     *
     * @param CIF_SUB_NO the value for FTR_ACCOUNTS.CIF_SUB_NO
     */
    public void setCIF_SUB_NO(BigDecimal CIF_SUB_NO) {
        this.CIF_SUB_NO = CIF_SUB_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FTR_ACCOUNTS.COMP_CODE
     *
     * @return the value of FTR_ACCOUNTS.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FTR_ACCOUNTS.COMP_CODE
     *
     * @param COMP_CODE the value for FTR_ACCOUNTS.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FTR_ACCOUNTS.CURRENCY_CODE
     *
     * @return the value of FTR_ACCOUNTS.CURRENCY_CODE
     */
    public BigDecimal getCURRENCY_CODE() {
        return CURRENCY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FTR_ACCOUNTS.CURRENCY_CODE
     *
     * @param CURRENCY_CODE the value for FTR_ACCOUNTS.CURRENCY_CODE
     */
    public void setCURRENCY_CODE(BigDecimal CURRENCY_CODE) {
        this.CURRENCY_CODE = CURRENCY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FTR_ACCOUNTS.GL_CODE
     *
     * @return the value of FTR_ACCOUNTS.GL_CODE
     */
    public BigDecimal getGL_CODE() {
        return GL_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FTR_ACCOUNTS.GL_CODE
     *
     * @param GL_CODE the value for FTR_ACCOUNTS.GL_CODE
     */
    public void setGL_CODE(BigDecimal GL_CODE) {
        this.GL_CODE = GL_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FTR_ACCOUNTS.SL_NO
     *
     * @return the value of FTR_ACCOUNTS.SL_NO
     */
    public BigDecimal getSL_NO() {
        return SL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FTR_ACCOUNTS.SL_NO
     *
     * @param SL_NO the value for FTR_ACCOUNTS.SL_NO
     */
    public void setSL_NO(BigDecimal SL_NO) {
        this.SL_NO = SL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FTR_ACCOUNTS.SUB_LINE_NBR
     *
     * @return the value of FTR_ACCOUNTS.SUB_LINE_NBR
     */
    public BigDecimal getSUB_LINE_NBR() {
        return SUB_LINE_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FTR_ACCOUNTS.SUB_LINE_NBR
     *
     * @param SUB_LINE_NBR the value for FTR_ACCOUNTS.SUB_LINE_NBR
     */
    public void setSUB_LINE_NBR(BigDecimal SUB_LINE_NBR) {
        this.SUB_LINE_NBR = SUB_LINE_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FTR_ACCOUNTS.TEMP_CODE
     *
     * @return the value of FTR_ACCOUNTS.TEMP_CODE
     */
    public BigDecimal getTEMP_CODE() {
        return TEMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FTR_ACCOUNTS.TEMP_CODE
     *
     * @param TEMP_CODE the value for FTR_ACCOUNTS.TEMP_CODE
     */
    public void setTEMP_CODE(BigDecimal TEMP_CODE) {
        this.TEMP_CODE = TEMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FTR_ACCOUNTS.TMPLT_LINE_NBR
     *
     * @return the value of FTR_ACCOUNTS.TMPLT_LINE_NBR
     */
    public BigDecimal getTMPLT_LINE_NBR() {
        return TMPLT_LINE_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FTR_ACCOUNTS.TMPLT_LINE_NBR
     *
     * @param TMPLT_LINE_NBR the value for FTR_ACCOUNTS.TMPLT_LINE_NBR
     */
    public void setTMPLT_LINE_NBR(BigDecimal TMPLT_LINE_NBR) {
        this.TMPLT_LINE_NBR = TMPLT_LINE_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FTR_ACCOUNTS.INCLUDE
     *
     * @return the value of FTR_ACCOUNTS.INCLUDE
     */
    public String getINCLUDE() {
        return INCLUDE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FTR_ACCOUNTS.INCLUDE
     *
     * @param INCLUDE the value for FTR_ACCOUNTS.INCLUDE
     */
    public void setINCLUDE(String INCLUDE) {
        this.INCLUDE = INCLUDE == null ? null : INCLUDE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FTR_ACCOUNTS.DATE_UPDATED
     *
     * @return the value of FTR_ACCOUNTS.DATE_UPDATED
     */
    public Date getDATE_UPDATED() {
        return DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FTR_ACCOUNTS.DATE_UPDATED
     *
     * @param DATE_UPDATED the value for FTR_ACCOUNTS.DATE_UPDATED
     */
    public void setDATE_UPDATED(Date DATE_UPDATED) {
        this.DATE_UPDATED = DATE_UPDATED;
    }
}