package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class FTR_OPTVOKey extends BaseVO {
    /**
     * This field corresponds to the database column FTR_OPT.CODE
     */
    private BigDecimal CODE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FTR_OPT.CODE
     *
     * @return the value of FTR_OPT.CODE
     */
    public BigDecimal getCODE() {
        return CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FTR_OPT.CODE
     *
     * @param CODE the value for FTR_OPT.CODE
     */
    public void setCODE(BigDecimal CODE) {
        this.CODE = CODE;
    }
}