package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;
import java.util.Date;

public class FTR_MISMATCH_REPORTVO extends BaseVO {
    /**
     * This field corresponds to the database column FTR_MISMATCH_REPORT.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column FTR_MISMATCH_REPORT.LINE_NO
     */
    private BigDecimal LINE_NO;

    /**
     * This field corresponds to the database column FTR_MISMATCH_REPORT.SUB_LINE_NO
     */
    private BigDecimal SUB_LINE_NO;

    /**
     * This field corresponds to the database column FTR_MISMATCH_REPORT.TMPLT_CODE
     */
    private BigDecimal TMPLT_CODE;

    /**
     * This field corresponds to the database column FTR_MISMATCH_REPORT.TMPLT_CODE1
     */
    private BigDecimal TMPLT_CODE1;

    /**
     * This field corresponds to the database column FTR_MISMATCH_REPORT.DATE_UPDATED
     */
    private Date DATE_UPDATED;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FTR_MISMATCH_REPORT.COMP_CODE
     *
     * @return the value of FTR_MISMATCH_REPORT.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FTR_MISMATCH_REPORT.COMP_CODE
     *
     * @param COMP_CODE the value for FTR_MISMATCH_REPORT.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FTR_MISMATCH_REPORT.LINE_NO
     *
     * @return the value of FTR_MISMATCH_REPORT.LINE_NO
     */
    public BigDecimal getLINE_NO() {
        return LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FTR_MISMATCH_REPORT.LINE_NO
     *
     * @param LINE_NO the value for FTR_MISMATCH_REPORT.LINE_NO
     */
    public void setLINE_NO(BigDecimal LINE_NO) {
        this.LINE_NO = LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FTR_MISMATCH_REPORT.SUB_LINE_NO
     *
     * @return the value of FTR_MISMATCH_REPORT.SUB_LINE_NO
     */
    public BigDecimal getSUB_LINE_NO() {
        return SUB_LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FTR_MISMATCH_REPORT.SUB_LINE_NO
     *
     * @param SUB_LINE_NO the value for FTR_MISMATCH_REPORT.SUB_LINE_NO
     */
    public void setSUB_LINE_NO(BigDecimal SUB_LINE_NO) {
        this.SUB_LINE_NO = SUB_LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FTR_MISMATCH_REPORT.TMPLT_CODE
     *
     * @return the value of FTR_MISMATCH_REPORT.TMPLT_CODE
     */
    public BigDecimal getTMPLT_CODE() {
        return TMPLT_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FTR_MISMATCH_REPORT.TMPLT_CODE
     *
     * @param TMPLT_CODE the value for FTR_MISMATCH_REPORT.TMPLT_CODE
     */
    public void setTMPLT_CODE(BigDecimal TMPLT_CODE) {
        this.TMPLT_CODE = TMPLT_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FTR_MISMATCH_REPORT.TMPLT_CODE1
     *
     * @return the value of FTR_MISMATCH_REPORT.TMPLT_CODE1
     */
    public BigDecimal getTMPLT_CODE1() {
        return TMPLT_CODE1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FTR_MISMATCH_REPORT.TMPLT_CODE1
     *
     * @param TMPLT_CODE1 the value for FTR_MISMATCH_REPORT.TMPLT_CODE1
     */
    public void setTMPLT_CODE1(BigDecimal TMPLT_CODE1) {
        this.TMPLT_CODE1 = TMPLT_CODE1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FTR_MISMATCH_REPORT.DATE_UPDATED
     *
     * @return the value of FTR_MISMATCH_REPORT.DATE_UPDATED
     */
    public Date getDATE_UPDATED() {
        return DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FTR_MISMATCH_REPORT.DATE_UPDATED
     *
     * @param DATE_UPDATED the value for FTR_MISMATCH_REPORT.DATE_UPDATED
     */
    public void setDATE_UPDATED(Date DATE_UPDATED) {
        this.DATE_UPDATED = DATE_UPDATED;
    }
}