package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class FTR_OPTVO extends FTR_OPTVOKey {
    /**
     * This field corresponds to the database column FTR_OPT.PROG_REF
     */
    private String PROG_REF;

    /**
     * This field corresponds to the database column FTR_OPT.PARENT_REF
     */
    private String PARENT_REF;

    /**
     * This field corresponds to the database column FTR_OPT.BRIEF_NAME_ENG
     */
    private String BRIEF_NAME_ENG;

    /**
     * This field corresponds to the database column FTR_OPT.BRIEF_NAME_ARAB
     */
    private String BRIEF_NAME_ARAB;

    /**
     * This field corresponds to the database column FTR_OPT.DISP_ORDER
     */
    private BigDecimal DISP_ORDER;

    /**
     * This field corresponds to the database column FTR_OPT.TMPLT_CODE
     */
    private BigDecimal TMPLT_CODE;

    /**
     * This field corresponds to the database column FTR_OPT.COLUMN_CODE
     */
    private BigDecimal COLUMN_CODE;

    /**
     * This field corresponds to the database column FTR_OPT.APP_NAME
     */
    private String APP_NAME;

    /**
     * This field corresponds to the database column FTR_OPT.DATE_UPDATED
     */
    private Date DATE_UPDATED;

    /**
     * This field corresponds to the database column FTR_OPT.GROUP_BY
     */
    private String GROUP_BY;

    /**
     * This field corresponds to the database column FTR_OPT.REP_TYPE
     */
    private String REP_TYPE;

    /**
     * This field corresponds to the database column FTR_OPT.ROW_COLMN
     */
    private BigDecimal ROW_COLMN;

    /**
     * This field corresponds to the database column FTR_OPT.STANDARD_FLAG_YN
     */
    private String STANDARD_FLAG_YN;

    /**
     * This field corresponds to the database column FTR_OPT.REP_CURRENCY
     */
    private BigDecimal REP_CURRENCY;
    
    /**
     * This field corresponds to the database column IMAL141_DEV_O11.FTR_OPT.GENERATED_FILE_NAME
     */
    private String GENERATED_FILE_NAME;



    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FTR_OPT.PROG_REF
     *
     * @return the value of FTR_OPT.PROG_REF
     */
    public String getPROG_REF() {
        return PROG_REF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FTR_OPT.PROG_REF
     *
     * @param PROG_REF the value for FTR_OPT.PROG_REF
     */
    public void setPROG_REF(String PROG_REF) {
        this.PROG_REF = PROG_REF == null ? null : PROG_REF.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FTR_OPT.PARENT_REF
     *
     * @return the value of FTR_OPT.PARENT_REF
     */
    public String getPARENT_REF() {
        return PARENT_REF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FTR_OPT.PARENT_REF
     *
     * @param PARENT_REF the value for FTR_OPT.PARENT_REF
     */
    public void setPARENT_REF(String PARENT_REF) {
        this.PARENT_REF = PARENT_REF == null ? null : PARENT_REF.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FTR_OPT.BRIEF_NAME_ENG
     *
     * @return the value of FTR_OPT.BRIEF_NAME_ENG
     */
    public String getBRIEF_NAME_ENG() {
        return BRIEF_NAME_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FTR_OPT.BRIEF_NAME_ENG
     *
     * @param BRIEF_NAME_ENG the value for FTR_OPT.BRIEF_NAME_ENG
     */
    public void setBRIEF_NAME_ENG(String BRIEF_NAME_ENG) {
        this.BRIEF_NAME_ENG = BRIEF_NAME_ENG == null ? null : BRIEF_NAME_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FTR_OPT.BRIEF_NAME_ARAB
     *
     * @return the value of FTR_OPT.BRIEF_NAME_ARAB
     */
    public String getBRIEF_NAME_ARAB() {
        return BRIEF_NAME_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FTR_OPT.BRIEF_NAME_ARAB
     *
     * @param BRIEF_NAME_ARAB the value for FTR_OPT.BRIEF_NAME_ARAB
     */
    public void setBRIEF_NAME_ARAB(String BRIEF_NAME_ARAB) {
        this.BRIEF_NAME_ARAB = BRIEF_NAME_ARAB == null ? null : BRIEF_NAME_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FTR_OPT.DISP_ORDER
     *
     * @return the value of FTR_OPT.DISP_ORDER
     */
    public BigDecimal getDISP_ORDER() {
        return DISP_ORDER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FTR_OPT.DISP_ORDER
     *
     * @param DISP_ORDER the value for FTR_OPT.DISP_ORDER
     */
    public void setDISP_ORDER(BigDecimal DISP_ORDER) {
        this.DISP_ORDER = DISP_ORDER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FTR_OPT.TMPLT_CODE
     *
     * @return the value of FTR_OPT.TMPLT_CODE
     */
    public BigDecimal getTMPLT_CODE() {
        return TMPLT_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FTR_OPT.TMPLT_CODE
     *
     * @param TMPLT_CODE the value for FTR_OPT.TMPLT_CODE
     */
    public void setTMPLT_CODE(BigDecimal TMPLT_CODE) {
        this.TMPLT_CODE = TMPLT_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FTR_OPT.COLUMN_CODE
     *
     * @return the value of FTR_OPT.COLUMN_CODE
     */
    public BigDecimal getCOLUMN_CODE() {
        return COLUMN_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FTR_OPT.COLUMN_CODE
     *
     * @param COLUMN_CODE the value for FTR_OPT.COLUMN_CODE
     */
    public void setCOLUMN_CODE(BigDecimal COLUMN_CODE) {
        this.COLUMN_CODE = COLUMN_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FTR_OPT.APP_NAME
     *
     * @return the value of FTR_OPT.APP_NAME
     */
    public String getAPP_NAME() {
        return APP_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FTR_OPT.APP_NAME
     *
     * @param APP_NAME the value for FTR_OPT.APP_NAME
     */
    public void setAPP_NAME(String APP_NAME) {
        this.APP_NAME = APP_NAME == null ? null : APP_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FTR_OPT.DATE_UPDATED
     *
     * @return the value of FTR_OPT.DATE_UPDATED
     */
    public Date getDATE_UPDATED() {
        return DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FTR_OPT.DATE_UPDATED
     *
     * @param DATE_UPDATED the value for FTR_OPT.DATE_UPDATED
     */
    public void setDATE_UPDATED(Date DATE_UPDATED) {
        this.DATE_UPDATED = DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FTR_OPT.GROUP_BY
     *
     * @return the value of FTR_OPT.GROUP_BY
     */
    public String getGROUP_BY() {
        return GROUP_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FTR_OPT.GROUP_BY
     *
     * @param GROUP_BY the value for FTR_OPT.GROUP_BY
     */
    public void setGROUP_BY(String GROUP_BY) {
        this.GROUP_BY = GROUP_BY == null ? null : GROUP_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FTR_OPT.REP_TYPE
     *
     * @return the value of FTR_OPT.REP_TYPE
     */
    public String getREP_TYPE() {
        return REP_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FTR_OPT.REP_TYPE
     *
     * @param REP_TYPE the value for FTR_OPT.REP_TYPE
     */
    public void setREP_TYPE(String REP_TYPE) {
        this.REP_TYPE = REP_TYPE == null ? null : REP_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FTR_OPT.ROW_COLMN
     *
     * @return the value of FTR_OPT.ROW_COLMN
     */
    public BigDecimal getROW_COLMN() {
        return ROW_COLMN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FTR_OPT.ROW_COLMN
     *
     * @param ROW_COLMN the value for FTR_OPT.ROW_COLMN
     */
    public void setROW_COLMN(BigDecimal ROW_COLMN) {
        this.ROW_COLMN = ROW_COLMN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FTR_OPT.STANDARD_FLAG_YN
     *
     * @return the value of FTR_OPT.STANDARD_FLAG_YN
     */
    public String getSTANDARD_FLAG_YN() {
        return STANDARD_FLAG_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FTR_OPT.STANDARD_FLAG_YN
     *
     * @param STANDARD_FLAG_YN the value for FTR_OPT.STANDARD_FLAG_YN
     */
    public void setSTANDARD_FLAG_YN(String STANDARD_FLAG_YN) {
        this.STANDARD_FLAG_YN = STANDARD_FLAG_YN == null ? null : STANDARD_FLAG_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FTR_OPT.REP_CURRENCY
     *
     * @return the value of FTR_OPT.REP_CURRENCY
     */
    public BigDecimal getREP_CURRENCY() {
        return REP_CURRENCY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FTR_OPT.REP_CURRENCY
     *
     * @param REP_CURRENCY the value for FTR_OPT.REP_CURRENCY
     */
    public void setREP_CURRENCY(BigDecimal REP_CURRENCY) {
        this.REP_CURRENCY = REP_CURRENCY;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMAL141_DEV_O11.FTR_OPT.GENERATED_FILE_NAME
     *
     * @return the value of IMAL141_DEV_O11.FTR_OPT.GENERATED_FILE_NAME
     */
    public String getGENERATED_FILE_NAME() {
        return GENERATED_FILE_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMAL141_DEV_O11.FTR_OPT.GENERATED_FILE_NAME
     *
     * @param GENERATED_FILE_NAME the value for IMAL141_DEV_O11.FTR_OPT.GENERATED_FILE_NAME
     */
    public void setGENERATED_FILE_NAME(String GENERATED_FILE_NAME) {
        this.GENERATED_FILE_NAME = GENERATED_FILE_NAME == null ? null : GENERATED_FILE_NAME.trim();
    }
}