package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

import com.path.lib.vo.BaseVO;

public class GLSHEADERVO extends BaseVO {
    /**
     * This field corresponds to the database column GLSHEADER.CODE
     */
    private BigDecimal CODE;

    /**
     * This field corresponds to the database column GLSHEADER.BRIEF_NAME_ENG
     */
    private String BRIEF_NAME_ENG;

    /**
     * This field corresponds to the database column GLSHEADER.BRIEF_NAME_ARAB
     */
    private String BRIEF_NAME_ARAB;

    /**
     * This field corresponds to the database column GLSHEADER.LEFT1
     */
    private String LEFT1;

    /**
     * This field corresponds to the database column GLSHEADER.LEFT2
     */
    private String LEFT2;

    /**
     * This field corresponds to the database column GLSHEADER.LEFT3
     */
    private String LEFT3;

    /**
     * This field corresponds to the database column GLSHEADER.LEFT4
     */
    private String LEFT4;

    /**
     * This field corresponds to the database column GLSHEADER.CENTER1
     */
    private String CENTER1;

    /**
     * This field corresponds to the database column GLSHEADER.CENTER2
     */
    private String CENTER2;

    /**
     * This field corresponds to the database column GLSHEADER.CENTER3
     */
    private String CENTER3;

    /**
     * This field corresponds to the database column GLSHEADER.RIGHT1
     */
    private String RIGHT1;

    /**
     * This field corresponds to the database column GLSHEADER.RIGHT2
     */
    private String RIGHT2;

    /**
     * This field corresponds to the database column GLSHEADER.RIGHT3
     */
    private String RIGHT3;

    /**
     * This field corresponds to the database column GLSHEADER.RIGHT4
     */
    private String RIGHT4;

    /**
     * This field corresponds to the database column GLSHEADER.DATE_UPDATED
     */
    private Date DATE_UPDATED;

    /**
     * This field corresponds to the database column GLSHEADER.TEMPLATE_TYPE
     */
    private String TEMPLATE_TYPE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GLSHEADER.CODE
     *
     * @return the value of GLSHEADER.CODE
     */
    public BigDecimal getCODE() {
        return CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GLSHEADER.CODE
     *
     * @param CODE the value for GLSHEADER.CODE
     */
    public void setCODE(BigDecimal CODE) {
        this.CODE = CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GLSHEADER.BRIEF_NAME_ENG
     *
     * @return the value of GLSHEADER.BRIEF_NAME_ENG
     */
    public String getBRIEF_NAME_ENG() {
        return BRIEF_NAME_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GLSHEADER.BRIEF_NAME_ENG
     *
     * @param BRIEF_NAME_ENG the value for GLSHEADER.BRIEF_NAME_ENG
     */
    public void setBRIEF_NAME_ENG(String BRIEF_NAME_ENG) {
        this.BRIEF_NAME_ENG = BRIEF_NAME_ENG == null ? null : BRIEF_NAME_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GLSHEADER.BRIEF_NAME_ARAB
     *
     * @return the value of GLSHEADER.BRIEF_NAME_ARAB
     */
    public String getBRIEF_NAME_ARAB() {
        return BRIEF_NAME_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GLSHEADER.BRIEF_NAME_ARAB
     *
     * @param BRIEF_NAME_ARAB the value for GLSHEADER.BRIEF_NAME_ARAB
     */
    public void setBRIEF_NAME_ARAB(String BRIEF_NAME_ARAB) {
        this.BRIEF_NAME_ARAB = BRIEF_NAME_ARAB == null ? null : BRIEF_NAME_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GLSHEADER.LEFT1
     *
     * @return the value of GLSHEADER.LEFT1
     */
    public String getLEFT1() {
        return LEFT1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GLSHEADER.LEFT1
     *
     * @param LEFT1 the value for GLSHEADER.LEFT1
     */
    public void setLEFT1(String LEFT1) {
        this.LEFT1 = LEFT1 == null ? null : LEFT1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GLSHEADER.LEFT2
     *
     * @return the value of GLSHEADER.LEFT2
     */
    public String getLEFT2() {
        return LEFT2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GLSHEADER.LEFT2
     *
     * @param LEFT2 the value for GLSHEADER.LEFT2
     */
    public void setLEFT2(String LEFT2) {
        this.LEFT2 = LEFT2 == null ? null : LEFT2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GLSHEADER.LEFT3
     *
     * @return the value of GLSHEADER.LEFT3
     */
    public String getLEFT3() {
        return LEFT3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GLSHEADER.LEFT3
     *
     * @param LEFT3 the value for GLSHEADER.LEFT3
     */
    public void setLEFT3(String LEFT3) {
        this.LEFT3 = LEFT3 == null ? null : LEFT3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GLSHEADER.LEFT4
     *
     * @return the value of GLSHEADER.LEFT4
     */
    public String getLEFT4() {
        return LEFT4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GLSHEADER.LEFT4
     *
     * @param LEFT4 the value for GLSHEADER.LEFT4
     */
    public void setLEFT4(String LEFT4) {
        this.LEFT4 = LEFT4 == null ? null : LEFT4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GLSHEADER.CENTER1
     *
     * @return the value of GLSHEADER.CENTER1
     */
    public String getCENTER1() {
        return CENTER1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GLSHEADER.CENTER1
     *
     * @param CENTER1 the value for GLSHEADER.CENTER1
     */
    public void setCENTER1(String CENTER1) {
        this.CENTER1 = CENTER1 == null ? null : CENTER1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GLSHEADER.CENTER2
     *
     * @return the value of GLSHEADER.CENTER2
     */
    public String getCENTER2() {
        return CENTER2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GLSHEADER.CENTER2
     *
     * @param CENTER2 the value for GLSHEADER.CENTER2
     */
    public void setCENTER2(String CENTER2) {
        this.CENTER2 = CENTER2 == null ? null : CENTER2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GLSHEADER.CENTER3
     *
     * @return the value of GLSHEADER.CENTER3
     */
    public String getCENTER3() {
        return CENTER3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GLSHEADER.CENTER3
     *
     * @param CENTER3 the value for GLSHEADER.CENTER3
     */
    public void setCENTER3(String CENTER3) {
        this.CENTER3 = CENTER3 == null ? null : CENTER3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GLSHEADER.RIGHT1
     *
     * @return the value of GLSHEADER.RIGHT1
     */
    public String getRIGHT1() {
        return RIGHT1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GLSHEADER.RIGHT1
     *
     * @param RIGHT1 the value for GLSHEADER.RIGHT1
     */
    public void setRIGHT1(String RIGHT1) {
        this.RIGHT1 = RIGHT1 == null ? null : RIGHT1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GLSHEADER.RIGHT2
     *
     * @return the value of GLSHEADER.RIGHT2
     */
    public String getRIGHT2() {
        return RIGHT2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GLSHEADER.RIGHT2
     *
     * @param RIGHT2 the value for GLSHEADER.RIGHT2
     */
    public void setRIGHT2(String RIGHT2) {
        this.RIGHT2 = RIGHT2 == null ? null : RIGHT2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GLSHEADER.RIGHT3
     *
     * @return the value of GLSHEADER.RIGHT3
     */
    public String getRIGHT3() {
        return RIGHT3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GLSHEADER.RIGHT3
     *
     * @param RIGHT3 the value for GLSHEADER.RIGHT3
     */
    public void setRIGHT3(String RIGHT3) {
        this.RIGHT3 = RIGHT3 == null ? null : RIGHT3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GLSHEADER.RIGHT4
     *
     * @return the value of GLSHEADER.RIGHT4
     */
    public String getRIGHT4() {
        return RIGHT4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GLSHEADER.RIGHT4
     *
     * @param RIGHT4 the value for GLSHEADER.RIGHT4
     */
    public void setRIGHT4(String RIGHT4) {
        this.RIGHT4 = RIGHT4 == null ? null : RIGHT4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GLSHEADER.DATE_UPDATED
     *
     * @return the value of GLSHEADER.DATE_UPDATED
     */
    public Date getDATE_UPDATED() {
        return DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GLSHEADER.DATE_UPDATED
     *
     * @param DATE_UPDATED the value for GLSHEADER.DATE_UPDATED
     */
    public void setDATE_UPDATED(Date DATE_UPDATED) {
        this.DATE_UPDATED = DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GLSHEADER.TEMPLATE_TYPE
     *
     * @return the value of GLSHEADER.TEMPLATE_TYPE
     */
    public String getTEMPLATE_TYPE() {
        return TEMPLATE_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GLSHEADER.TEMPLATE_TYPE
     *
     * @param TEMPLATE_TYPE the value for GLSHEADER.TEMPLATE_TYPE
     */
    public void setTEMPLATE_TYPE(String TEMPLATE_TYPE) {
        this.TEMPLATE_TYPE = TEMPLATE_TYPE == null ? null : TEMPLATE_TYPE.trim();
    }
}