package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;
import java.util.Date;

public class GLSTMPLTGLSDETVO extends BaseVO {
    /**
     * This field corresponds to the database column GLSTMPLTGLSDET.CODE
     */
    private BigDecimal CODE;

    /**
     * This field corresponds to the database column GLSTMPLTGLSDET.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column GLSTMPLTGLSDET.LINE_NBR
     */
    private BigDecimal LINE_NBR;

    /**
     * This field corresponds to the database column GLSTMPLTGLSDET.LINE_NBR_DET
     */
    private BigDecimal LINE_NBR_DET;

    /**
     * This field corresponds to the database column GLSTMPLTGLSDET.TEMPLATE_TYPE
     */
    private String TEMPLATE_TYPE;

    /**
     * This field corresponds to the database column GLSTMPLTGLSDET.FROM_GL
     */
    private BigDecimal FROM_GL;

    /**
     * This field corresponds to the database column GLSTMPLTGLSDET.TO_GL
     */
    private BigDecimal TO_GL;

    /**
     * This field corresponds to the database column GLSTMPLTGLSDET.GL_COMP
     */
    private BigDecimal GL_COMP;

    /**
     * This field corresponds to the database column GLSTMPLTGLSDET.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;

    /**
     * This field corresponds to the database column GLSTMPLTGLSDET.DIV_CODE
     */
    private BigDecimal DIV_CODE;

    /**
     * This field corresponds to the database column GLSTMPLTGLSDET.DEPT_CODE
     */
    private BigDecimal DEPT_CODE;

    /**
     * This field corresponds to the database column GLSTMPLTGLSDET.GL_SIGN
     */
    private String GL_SIGN;

    /**
     * This field corresponds to the database column GLSTMPLTGLSDET.ADD_SUBTRACT
     */
    private BigDecimal ADD_SUBTRACT;

    /**
     * This field corresponds to the database column GLSTMPLTGLSDET.PERCENTAGE
     */
    private BigDecimal PERCENTAGE;

    /**
     * This field corresponds to the database column GLSTMPLTGLSDET.EXCLUDE_CLOSING_ENTRY
     */
    private String EXCLUDE_CLOSING_ENTRY;

    /**
     * This field corresponds to the database column GLSTMPLTGLSDET.CALC_TYPE
     */
    private String CALC_TYPE;

    /**
     * This field corresponds to the database column GLSTMPLTGLSDET.CONTRIBUTION
     */
    private String CONTRIBUTION;

    /**
     * This field corresponds to the database column GLSTMPLTGLSDET.DATE_UPDATED
     */
    private Date DATE_UPDATED;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GLSTMPLTGLSDET.CODE
     *
     * @return the value of GLSTMPLTGLSDET.CODE
     */
    public BigDecimal getCODE() {
        return CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GLSTMPLTGLSDET.CODE
     *
     * @param CODE the value for GLSTMPLTGLSDET.CODE
     */
    public void setCODE(BigDecimal CODE) {
        this.CODE = CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GLSTMPLTGLSDET.COMP_CODE
     *
     * @return the value of GLSTMPLTGLSDET.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GLSTMPLTGLSDET.COMP_CODE
     *
     * @param COMP_CODE the value for GLSTMPLTGLSDET.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GLSTMPLTGLSDET.LINE_NBR
     *
     * @return the value of GLSTMPLTGLSDET.LINE_NBR
     */
    public BigDecimal getLINE_NBR() {
        return LINE_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GLSTMPLTGLSDET.LINE_NBR
     *
     * @param LINE_NBR the value for GLSTMPLTGLSDET.LINE_NBR
     */
    public void setLINE_NBR(BigDecimal LINE_NBR) {
        this.LINE_NBR = LINE_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GLSTMPLTGLSDET.LINE_NBR_DET
     *
     * @return the value of GLSTMPLTGLSDET.LINE_NBR_DET
     */
    public BigDecimal getLINE_NBR_DET() {
        return LINE_NBR_DET;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GLSTMPLTGLSDET.LINE_NBR_DET
     *
     * @param LINE_NBR_DET the value for GLSTMPLTGLSDET.LINE_NBR_DET
     */
    public void setLINE_NBR_DET(BigDecimal LINE_NBR_DET) {
        this.LINE_NBR_DET = LINE_NBR_DET;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GLSTMPLTGLSDET.TEMPLATE_TYPE
     *
     * @return the value of GLSTMPLTGLSDET.TEMPLATE_TYPE
     */
    public String getTEMPLATE_TYPE() {
        return TEMPLATE_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GLSTMPLTGLSDET.TEMPLATE_TYPE
     *
     * @param TEMPLATE_TYPE the value for GLSTMPLTGLSDET.TEMPLATE_TYPE
     */
    public void setTEMPLATE_TYPE(String TEMPLATE_TYPE) {
        this.TEMPLATE_TYPE = TEMPLATE_TYPE == null ? null : TEMPLATE_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GLSTMPLTGLSDET.FROM_GL
     *
     * @return the value of GLSTMPLTGLSDET.FROM_GL
     */
    public BigDecimal getFROM_GL() {
        return FROM_GL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GLSTMPLTGLSDET.FROM_GL
     *
     * @param FROM_GL the value for GLSTMPLTGLSDET.FROM_GL
     */
    public void setFROM_GL(BigDecimal FROM_GL) {
        this.FROM_GL = FROM_GL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GLSTMPLTGLSDET.TO_GL
     *
     * @return the value of GLSTMPLTGLSDET.TO_GL
     */
    public BigDecimal getTO_GL() {
        return TO_GL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GLSTMPLTGLSDET.TO_GL
     *
     * @param TO_GL the value for GLSTMPLTGLSDET.TO_GL
     */
    public void setTO_GL(BigDecimal TO_GL) {
        this.TO_GL = TO_GL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GLSTMPLTGLSDET.GL_COMP
     *
     * @return the value of GLSTMPLTGLSDET.GL_COMP
     */
    public BigDecimal getGL_COMP() {
        return GL_COMP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GLSTMPLTGLSDET.GL_COMP
     *
     * @param GL_COMP the value for GLSTMPLTGLSDET.GL_COMP
     */
    public void setGL_COMP(BigDecimal GL_COMP) {
        this.GL_COMP = GL_COMP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GLSTMPLTGLSDET.BRANCH_CODE
     *
     * @return the value of GLSTMPLTGLSDET.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GLSTMPLTGLSDET.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for GLSTMPLTGLSDET.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GLSTMPLTGLSDET.DIV_CODE
     *
     * @return the value of GLSTMPLTGLSDET.DIV_CODE
     */
    public BigDecimal getDIV_CODE() {
        return DIV_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GLSTMPLTGLSDET.DIV_CODE
     *
     * @param DIV_CODE the value for GLSTMPLTGLSDET.DIV_CODE
     */
    public void setDIV_CODE(BigDecimal DIV_CODE) {
        this.DIV_CODE = DIV_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GLSTMPLTGLSDET.DEPT_CODE
     *
     * @return the value of GLSTMPLTGLSDET.DEPT_CODE
     */
    public BigDecimal getDEPT_CODE() {
        return DEPT_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GLSTMPLTGLSDET.DEPT_CODE
     *
     * @param DEPT_CODE the value for GLSTMPLTGLSDET.DEPT_CODE
     */
    public void setDEPT_CODE(BigDecimal DEPT_CODE) {
        this.DEPT_CODE = DEPT_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GLSTMPLTGLSDET.GL_SIGN
     *
     * @return the value of GLSTMPLTGLSDET.GL_SIGN
     */
    public String getGL_SIGN() {
        return GL_SIGN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GLSTMPLTGLSDET.GL_SIGN
     *
     * @param GL_SIGN the value for GLSTMPLTGLSDET.GL_SIGN
     */
    public void setGL_SIGN(String GL_SIGN) {
        this.GL_SIGN = GL_SIGN == null ? null : GL_SIGN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GLSTMPLTGLSDET.ADD_SUBTRACT
     *
     * @return the value of GLSTMPLTGLSDET.ADD_SUBTRACT
     */
    public BigDecimal getADD_SUBTRACT() {
        return ADD_SUBTRACT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GLSTMPLTGLSDET.ADD_SUBTRACT
     *
     * @param ADD_SUBTRACT the value for GLSTMPLTGLSDET.ADD_SUBTRACT
     */
    public void setADD_SUBTRACT(BigDecimal ADD_SUBTRACT) {
        this.ADD_SUBTRACT = ADD_SUBTRACT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GLSTMPLTGLSDET.PERCENTAGE
     *
     * @return the value of GLSTMPLTGLSDET.PERCENTAGE
     */
    public BigDecimal getPERCENTAGE() {
        return PERCENTAGE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GLSTMPLTGLSDET.PERCENTAGE
     *
     * @param PERCENTAGE the value for GLSTMPLTGLSDET.PERCENTAGE
     */
    public void setPERCENTAGE(BigDecimal PERCENTAGE) {
        this.PERCENTAGE = PERCENTAGE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GLSTMPLTGLSDET.EXCLUDE_CLOSING_ENTRY
     *
     * @return the value of GLSTMPLTGLSDET.EXCLUDE_CLOSING_ENTRY
     */
    public String getEXCLUDE_CLOSING_ENTRY() {
        return EXCLUDE_CLOSING_ENTRY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GLSTMPLTGLSDET.EXCLUDE_CLOSING_ENTRY
     *
     * @param EXCLUDE_CLOSING_ENTRY the value for GLSTMPLTGLSDET.EXCLUDE_CLOSING_ENTRY
     */
    public void setEXCLUDE_CLOSING_ENTRY(String EXCLUDE_CLOSING_ENTRY) {
        this.EXCLUDE_CLOSING_ENTRY = EXCLUDE_CLOSING_ENTRY == null ? null : EXCLUDE_CLOSING_ENTRY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GLSTMPLTGLSDET.CALC_TYPE
     *
     * @return the value of GLSTMPLTGLSDET.CALC_TYPE
     */
    public String getCALC_TYPE() {
        return CALC_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GLSTMPLTGLSDET.CALC_TYPE
     *
     * @param CALC_TYPE the value for GLSTMPLTGLSDET.CALC_TYPE
     */
    public void setCALC_TYPE(String CALC_TYPE) {
        this.CALC_TYPE = CALC_TYPE == null ? null : CALC_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GLSTMPLTGLSDET.CONTRIBUTION
     *
     * @return the value of GLSTMPLTGLSDET.CONTRIBUTION
     */
    public String getCONTRIBUTION() {
        return CONTRIBUTION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GLSTMPLTGLSDET.CONTRIBUTION
     *
     * @param CONTRIBUTION the value for GLSTMPLTGLSDET.CONTRIBUTION
     */
    public void setCONTRIBUTION(String CONTRIBUTION) {
        this.CONTRIBUTION = CONTRIBUTION == null ? null : CONTRIBUTION.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GLSTMPLTGLSDET.DATE_UPDATED
     *
     * @return the value of GLSTMPLTGLSDET.DATE_UPDATED
     */
    public Date getDATE_UPDATED() {
        return DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GLSTMPLTGLSDET.DATE_UPDATED
     *
     * @param DATE_UPDATED the value for GLSTMPLTGLSDET.DATE_UPDATED
     */
    public void setDATE_UPDATED(Date DATE_UPDATED) {
        this.DATE_UPDATED = DATE_UPDATED;
    }
}