package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class GLSTMPLT_CRITERIAVO  extends GLSTMPLT_CRITERIAVOKey  {
    /**
     * This field corresponds to the database column GLSTMPLT_CRITERIA.CODE
     */
    private BigDecimal CODE;

    /**
     * This field corresponds to the database column GLSTMPLT_CRITERIA.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column GLSTMPLT_CRITERIA.BRIEF_DESC_ENG
     */
    private String BRIEF_DESC_ENG;

    /**
     * This field corresponds to the database column GLSTMPLT_CRITERIA.LONG_DESC_ENG
     */
    private String LONG_DESC_ENG;

    /**
     * This field corresponds to the database column GLSTMPLT_CRITERIA.BRIEF_DESC_ARAB
     */
    private String BRIEF_DESC_ARAB;

    /**
     * This field corresponds to the database column GLSTMPLT_CRITERIA.LONG_DESC_ARAB
     */
    private String LONG_DESC_ARAB;

    /**
     * This field corresponds to the database column GLSTMPLT_CRITERIA.LINKED_IND
     */
    private String LINKED_IND;

    /**
     * This field corresponds to the database column GLSTMPLT_CRITERIA.LINKED_CODE
     */
    private BigDecimal LINKED_CODE;

    /**
     * This field corresponds to the database column GLSTMPLT_CRITERIA.CRI_TYPE
     */
    private String CRI_TYPE;

    /**
     * This field corresponds to the database column GLSTMPLT_CRITERIA.CRI_LINE_GL
     */
    private String CRI_LINE_GL;

    /**
     * This field corresponds to the database column GLSTMPLT_CRITERIA.SMART_CODE
     */
    private BigDecimal SMART_CODE;

    /**
     * This field corresponds to the database column GLSTMPLT_CRITERIA.DATE_UPDATED
     */
    private Date DATE_UPDATED;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GLSTMPLT_CRITERIA.CODE
     *
     * @return the value of GLSTMPLT_CRITERIA.CODE
     */
    public BigDecimal getCODE() {
        return CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GLSTMPLT_CRITERIA.CODE
     *
     * @param CODE the value for GLSTMPLT_CRITERIA.CODE
     */
    public void setCODE(BigDecimal CODE) {
        this.CODE = CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GLSTMPLT_CRITERIA.COMP_CODE
     *
     * @return the value of GLSTMPLT_CRITERIA.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GLSTMPLT_CRITERIA.COMP_CODE
     *
     * @param COMP_CODE the value for GLSTMPLT_CRITERIA.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GLSTMPLT_CRITERIA.BRIEF_DESC_ENG
     *
     * @return the value of GLSTMPLT_CRITERIA.BRIEF_DESC_ENG
     */
    public String getBRIEF_DESC_ENG() {
        return BRIEF_DESC_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GLSTMPLT_CRITERIA.BRIEF_DESC_ENG
     *
     * @param BRIEF_DESC_ENG the value for GLSTMPLT_CRITERIA.BRIEF_DESC_ENG
     */
    public void setBRIEF_DESC_ENG(String BRIEF_DESC_ENG) {
        this.BRIEF_DESC_ENG = BRIEF_DESC_ENG == null ? null : BRIEF_DESC_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GLSTMPLT_CRITERIA.LONG_DESC_ENG
     *
     * @return the value of GLSTMPLT_CRITERIA.LONG_DESC_ENG
     */
    public String getLONG_DESC_ENG() {
        return LONG_DESC_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GLSTMPLT_CRITERIA.LONG_DESC_ENG
     *
     * @param LONG_DESC_ENG the value for GLSTMPLT_CRITERIA.LONG_DESC_ENG
     */
    public void setLONG_DESC_ENG(String LONG_DESC_ENG) {
        this.LONG_DESC_ENG = LONG_DESC_ENG == null ? null : LONG_DESC_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GLSTMPLT_CRITERIA.BRIEF_DESC_ARAB
     *
     * @return the value of GLSTMPLT_CRITERIA.BRIEF_DESC_ARAB
     */
    public String getBRIEF_DESC_ARAB() {
        return BRIEF_DESC_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GLSTMPLT_CRITERIA.BRIEF_DESC_ARAB
     *
     * @param BRIEF_DESC_ARAB the value for GLSTMPLT_CRITERIA.BRIEF_DESC_ARAB
     */
    public void setBRIEF_DESC_ARAB(String BRIEF_DESC_ARAB) {
        this.BRIEF_DESC_ARAB = BRIEF_DESC_ARAB == null ? null : BRIEF_DESC_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GLSTMPLT_CRITERIA.LONG_DESC_ARAB
     *
     * @return the value of GLSTMPLT_CRITERIA.LONG_DESC_ARAB
     */
    public String getLONG_DESC_ARAB() {
        return LONG_DESC_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GLSTMPLT_CRITERIA.LONG_DESC_ARAB
     *
     * @param LONG_DESC_ARAB the value for GLSTMPLT_CRITERIA.LONG_DESC_ARAB
     */
    public void setLONG_DESC_ARAB(String LONG_DESC_ARAB) {
        this.LONG_DESC_ARAB = LONG_DESC_ARAB == null ? null : LONG_DESC_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GLSTMPLT_CRITERIA.LINKED_IND
     *
     * @return the value of GLSTMPLT_CRITERIA.LINKED_IND
     */
    public String getLINKED_IND() {
        return LINKED_IND;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GLSTMPLT_CRITERIA.LINKED_IND
     *
     * @param LINKED_IND the value for GLSTMPLT_CRITERIA.LINKED_IND
     */
    public void setLINKED_IND(String LINKED_IND) {
        this.LINKED_IND = LINKED_IND == null ? null : LINKED_IND.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GLSTMPLT_CRITERIA.LINKED_CODE
     *
     * @return the value of GLSTMPLT_CRITERIA.LINKED_CODE
     */
    public BigDecimal getLINKED_CODE() {
        return LINKED_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GLSTMPLT_CRITERIA.LINKED_CODE
     *
     * @param LINKED_CODE the value for GLSTMPLT_CRITERIA.LINKED_CODE
     */
    public void setLINKED_CODE(BigDecimal LINKED_CODE) {
        this.LINKED_CODE = LINKED_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GLSTMPLT_CRITERIA.CRI_TYPE
     *
     * @return the value of GLSTMPLT_CRITERIA.CRI_TYPE
     */
    public String getCRI_TYPE() {
        return CRI_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GLSTMPLT_CRITERIA.CRI_TYPE
     *
     * @param CRI_TYPE the value for GLSTMPLT_CRITERIA.CRI_TYPE
     */
    public void setCRI_TYPE(String CRI_TYPE) {
        this.CRI_TYPE = CRI_TYPE == null ? null : CRI_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GLSTMPLT_CRITERIA.CRI_LINE_GL
     *
     * @return the value of GLSTMPLT_CRITERIA.CRI_LINE_GL
     */
    public String getCRI_LINE_GL() {
        return CRI_LINE_GL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GLSTMPLT_CRITERIA.CRI_LINE_GL
     *
     * @param CRI_LINE_GL the value for GLSTMPLT_CRITERIA.CRI_LINE_GL
     */
    public void setCRI_LINE_GL(String CRI_LINE_GL) {
        this.CRI_LINE_GL = CRI_LINE_GL == null ? null : CRI_LINE_GL.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GLSTMPLT_CRITERIA.SMART_CODE
     *
     * @return the value of GLSTMPLT_CRITERIA.SMART_CODE
     */
    public BigDecimal getSMART_CODE() {
        return SMART_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GLSTMPLT_CRITERIA.SMART_CODE
     *
     * @param SMART_CODE the value for GLSTMPLT_CRITERIA.SMART_CODE
     */
    public void setSMART_CODE(BigDecimal SMART_CODE) {
        this.SMART_CODE = SMART_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GLSTMPLT_CRITERIA.DATE_UPDATED
     *
     * @return the value of GLSTMPLT_CRITERIA.DATE_UPDATED
     */
    public Date getDATE_UPDATED() {
        return DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GLSTMPLT_CRITERIA.DATE_UPDATED
     *
     * @param DATE_UPDATED the value for GLSTMPLT_CRITERIA.DATE_UPDATED
     */
    public void setDATE_UPDATED(Date DATE_UPDATED) {
        this.DATE_UPDATED = DATE_UPDATED;
    }
}