package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;
import java.util.Date;

public class GLSTMPLT_PARAM_LINKVO extends BaseVO {
    /**
     * This field corresponds to the database column GLSTMPLT_PARAM_LINK.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column GLSTMPLT_PARAM_LINK.CRITERIA_CODE
     */
    private BigDecimal CRITERIA_CODE;

    /**
     * This field corresponds to the database column GLSTMPLT_PARAM_LINK.LINE_NO
     */
    private BigDecimal LINE_NO;

    /**
     * This field corresponds to the database column GLSTMPLT_PARAM_LINK.SUB_LINE_NO
     */
    private BigDecimal SUB_LINE_NO;

    /**
     * This field corresponds to the database column GLSTMPLT_PARAM_LINK.TEMP_CODE
     */
    private BigDecimal TEMP_CODE;

    /**
     * This field corresponds to the database column GLSTMPLT_PARAM_LINK.CODE1
     */
    private BigDecimal CODE1;

    /**
     * This field corresponds to the database column GLSTMPLT_PARAM_LINK.PERCENTAGE
     */
    private BigDecimal PERCENTAGE;

    /**
     * This field corresponds to the database column GLSTMPLT_PARAM_LINK.TYPE1
     */
    private String TYPE1;

    /**
     * This field corresponds to the database column GLSTMPLT_PARAM_LINK.RESIDENT
     */
    private String RESIDENT;

    /**
     * This field corresponds to the database column GLSTMPLT_PARAM_LINK.INCLUDE
     */
    private String INCLUDE;

    /**
     * This field corresponds to the database column GLSTMPLT_PARAM_LINK.OPERATOR
     */
    private String OPERATOR;

    /**
     * This field corresponds to the database column GLSTMPLT_PARAM_LINK.AMOUNT
     */
    private BigDecimal AMOUNT;

    /**
     * This field corresponds to the database column GLSTMPLT_PARAM_LINK.DEBIT_CREDIT_IND
     */
    private String DEBIT_CREDIT_IND;

    /**
     * This field corresponds to the database column GLSTMPLT_PARAM_LINK.COLL_PER_TYPE
     */
    private String COLL_PER_TYPE;

    /**
     * This field corresponds to the database column GLSTMPLT_PARAM_LINK.TOTAL_AMT_SIGN
     */
    private String TOTAL_AMT_SIGN;

    /**
     * This field corresponds to the database column GLSTMPLT_PARAM_LINK.TRS_ASSET_TYPE
     */
    private String TRS_ASSET_TYPE;

    /**
     * This field corresponds to the database column GLSTMPLT_PARAM_LINK.CATEGORY
     */
    private BigDecimal CATEGORY;

    /**
     * This field corresponds to the database column GLSTMPLT_PARAM_LINK.AMOUNT2
     */
    private BigDecimal AMOUNT2;

    /**
     * This field corresponds to the database column GLSTMPLT_PARAM_LINK.CODE2
     */
    private BigDecimal CODE2;

    /**
     * This field corresponds to the database column GLSTMPLT_PARAM_LINK.SOURCE_USAGES
     */
    private String SOURCE_USAGES;

    /**
     * This field corresponds to the database column GLSTMPLT_PARAM_LINK.OPERATOR1
     */
    private String OPERATOR1;

    /**
     * This field corresponds to the database column GLSTMPLT_PARAM_LINK.DEAL_TENURE
     */
    private BigDecimal DEAL_TENURE;

    /**
     * This field corresponds to the database column GLSTMPLT_PARAM_LINK.SECURITY_CODE1
     */
    private BigDecimal SECURITY_CODE1;

    /**
     * This field corresponds to the database column GLSTMPLT_PARAM_LINK.SECURITY_CODE2
     */
    private BigDecimal SECURITY_CODE2;

    /**
     * This field corresponds to the database column GLSTMPLT_PARAM_LINK.MAT_DATE
     */
    private String MAT_DATE;

    /**
     * This field corresponds to the database column GLSTMPLT_PARAM_LINK.CBK_CIF_TYPE
     */
    private String CBK_CIF_TYPE;

    /**
     * This field corresponds to the database column GLSTMPLT_PARAM_LINK.SECURITY_LISTED
     */
    private String SECURITY_LISTED;

    /**
     * This field corresponds to the database column GLSTMPLT_PARAM_LINK.DATE_TYPE
     */
    private String DATE_TYPE;

    /**
     * This field corresponds to the database column GLSTMPLT_PARAM_LINK.GL_TERM
     */
    private String GL_TERM;

    /**
     * This field corresponds to the database column GLSTMPLT_PARAM_LINK.DATE_UPDATED
     */
    private Date DATE_UPDATED;

    /**
     * This field corresponds to the database column GLSTMPLT_PARAM_LINK.GENDER
     */
    private String GENDER;

    /**
     * This field corresponds to the database column GLSTMPLT_PARAM_LINK.SECURITY_CLASS
     */
    private String SECURITY_CLASS;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GLSTMPLT_PARAM_LINK.COMP_CODE
     *
     * @return the value of GLSTMPLT_PARAM_LINK.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GLSTMPLT_PARAM_LINK.COMP_CODE
     *
     * @param COMP_CODE the value for GLSTMPLT_PARAM_LINK.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GLSTMPLT_PARAM_LINK.CRITERIA_CODE
     *
     * @return the value of GLSTMPLT_PARAM_LINK.CRITERIA_CODE
     */
    public BigDecimal getCRITERIA_CODE() {
        return CRITERIA_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GLSTMPLT_PARAM_LINK.CRITERIA_CODE
     *
     * @param CRITERIA_CODE the value for GLSTMPLT_PARAM_LINK.CRITERIA_CODE
     */
    public void setCRITERIA_CODE(BigDecimal CRITERIA_CODE) {
        this.CRITERIA_CODE = CRITERIA_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GLSTMPLT_PARAM_LINK.LINE_NO
     *
     * @return the value of GLSTMPLT_PARAM_LINK.LINE_NO
     */
    public BigDecimal getLINE_NO() {
        return LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GLSTMPLT_PARAM_LINK.LINE_NO
     *
     * @param LINE_NO the value for GLSTMPLT_PARAM_LINK.LINE_NO
     */
    public void setLINE_NO(BigDecimal LINE_NO) {
        this.LINE_NO = LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GLSTMPLT_PARAM_LINK.SUB_LINE_NO
     *
     * @return the value of GLSTMPLT_PARAM_LINK.SUB_LINE_NO
     */
    public BigDecimal getSUB_LINE_NO() {
        return SUB_LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GLSTMPLT_PARAM_LINK.SUB_LINE_NO
     *
     * @param SUB_LINE_NO the value for GLSTMPLT_PARAM_LINK.SUB_LINE_NO
     */
    public void setSUB_LINE_NO(BigDecimal SUB_LINE_NO) {
        this.SUB_LINE_NO = SUB_LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GLSTMPLT_PARAM_LINK.TEMP_CODE
     *
     * @return the value of GLSTMPLT_PARAM_LINK.TEMP_CODE
     */
    public BigDecimal getTEMP_CODE() {
        return TEMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GLSTMPLT_PARAM_LINK.TEMP_CODE
     *
     * @param TEMP_CODE the value for GLSTMPLT_PARAM_LINK.TEMP_CODE
     */
    public void setTEMP_CODE(BigDecimal TEMP_CODE) {
        this.TEMP_CODE = TEMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GLSTMPLT_PARAM_LINK.CODE1
     *
     * @return the value of GLSTMPLT_PARAM_LINK.CODE1
     */
    public BigDecimal getCODE1() {
        return CODE1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GLSTMPLT_PARAM_LINK.CODE1
     *
     * @param CODE1 the value for GLSTMPLT_PARAM_LINK.CODE1
     */
    public void setCODE1(BigDecimal CODE1) {
        this.CODE1 = CODE1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GLSTMPLT_PARAM_LINK.PERCENTAGE
     *
     * @return the value of GLSTMPLT_PARAM_LINK.PERCENTAGE
     */
    public BigDecimal getPERCENTAGE() {
        return PERCENTAGE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GLSTMPLT_PARAM_LINK.PERCENTAGE
     *
     * @param PERCENTAGE the value for GLSTMPLT_PARAM_LINK.PERCENTAGE
     */
    public void setPERCENTAGE(BigDecimal PERCENTAGE) {
        this.PERCENTAGE = PERCENTAGE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GLSTMPLT_PARAM_LINK.TYPE1
     *
     * @return the value of GLSTMPLT_PARAM_LINK.TYPE1
     */
    public String getTYPE1() {
        return TYPE1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GLSTMPLT_PARAM_LINK.TYPE1
     *
     * @param TYPE1 the value for GLSTMPLT_PARAM_LINK.TYPE1
     */
    public void setTYPE1(String TYPE1) {
        this.TYPE1 = TYPE1 == null ? null : TYPE1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GLSTMPLT_PARAM_LINK.RESIDENT
     *
     * @return the value of GLSTMPLT_PARAM_LINK.RESIDENT
     */
    public String getRESIDENT() {
        return RESIDENT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GLSTMPLT_PARAM_LINK.RESIDENT
     *
     * @param RESIDENT the value for GLSTMPLT_PARAM_LINK.RESIDENT
     */
    public void setRESIDENT(String RESIDENT) {
        this.RESIDENT = RESIDENT == null ? null : RESIDENT.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GLSTMPLT_PARAM_LINK.INCLUDE
     *
     * @return the value of GLSTMPLT_PARAM_LINK.INCLUDE
     */
    public String getINCLUDE() {
        return INCLUDE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GLSTMPLT_PARAM_LINK.INCLUDE
     *
     * @param INCLUDE the value for GLSTMPLT_PARAM_LINK.INCLUDE
     */
    public void setINCLUDE(String INCLUDE) {
        this.INCLUDE = INCLUDE == null ? null : INCLUDE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GLSTMPLT_PARAM_LINK.OPERATOR
     *
     * @return the value of GLSTMPLT_PARAM_LINK.OPERATOR
     */
    public String getOPERATOR() {
        return OPERATOR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GLSTMPLT_PARAM_LINK.OPERATOR
     *
     * @param OPERATOR the value for GLSTMPLT_PARAM_LINK.OPERATOR
     */
    public void setOPERATOR(String OPERATOR) {
        this.OPERATOR = OPERATOR == null ? null : OPERATOR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GLSTMPLT_PARAM_LINK.AMOUNT
     *
     * @return the value of GLSTMPLT_PARAM_LINK.AMOUNT
     */
    public BigDecimal getAMOUNT() {
        return AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GLSTMPLT_PARAM_LINK.AMOUNT
     *
     * @param AMOUNT the value for GLSTMPLT_PARAM_LINK.AMOUNT
     */
    public void setAMOUNT(BigDecimal AMOUNT) {
        this.AMOUNT = AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GLSTMPLT_PARAM_LINK.DEBIT_CREDIT_IND
     *
     * @return the value of GLSTMPLT_PARAM_LINK.DEBIT_CREDIT_IND
     */
    public String getDEBIT_CREDIT_IND() {
        return DEBIT_CREDIT_IND;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GLSTMPLT_PARAM_LINK.DEBIT_CREDIT_IND
     *
     * @param DEBIT_CREDIT_IND the value for GLSTMPLT_PARAM_LINK.DEBIT_CREDIT_IND
     */
    public void setDEBIT_CREDIT_IND(String DEBIT_CREDIT_IND) {
        this.DEBIT_CREDIT_IND = DEBIT_CREDIT_IND == null ? null : DEBIT_CREDIT_IND.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GLSTMPLT_PARAM_LINK.COLL_PER_TYPE
     *
     * @return the value of GLSTMPLT_PARAM_LINK.COLL_PER_TYPE
     */
    public String getCOLL_PER_TYPE() {
        return COLL_PER_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GLSTMPLT_PARAM_LINK.COLL_PER_TYPE
     *
     * @param COLL_PER_TYPE the value for GLSTMPLT_PARAM_LINK.COLL_PER_TYPE
     */
    public void setCOLL_PER_TYPE(String COLL_PER_TYPE) {
        this.COLL_PER_TYPE = COLL_PER_TYPE == null ? null : COLL_PER_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GLSTMPLT_PARAM_LINK.TOTAL_AMT_SIGN
     *
     * @return the value of GLSTMPLT_PARAM_LINK.TOTAL_AMT_SIGN
     */
    public String getTOTAL_AMT_SIGN() {
        return TOTAL_AMT_SIGN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GLSTMPLT_PARAM_LINK.TOTAL_AMT_SIGN
     *
     * @param TOTAL_AMT_SIGN the value for GLSTMPLT_PARAM_LINK.TOTAL_AMT_SIGN
     */
    public void setTOTAL_AMT_SIGN(String TOTAL_AMT_SIGN) {
        this.TOTAL_AMT_SIGN = TOTAL_AMT_SIGN == null ? null : TOTAL_AMT_SIGN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GLSTMPLT_PARAM_LINK.TRS_ASSET_TYPE
     *
     * @return the value of GLSTMPLT_PARAM_LINK.TRS_ASSET_TYPE
     */
    public String getTRS_ASSET_TYPE() {
        return TRS_ASSET_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GLSTMPLT_PARAM_LINK.TRS_ASSET_TYPE
     *
     * @param TRS_ASSET_TYPE the value for GLSTMPLT_PARAM_LINK.TRS_ASSET_TYPE
     */
    public void setTRS_ASSET_TYPE(String TRS_ASSET_TYPE) {
        this.TRS_ASSET_TYPE = TRS_ASSET_TYPE == null ? null : TRS_ASSET_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GLSTMPLT_PARAM_LINK.CATEGORY
     *
     * @return the value of GLSTMPLT_PARAM_LINK.CATEGORY
     */
    public BigDecimal getCATEGORY() {
        return CATEGORY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GLSTMPLT_PARAM_LINK.CATEGORY
     *
     * @param CATEGORY the value for GLSTMPLT_PARAM_LINK.CATEGORY
     */
    public void setCATEGORY(BigDecimal CATEGORY) {
        this.CATEGORY = CATEGORY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GLSTMPLT_PARAM_LINK.AMOUNT2
     *
     * @return the value of GLSTMPLT_PARAM_LINK.AMOUNT2
     */
    public BigDecimal getAMOUNT2() {
        return AMOUNT2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GLSTMPLT_PARAM_LINK.AMOUNT2
     *
     * @param AMOUNT2 the value for GLSTMPLT_PARAM_LINK.AMOUNT2
     */
    public void setAMOUNT2(BigDecimal AMOUNT2) {
        this.AMOUNT2 = AMOUNT2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GLSTMPLT_PARAM_LINK.CODE2
     *
     * @return the value of GLSTMPLT_PARAM_LINK.CODE2
     */
    public BigDecimal getCODE2() {
        return CODE2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GLSTMPLT_PARAM_LINK.CODE2
     *
     * @param CODE2 the value for GLSTMPLT_PARAM_LINK.CODE2
     */
    public void setCODE2(BigDecimal CODE2) {
        this.CODE2 = CODE2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GLSTMPLT_PARAM_LINK.SOURCE_USAGES
     *
     * @return the value of GLSTMPLT_PARAM_LINK.SOURCE_USAGES
     */
    public String getSOURCE_USAGES() {
        return SOURCE_USAGES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GLSTMPLT_PARAM_LINK.SOURCE_USAGES
     *
     * @param SOURCE_USAGES the value for GLSTMPLT_PARAM_LINK.SOURCE_USAGES
     */
    public void setSOURCE_USAGES(String SOURCE_USAGES) {
        this.SOURCE_USAGES = SOURCE_USAGES == null ? null : SOURCE_USAGES.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GLSTMPLT_PARAM_LINK.OPERATOR1
     *
     * @return the value of GLSTMPLT_PARAM_LINK.OPERATOR1
     */
    public String getOPERATOR1() {
        return OPERATOR1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GLSTMPLT_PARAM_LINK.OPERATOR1
     *
     * @param OPERATOR1 the value for GLSTMPLT_PARAM_LINK.OPERATOR1
     */
    public void setOPERATOR1(String OPERATOR1) {
        this.OPERATOR1 = OPERATOR1 == null ? null : OPERATOR1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GLSTMPLT_PARAM_LINK.DEAL_TENURE
     *
     * @return the value of GLSTMPLT_PARAM_LINK.DEAL_TENURE
     */
    public BigDecimal getDEAL_TENURE() {
        return DEAL_TENURE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GLSTMPLT_PARAM_LINK.DEAL_TENURE
     *
     * @param DEAL_TENURE the value for GLSTMPLT_PARAM_LINK.DEAL_TENURE
     */
    public void setDEAL_TENURE(BigDecimal DEAL_TENURE) {
        this.DEAL_TENURE = DEAL_TENURE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GLSTMPLT_PARAM_LINK.SECURITY_CODE1
     *
     * @return the value of GLSTMPLT_PARAM_LINK.SECURITY_CODE1
     */
    public BigDecimal getSECURITY_CODE1() {
        return SECURITY_CODE1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GLSTMPLT_PARAM_LINK.SECURITY_CODE1
     *
     * @param SECURITY_CODE1 the value for GLSTMPLT_PARAM_LINK.SECURITY_CODE1
     */
    public void setSECURITY_CODE1(BigDecimal SECURITY_CODE1) {
        this.SECURITY_CODE1 = SECURITY_CODE1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GLSTMPLT_PARAM_LINK.SECURITY_CODE2
     *
     * @return the value of GLSTMPLT_PARAM_LINK.SECURITY_CODE2
     */
    public BigDecimal getSECURITY_CODE2() {
        return SECURITY_CODE2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GLSTMPLT_PARAM_LINK.SECURITY_CODE2
     *
     * @param SECURITY_CODE2 the value for GLSTMPLT_PARAM_LINK.SECURITY_CODE2
     */
    public void setSECURITY_CODE2(BigDecimal SECURITY_CODE2) {
        this.SECURITY_CODE2 = SECURITY_CODE2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GLSTMPLT_PARAM_LINK.MAT_DATE
     *
     * @return the value of GLSTMPLT_PARAM_LINK.MAT_DATE
     */
    public String getMAT_DATE() {
        return MAT_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GLSTMPLT_PARAM_LINK.MAT_DATE
     *
     * @param MAT_DATE the value for GLSTMPLT_PARAM_LINK.MAT_DATE
     */
    public void setMAT_DATE(String MAT_DATE) {
        this.MAT_DATE = MAT_DATE == null ? null : MAT_DATE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GLSTMPLT_PARAM_LINK.CBK_CIF_TYPE
     *
     * @return the value of GLSTMPLT_PARAM_LINK.CBK_CIF_TYPE
     */
    public String getCBK_CIF_TYPE() {
        return CBK_CIF_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GLSTMPLT_PARAM_LINK.CBK_CIF_TYPE
     *
     * @param CBK_CIF_TYPE the value for GLSTMPLT_PARAM_LINK.CBK_CIF_TYPE
     */
    public void setCBK_CIF_TYPE(String CBK_CIF_TYPE) {
        this.CBK_CIF_TYPE = CBK_CIF_TYPE == null ? null : CBK_CIF_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GLSTMPLT_PARAM_LINK.SECURITY_LISTED
     *
     * @return the value of GLSTMPLT_PARAM_LINK.SECURITY_LISTED
     */
    public String getSECURITY_LISTED() {
        return SECURITY_LISTED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GLSTMPLT_PARAM_LINK.SECURITY_LISTED
     *
     * @param SECURITY_LISTED the value for GLSTMPLT_PARAM_LINK.SECURITY_LISTED
     */
    public void setSECURITY_LISTED(String SECURITY_LISTED) {
        this.SECURITY_LISTED = SECURITY_LISTED == null ? null : SECURITY_LISTED.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GLSTMPLT_PARAM_LINK.DATE_TYPE
     *
     * @return the value of GLSTMPLT_PARAM_LINK.DATE_TYPE
     */
    public String getDATE_TYPE() {
        return DATE_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GLSTMPLT_PARAM_LINK.DATE_TYPE
     *
     * @param DATE_TYPE the value for GLSTMPLT_PARAM_LINK.DATE_TYPE
     */
    public void setDATE_TYPE(String DATE_TYPE) {
        this.DATE_TYPE = DATE_TYPE == null ? null : DATE_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GLSTMPLT_PARAM_LINK.GL_TERM
     *
     * @return the value of GLSTMPLT_PARAM_LINK.GL_TERM
     */
    public String getGL_TERM() {
        return GL_TERM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GLSTMPLT_PARAM_LINK.GL_TERM
     *
     * @param GL_TERM the value for GLSTMPLT_PARAM_LINK.GL_TERM
     */
    public void setGL_TERM(String GL_TERM) {
        this.GL_TERM = GL_TERM == null ? null : GL_TERM.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GLSTMPLT_PARAM_LINK.DATE_UPDATED
     *
     * @return the value of GLSTMPLT_PARAM_LINK.DATE_UPDATED
     */
    public Date getDATE_UPDATED() {
        return DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GLSTMPLT_PARAM_LINK.DATE_UPDATED
     *
     * @param DATE_UPDATED the value for GLSTMPLT_PARAM_LINK.DATE_UPDATED
     */
    public void setDATE_UPDATED(Date DATE_UPDATED) {
        this.DATE_UPDATED = DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GLSTMPLT_PARAM_LINK.GENDER
     *
     * @return the value of GLSTMPLT_PARAM_LINK.GENDER
     */
    public String getGENDER() {
        return GENDER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GLSTMPLT_PARAM_LINK.GENDER
     *
     * @param GENDER the value for GLSTMPLT_PARAM_LINK.GENDER
     */
    public void setGENDER(String GENDER) {
        this.GENDER = GENDER == null ? null : GENDER.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GLSTMPLT_PARAM_LINK.SECURITY_CLASS
     *
     * @return the value of GLSTMPLT_PARAM_LINK.SECURITY_CLASS
     */
    public String getSECURITY_CLASS() {
        return SECURITY_CLASS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GLSTMPLT_PARAM_LINK.SECURITY_CLASS
     *
     * @param SECURITY_CLASS the value for GLSTMPLT_PARAM_LINK.SECURITY_CLASS
     */
    public void setSECURITY_CLASS(String SECURITY_CLASS) {
        this.SECURITY_CLASS = SECURITY_CLASS == null ? null : SECURITY_CLASS.trim();
    }
}