package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class IRP_SCHED_DETAILSVOKey extends BaseVO {
    /**
     * This field corresponds to the database column IRP_SCHED_DETAILS.FREQUENCY_OCCURENCE
     */
    private BigDecimal FREQUENCY_OCCURENCE;

    /**
     * This field corresponds to the database column IRP_SCHED_DETAILS.SCHED_ID
     */
    private BigDecimal SCHED_ID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_SCHED_DETAILS.FREQUENCY_OCCURENCE
     *
     * @return the value of IRP_SCHED_DETAILS.FREQUENCY_OCCURENCE
     */
    public BigDecimal getFREQUENCY_OCCURENCE() {
        return FREQUENCY_OCCURENCE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_SCHED_DETAILS.FREQUENCY_OCCURENCE
     *
     * @param FREQUENCY_OCCURENCE the value for IRP_SCHED_DETAILS.FREQUENCY_OCCURENCE
     */
    public void setFREQUENCY_OCCURENCE(BigDecimal FREQUENCY_OCCURENCE) {
        this.FREQUENCY_OCCURENCE = FREQUENCY_OCCURENCE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_SCHED_DETAILS.SCHED_ID
     *
     * @return the value of IRP_SCHED_DETAILS.SCHED_ID
     */
    public BigDecimal getSCHED_ID() {
        return SCHED_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_SCHED_DETAILS.SCHED_ID
     *
     * @param SCHED_ID the value for IRP_SCHED_DETAILS.SCHED_ID
     */
    public void setSCHED_ID(BigDecimal SCHED_ID) {
        this.SCHED_ID = SCHED_ID;
    }
}