package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class IRP_TEMPLATE_COLUMNSVO extends IRP_TEMPLATE_COLUMNSVOKey {
    /**
     * This field corresponds to the database column IRP_TEMPLATE_COLUMNS.BRIEF_NAME1
     */
    private String BRIEF_NAME1;

    /**
     * This field corresponds to the database column IRP_TEMPLATE_COLUMNS.BRIEF_NAME2
     */
    private String BRIEF_NAME2;

    /**
     * This field corresponds to the database column IRP_TEMPLATE_COLUMNS.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column IRP_TEMPLATE_COLUMNS.DATE_CREATED
     */
    private Date DATE_CREATED;

    /**
     * This field corresponds to the database column IRP_TEMPLATE_COLUMNS.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column IRP_TEMPLATE_COLUMNS.DATE_MODIFIED
     */
    private Date DATE_MODIFIED;

    /**
     * This field corresponds to the database column IRP_TEMPLATE_COLUMNS.PRINT_PAPER_SIZE
     */
    private BigDecimal PRINT_PAPER_SIZE;

    /**
     * This field corresponds to the database column IRP_TEMPLATE_COLUMNS.PRINT_PAPER_ORIENTATION
     */
    private BigDecimal PRINT_PAPER_ORIENTATION;

    /**
     * This field corresponds to the database column IRP_TEMPLATE_COLUMNS.DATE_UPDATED
     */
    private Date DATE_UPDATED;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_TEMPLATE_COLUMNS.BRIEF_NAME1
     *
     * @return the value of IRP_TEMPLATE_COLUMNS.BRIEF_NAME1
     */
    public String getBRIEF_NAME1() {
        return BRIEF_NAME1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_TEMPLATE_COLUMNS.BRIEF_NAME1
     *
     * @param BRIEF_NAME1 the value for IRP_TEMPLATE_COLUMNS.BRIEF_NAME1
     */
    public void setBRIEF_NAME1(String BRIEF_NAME1) {
        this.BRIEF_NAME1 = BRIEF_NAME1 == null ? null : BRIEF_NAME1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_TEMPLATE_COLUMNS.BRIEF_NAME2
     *
     * @return the value of IRP_TEMPLATE_COLUMNS.BRIEF_NAME2
     */
    public String getBRIEF_NAME2() {
        return BRIEF_NAME2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_TEMPLATE_COLUMNS.BRIEF_NAME2
     *
     * @param BRIEF_NAME2 the value for IRP_TEMPLATE_COLUMNS.BRIEF_NAME2
     */
    public void setBRIEF_NAME2(String BRIEF_NAME2) {
        this.BRIEF_NAME2 = BRIEF_NAME2 == null ? null : BRIEF_NAME2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_TEMPLATE_COLUMNS.CREATED_BY
     *
     * @return the value of IRP_TEMPLATE_COLUMNS.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_TEMPLATE_COLUMNS.CREATED_BY
     *
     * @param CREATED_BY the value for IRP_TEMPLATE_COLUMNS.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_TEMPLATE_COLUMNS.DATE_CREATED
     *
     * @return the value of IRP_TEMPLATE_COLUMNS.DATE_CREATED
     */
    public Date getDATE_CREATED() {
        return DATE_CREATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_TEMPLATE_COLUMNS.DATE_CREATED
     *
     * @param DATE_CREATED the value for IRP_TEMPLATE_COLUMNS.DATE_CREATED
     */
    public void setDATE_CREATED(Date DATE_CREATED) {
        this.DATE_CREATED = DATE_CREATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_TEMPLATE_COLUMNS.MODIFIED_BY
     *
     * @return the value of IRP_TEMPLATE_COLUMNS.MODIFIED_BY
     */
    public String getMODIFIED_BY() {
        return MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_TEMPLATE_COLUMNS.MODIFIED_BY
     *
     * @param MODIFIED_BY the value for IRP_TEMPLATE_COLUMNS.MODIFIED_BY
     */
    public void setMODIFIED_BY(String MODIFIED_BY) {
        this.MODIFIED_BY = MODIFIED_BY == null ? null : MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_TEMPLATE_COLUMNS.DATE_MODIFIED
     *
     * @return the value of IRP_TEMPLATE_COLUMNS.DATE_MODIFIED
     */
    public Date getDATE_MODIFIED() {
        return DATE_MODIFIED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_TEMPLATE_COLUMNS.DATE_MODIFIED
     *
     * @param DATE_MODIFIED the value for IRP_TEMPLATE_COLUMNS.DATE_MODIFIED
     */
    public void setDATE_MODIFIED(Date DATE_MODIFIED) {
        this.DATE_MODIFIED = DATE_MODIFIED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_TEMPLATE_COLUMNS.PRINT_PAPER_SIZE
     *
     * @return the value of IRP_TEMPLATE_COLUMNS.PRINT_PAPER_SIZE
     */
    public BigDecimal getPRINT_PAPER_SIZE() {
        return PRINT_PAPER_SIZE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_TEMPLATE_COLUMNS.PRINT_PAPER_SIZE
     *
     * @param PRINT_PAPER_SIZE the value for IRP_TEMPLATE_COLUMNS.PRINT_PAPER_SIZE
     */
    public void setPRINT_PAPER_SIZE(BigDecimal PRINT_PAPER_SIZE) {
        this.PRINT_PAPER_SIZE = PRINT_PAPER_SIZE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_TEMPLATE_COLUMNS.PRINT_PAPER_ORIENTATION
     *
     * @return the value of IRP_TEMPLATE_COLUMNS.PRINT_PAPER_ORIENTATION
     */
    public BigDecimal getPRINT_PAPER_ORIENTATION() {
        return PRINT_PAPER_ORIENTATION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_TEMPLATE_COLUMNS.PRINT_PAPER_ORIENTATION
     *
     * @param PRINT_PAPER_ORIENTATION the value for IRP_TEMPLATE_COLUMNS.PRINT_PAPER_ORIENTATION
     */
    public void setPRINT_PAPER_ORIENTATION(BigDecimal PRINT_PAPER_ORIENTATION) {
        this.PRINT_PAPER_ORIENTATION = PRINT_PAPER_ORIENTATION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_TEMPLATE_COLUMNS.DATE_UPDATED
     *
     * @return the value of IRP_TEMPLATE_COLUMNS.DATE_UPDATED
     */
    public Date getDATE_UPDATED() {
        return DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_TEMPLATE_COLUMNS.DATE_UPDATED
     *
     * @param DATE_UPDATED the value for IRP_TEMPLATE_COLUMNS.DATE_UPDATED
     */
    public void setDATE_UPDATED(Date DATE_UPDATED) {
        this.DATE_UPDATED = DATE_UPDATED;
    }
}