package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class IRP_TEMPLATE_COLUMNS_DETVO extends IRP_TEMPLATE_COLUMNS_DETVOKey {
	private String TEMPLATE_COL_DESC1;
	private String TEMPLATE_COL_DESC2;
    /**
     * This field corresponds to the database column IRP_TEMPLATE_COLUMNS_DET.COL_TYPE
     */
    private String COL_TYPE;

    /**
     * This field corresponds to the database column IRP_TEMPLATE_COLUMNS_DET.FROM_DATE
     */
    private Date FROM_DATE;

    /**
     * This field corresponds to the database column IRP_TEMPLATE_COLUMNS_DET.TO_DATE
     */
    private Date TO_DATE;

    /**
     * This field corresponds to the database column IRP_TEMPLATE_COLUMNS_DET.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column IRP_TEMPLATE_COLUMNS_DET.DATE_CREATED
     */
    private Date DATE_CREATED;

    /**
     * This field corresponds to the database column IRP_TEMPLATE_COLUMNS_DET.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column IRP_TEMPLATE_COLUMNS_DET.DATE_MODIFIED
     */
    private Date DATE_MODIFIED;

    /**
     * This field corresponds to the database column IRP_TEMPLATE_COLUMNS_DET.COL_COMP_CODE
     */
    private BigDecimal COL_COMP_CODE;

    /**
     * This field corresponds to the database column IRP_TEMPLATE_COLUMNS_DET.FROM_BRANCH
     */
    private BigDecimal FROM_BRANCH;

    /**
     * This field corresponds to the database column IRP_TEMPLATE_COLUMNS_DET.TO_BRANCH
     */
    private BigDecimal TO_BRANCH;

    /**
     * This field corresponds to the database column IRP_TEMPLATE_COLUMNS_DET.FROM_CY
     */
    private BigDecimal FROM_CY;

    /**
     * This field corresponds to the database column IRP_TEMPLATE_COLUMNS_DET.TO_CY
     */
    private BigDecimal TO_CY;

    /**
     * This field corresponds to the database column IRP_TEMPLATE_COLUMNS_DET.FROM_DIV
     */
    private BigDecimal FROM_DIV;

    /**
     * This field corresponds to the database column IRP_TEMPLATE_COLUMNS_DET.TO_DIV
     */
    private BigDecimal TO_DIV;

    /**
     * This field corresponds to the database column IRP_TEMPLATE_COLUMNS_DET.FROM_DEPT
     */
    private BigDecimal FROM_DEPT;

    /**
     * This field corresponds to the database column IRP_TEMPLATE_COLUMNS_DET.TO_DEPT
     */
    private BigDecimal TO_DEPT;

    /**
     * This field corresponds to the database column IRP_TEMPLATE_COLUMNS_DET.FROM_UNIT
     */
    private BigDecimal FROM_UNIT;

    /**
     * This field corresponds to the database column IRP_TEMPLATE_COLUMNS_DET.TO_UNIT
     */
    private BigDecimal TO_UNIT;

    /**
     * This field corresponds to the database column IRP_TEMPLATE_COLUMNS_DET.IS_BOLD
     */
    private String IS_BOLD;

    /**
     * This field corresponds to the database column IRP_TEMPLATE_COLUMNS_DET.DISP_COL_TOT_ZERO
     */
    private String DISP_COL_TOT_ZERO;

    /**
     * This field corresponds to the database column IRP_TEMPLATE_COLUMNS_DET.EXPRESSION_LINES
     */
    private String EXPRESSION_LINES;

    /**
     * This field corresponds to the database column IRP_TEMPLATE_COLUMNS_DET.EXPRESSION
     */
    private String EXPRESSION;

    /**
     * This field corresponds to the database column IRP_TEMPLATE_COLUMNS_DET.ALL_CRITERIA
     */
    private String ALL_CRITERIA;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_TEMPLATE_COLUMNS_DET.COL_TYPE
     *
     * @return the value of IRP_TEMPLATE_COLUMNS_DET.COL_TYPE
     */
    public String getCOL_TYPE() {
        return COL_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_TEMPLATE_COLUMNS_DET.COL_TYPE
     *
     * @param COL_TYPE the value for IRP_TEMPLATE_COLUMNS_DET.COL_TYPE
     */
    public void setCOL_TYPE(String COL_TYPE) {
        this.COL_TYPE = COL_TYPE == null ? null : COL_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_TEMPLATE_COLUMNS_DET.FROM_DATE
     *
     * @return the value of IRP_TEMPLATE_COLUMNS_DET.FROM_DATE
     */
    public Date getFROM_DATE() {
        return FROM_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_TEMPLATE_COLUMNS_DET.FROM_DATE
     *
     * @param FROM_DATE the value for IRP_TEMPLATE_COLUMNS_DET.FROM_DATE
     */
    public void setFROM_DATE(Date FROM_DATE) {
        this.FROM_DATE = FROM_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_TEMPLATE_COLUMNS_DET.TO_DATE
     *
     * @return the value of IRP_TEMPLATE_COLUMNS_DET.TO_DATE
     */
    public Date getTO_DATE() {
        return TO_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_TEMPLATE_COLUMNS_DET.TO_DATE
     *
     * @param TO_DATE the value for IRP_TEMPLATE_COLUMNS_DET.TO_DATE
     */
    public void setTO_DATE(Date TO_DATE) {
        this.TO_DATE = TO_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_TEMPLATE_COLUMNS_DET.CREATED_BY
     *
     * @return the value of IRP_TEMPLATE_COLUMNS_DET.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_TEMPLATE_COLUMNS_DET.CREATED_BY
     *
     * @param CREATED_BY the value for IRP_TEMPLATE_COLUMNS_DET.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_TEMPLATE_COLUMNS_DET.DATE_CREATED
     *
     * @return the value of IRP_TEMPLATE_COLUMNS_DET.DATE_CREATED
     */
    public Date getDATE_CREATED() {
        return DATE_CREATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_TEMPLATE_COLUMNS_DET.DATE_CREATED
     *
     * @param DATE_CREATED the value for IRP_TEMPLATE_COLUMNS_DET.DATE_CREATED
     */
    public void setDATE_CREATED(Date DATE_CREATED) {
        this.DATE_CREATED = DATE_CREATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_TEMPLATE_COLUMNS_DET.MODIFIED_BY
     *
     * @return the value of IRP_TEMPLATE_COLUMNS_DET.MODIFIED_BY
     */
    public String getMODIFIED_BY() {
        return MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_TEMPLATE_COLUMNS_DET.MODIFIED_BY
     *
     * @param MODIFIED_BY the value for IRP_TEMPLATE_COLUMNS_DET.MODIFIED_BY
     */
    public void setMODIFIED_BY(String MODIFIED_BY) {
        this.MODIFIED_BY = MODIFIED_BY == null ? null : MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_TEMPLATE_COLUMNS_DET.DATE_MODIFIED
     *
     * @return the value of IRP_TEMPLATE_COLUMNS_DET.DATE_MODIFIED
     */
    public Date getDATE_MODIFIED() {
        return DATE_MODIFIED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_TEMPLATE_COLUMNS_DET.DATE_MODIFIED
     *
     * @param DATE_MODIFIED the value for IRP_TEMPLATE_COLUMNS_DET.DATE_MODIFIED
     */
    public void setDATE_MODIFIED(Date DATE_MODIFIED) {
        this.DATE_MODIFIED = DATE_MODIFIED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_TEMPLATE_COLUMNS_DET.COL_COMP_CODE
     *
     * @return the value of IRP_TEMPLATE_COLUMNS_DET.COL_COMP_CODE
     */
    public BigDecimal getCOL_COMP_CODE() {
        return COL_COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_TEMPLATE_COLUMNS_DET.COL_COMP_CODE
     *
     * @param COL_COMP_CODE the value for IRP_TEMPLATE_COLUMNS_DET.COL_COMP_CODE
     */
    public void setCOL_COMP_CODE(BigDecimal COL_COMP_CODE) {
        this.COL_COMP_CODE = COL_COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_TEMPLATE_COLUMNS_DET.FROM_BRANCH
     *
     * @return the value of IRP_TEMPLATE_COLUMNS_DET.FROM_BRANCH
     */
    public BigDecimal getFROM_BRANCH() {
        return FROM_BRANCH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_TEMPLATE_COLUMNS_DET.FROM_BRANCH
     *
     * @param FROM_BRANCH the value for IRP_TEMPLATE_COLUMNS_DET.FROM_BRANCH
     */
    public void setFROM_BRANCH(BigDecimal FROM_BRANCH) {
        this.FROM_BRANCH = FROM_BRANCH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_TEMPLATE_COLUMNS_DET.TO_BRANCH
     *
     * @return the value of IRP_TEMPLATE_COLUMNS_DET.TO_BRANCH
     */
    public BigDecimal getTO_BRANCH() {
        return TO_BRANCH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_TEMPLATE_COLUMNS_DET.TO_BRANCH
     *
     * @param TO_BRANCH the value for IRP_TEMPLATE_COLUMNS_DET.TO_BRANCH
     */
    public void setTO_BRANCH(BigDecimal TO_BRANCH) {
        this.TO_BRANCH = TO_BRANCH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_TEMPLATE_COLUMNS_DET.FROM_CY
     *
     * @return the value of IRP_TEMPLATE_COLUMNS_DET.FROM_CY
     */
    public BigDecimal getFROM_CY() {
        return FROM_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_TEMPLATE_COLUMNS_DET.FROM_CY
     *
     * @param FROM_CY the value for IRP_TEMPLATE_COLUMNS_DET.FROM_CY
     */
    public void setFROM_CY(BigDecimal FROM_CY) {
        this.FROM_CY = FROM_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_TEMPLATE_COLUMNS_DET.TO_CY
     *
     * @return the value of IRP_TEMPLATE_COLUMNS_DET.TO_CY
     */
    public BigDecimal getTO_CY() {
        return TO_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_TEMPLATE_COLUMNS_DET.TO_CY
     *
     * @param TO_CY the value for IRP_TEMPLATE_COLUMNS_DET.TO_CY
     */
    public void setTO_CY(BigDecimal TO_CY) {
        this.TO_CY = TO_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_TEMPLATE_COLUMNS_DET.FROM_DIV
     *
     * @return the value of IRP_TEMPLATE_COLUMNS_DET.FROM_DIV
     */
    public BigDecimal getFROM_DIV() {
        return FROM_DIV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_TEMPLATE_COLUMNS_DET.FROM_DIV
     *
     * @param FROM_DIV the value for IRP_TEMPLATE_COLUMNS_DET.FROM_DIV
     */
    public void setFROM_DIV(BigDecimal FROM_DIV) {
        this.FROM_DIV = FROM_DIV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_TEMPLATE_COLUMNS_DET.TO_DIV
     *
     * @return the value of IRP_TEMPLATE_COLUMNS_DET.TO_DIV
     */
    public BigDecimal getTO_DIV() {
        return TO_DIV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_TEMPLATE_COLUMNS_DET.TO_DIV
     *
     * @param TO_DIV the value for IRP_TEMPLATE_COLUMNS_DET.TO_DIV
     */
    public void setTO_DIV(BigDecimal TO_DIV) {
        this.TO_DIV = TO_DIV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_TEMPLATE_COLUMNS_DET.FROM_DEPT
     *
     * @return the value of IRP_TEMPLATE_COLUMNS_DET.FROM_DEPT
     */
    public BigDecimal getFROM_DEPT() {
        return FROM_DEPT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_TEMPLATE_COLUMNS_DET.FROM_DEPT
     *
     * @param FROM_DEPT the value for IRP_TEMPLATE_COLUMNS_DET.FROM_DEPT
     */
    public void setFROM_DEPT(BigDecimal FROM_DEPT) {
        this.FROM_DEPT = FROM_DEPT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_TEMPLATE_COLUMNS_DET.TO_DEPT
     *
     * @return the value of IRP_TEMPLATE_COLUMNS_DET.TO_DEPT
     */
    public BigDecimal getTO_DEPT() {
        return TO_DEPT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_TEMPLATE_COLUMNS_DET.TO_DEPT
     *
     * @param TO_DEPT the value for IRP_TEMPLATE_COLUMNS_DET.TO_DEPT
     */
    public void setTO_DEPT(BigDecimal TO_DEPT) {
        this.TO_DEPT = TO_DEPT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_TEMPLATE_COLUMNS_DET.FROM_UNIT
     *
     * @return the value of IRP_TEMPLATE_COLUMNS_DET.FROM_UNIT
     */
    public BigDecimal getFROM_UNIT() {
        return FROM_UNIT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_TEMPLATE_COLUMNS_DET.FROM_UNIT
     *
     * @param FROM_UNIT the value for IRP_TEMPLATE_COLUMNS_DET.FROM_UNIT
     */
    public void setFROM_UNIT(BigDecimal FROM_UNIT) {
        this.FROM_UNIT = FROM_UNIT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_TEMPLATE_COLUMNS_DET.TO_UNIT
     *
     * @return the value of IRP_TEMPLATE_COLUMNS_DET.TO_UNIT
     */
    public BigDecimal getTO_UNIT() {
        return TO_UNIT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_TEMPLATE_COLUMNS_DET.TO_UNIT
     *
     * @param TO_UNIT the value for IRP_TEMPLATE_COLUMNS_DET.TO_UNIT
     */
    public void setTO_UNIT(BigDecimal TO_UNIT) {
        this.TO_UNIT = TO_UNIT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_TEMPLATE_COLUMNS_DET.IS_BOLD
     *
     * @return the value of IRP_TEMPLATE_COLUMNS_DET.IS_BOLD
     */
    public String getIS_BOLD() {
        return IS_BOLD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_TEMPLATE_COLUMNS_DET.IS_BOLD
     *
     * @param IS_BOLD the value for IRP_TEMPLATE_COLUMNS_DET.IS_BOLD
     */
    public void setIS_BOLD(String IS_BOLD) {
        this.IS_BOLD = IS_BOLD == null ? null : IS_BOLD.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_TEMPLATE_COLUMNS_DET.DISP_COL_TOT_ZERO
     *
     * @return the value of IRP_TEMPLATE_COLUMNS_DET.DISP_COL_TOT_ZERO
     */
    public String getDISP_COL_TOT_ZERO() {
        return DISP_COL_TOT_ZERO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_TEMPLATE_COLUMNS_DET.DISP_COL_TOT_ZERO
     *
     * @param DISP_COL_TOT_ZERO the value for IRP_TEMPLATE_COLUMNS_DET.DISP_COL_TOT_ZERO
     */
    public void setDISP_COL_TOT_ZERO(String DISP_COL_TOT_ZERO) {
        this.DISP_COL_TOT_ZERO = DISP_COL_TOT_ZERO == null ? null : DISP_COL_TOT_ZERO.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_TEMPLATE_COLUMNS_DET.EXPRESSION_LINES
     *
     * @return the value of IRP_TEMPLATE_COLUMNS_DET.EXPRESSION_LINES
     */
    public String getEXPRESSION_LINES() {
        return EXPRESSION_LINES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_TEMPLATE_COLUMNS_DET.EXPRESSION_LINES
     *
     * @param EXPRESSION_LINES the value for IRP_TEMPLATE_COLUMNS_DET.EXPRESSION_LINES
     */
    public void setEXPRESSION_LINES(String EXPRESSION_LINES) {
        this.EXPRESSION_LINES = EXPRESSION_LINES == null ? null : EXPRESSION_LINES.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_TEMPLATE_COLUMNS_DET.EXPRESSION
     *
     * @return the value of IRP_TEMPLATE_COLUMNS_DET.EXPRESSION
     */
    public String getEXPRESSION() {
        return EXPRESSION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_TEMPLATE_COLUMNS_DET.EXPRESSION
     *
     * @param EXPRESSION the value for IRP_TEMPLATE_COLUMNS_DET.EXPRESSION
     */
    public void setEXPRESSION(String EXPRESSION) {
        this.EXPRESSION = EXPRESSION == null ? null : EXPRESSION.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_TEMPLATE_COLUMNS_DET.ALL_CRITERIA
     *
     * @return the value of IRP_TEMPLATE_COLUMNS_DET.ALL_CRITERIA
     */
    public String getALL_CRITERIA() {
        return ALL_CRITERIA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_TEMPLATE_COLUMNS_DET.ALL_CRITERIA
     *
     * @param ALL_CRITERIA the value for IRP_TEMPLATE_COLUMNS_DET.ALL_CRITERIA
     */
    public void setALL_CRITERIA(String ALL_CRITERIA) {
        this.ALL_CRITERIA = ALL_CRITERIA == null ? null : ALL_CRITERIA.trim();
    }
    
    public String getTEMPLATE_COL_DESC1() {
		return TEMPLATE_COL_DESC1;
	}
	public void setTEMPLATE_COL_DESC1(String tEMPLATECOLDESC1) {
		TEMPLATE_COL_DESC1 = tEMPLATECOLDESC1;
	}
	public String getTEMPLATE_COL_DESC2() {
		return TEMPLATE_COL_DESC2;
	}
	public void setTEMPLATE_COL_DESC2(String tEMPLATECOLDESC2) {
		TEMPLATE_COL_DESC2 = tEMPLATECOLDESC2;
	} 
}