package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class IRP_SNAPSHOT_SUB_REPORTVO extends BaseVO {
    /**
     * This field corresponds to the database column IRP_SNAPSHOT_SUB_REPORT.REP_SNAPSHOT_ID
     */
    private BigDecimal REP_SNAPSHOT_ID;

    /**
     * This field corresponds to the database column IRP_SNAPSHOT_SUB_REPORT.SUB_REPORT_EXPRESSION
     */
    private String SUB_REPORT_EXPRESSION;

    /**
     * This field corresponds to the database column IRP_SNAPSHOT_SUB_REPORT.JRXML_FILE
     */
    private byte[] JRXML_FILE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_SNAPSHOT_SUB_REPORT.REP_SNAPSHOT_ID
     *
     * @return the value of IRP_SNAPSHOT_SUB_REPORT.REP_SNAPSHOT_ID
     */
    public BigDecimal getREP_SNAPSHOT_ID() {
        return REP_SNAPSHOT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_SNAPSHOT_SUB_REPORT.REP_SNAPSHOT_ID
     *
     * @param REP_SNAPSHOT_ID the value for IRP_SNAPSHOT_SUB_REPORT.REP_SNAPSHOT_ID
     */
    public void setREP_SNAPSHOT_ID(BigDecimal REP_SNAPSHOT_ID) {
        this.REP_SNAPSHOT_ID = REP_SNAPSHOT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_SNAPSHOT_SUB_REPORT.SUB_REPORT_EXPRESSION
     *
     * @return the value of IRP_SNAPSHOT_SUB_REPORT.SUB_REPORT_EXPRESSION
     */
    public String getSUB_REPORT_EXPRESSION() {
        return SUB_REPORT_EXPRESSION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_SNAPSHOT_SUB_REPORT.SUB_REPORT_EXPRESSION
     *
     * @param SUB_REPORT_EXPRESSION the value for IRP_SNAPSHOT_SUB_REPORT.SUB_REPORT_EXPRESSION
     */
    public void setSUB_REPORT_EXPRESSION(String SUB_REPORT_EXPRESSION) {
        this.SUB_REPORT_EXPRESSION = SUB_REPORT_EXPRESSION == null ? null : SUB_REPORT_EXPRESSION.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_SNAPSHOT_SUB_REPORT.JRXML_FILE
     *
     * @return the value of IRP_SNAPSHOT_SUB_REPORT.JRXML_FILE
     */
    public byte[] getJRXML_FILE() {
        return JRXML_FILE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_SNAPSHOT_SUB_REPORT.JRXML_FILE
     *
     * @param JRXML_FILE the value for IRP_SNAPSHOT_SUB_REPORT.JRXML_FILE
     */
    public void setJRXML_FILE(byte[] JRXML_FILE) {
        this.JRXML_FILE = JRXML_FILE;
    }
}