package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;
import java.util.Date;

public class IRP_REPORT_SCHED_LOG_DETAILSVO extends BaseVO {
    /**
     * This field corresponds to the database column IRP_REPORT_SCHED_LOG_DETAILS.LINE_NBR
     */
    private BigDecimal LINE_NBR;

    /**
     * This field corresponds to the database column IRP_REPORT_SCHED_LOG_DETAILS.REPORT_ID
     */
    private BigDecimal REPORT_ID;

    /**
     * This field corresponds to the database column IRP_REPORT_SCHED_LOG_DETAILS.SCHEDULED_DATE
     */
    private Date SCHEDULED_DATE;

    /**
     * This field corresponds to the database column IRP_REPORT_SCHED_LOG_DETAILS.SCHED_ID
     */
    private BigDecimal SCHED_ID;

    /**
     * This field corresponds to the database column IRP_REPORT_SCHED_LOG_DETAILS.START_DATE
     */
    private Date START_DATE;

    /**
     * This field corresponds to the database column IRP_REPORT_SCHED_LOG_DETAILS.FROM_EMAIL_VAL
     */
    private String FROM_EMAIL_VAL;

    /**
     * This field corresponds to the database column IRP_REPORT_SCHED_LOG_DETAILS.RECEIVER_TYPE
     */
    private BigDecimal RECEIVER_TYPE;

    /**
     * This field corresponds to the database column IRP_REPORT_SCHED_LOG_DETAILS.RECEIVER_EMAIL_VAL
     */
    private String RECEIVER_EMAIL_VAL;

    /**
     * This field corresponds to the database column IRP_REPORT_SCHED_LOG_DETAILS.STATUS
     */
    private String STATUS;

    /**
     * This field corresponds to the database column IRP_REPORT_SCHED_LOG_DETAILS.REMARKS
     */
    private String REMARKS;

    /**
     * This field corresponds to the database column IRP_REPORT_SCHED_LOG_DETAILS.EMAIL_SUBJECT
     */
    private String EMAIL_SUBJECT;

    /**
     * This field corresponds to the database column IRP_REPORT_SCHED_LOG_DETAILS.CIF_NO
     */
    private BigDecimal CIF_NO;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_REPORT_SCHED_LOG_DETAILS.LINE_NBR
     *
     * @return the value of IRP_REPORT_SCHED_LOG_DETAILS.LINE_NBR
     */
    public BigDecimal getLINE_NBR() {
        return LINE_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_REPORT_SCHED_LOG_DETAILS.LINE_NBR
     *
     * @param LINE_NBR the value for IRP_REPORT_SCHED_LOG_DETAILS.LINE_NBR
     */
    public void setLINE_NBR(BigDecimal LINE_NBR) {
        this.LINE_NBR = LINE_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_REPORT_SCHED_LOG_DETAILS.REPORT_ID
     *
     * @return the value of IRP_REPORT_SCHED_LOG_DETAILS.REPORT_ID
     */
    public BigDecimal getREPORT_ID() {
        return REPORT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_REPORT_SCHED_LOG_DETAILS.REPORT_ID
     *
     * @param REPORT_ID the value for IRP_REPORT_SCHED_LOG_DETAILS.REPORT_ID
     */
    public void setREPORT_ID(BigDecimal REPORT_ID) {
        this.REPORT_ID = REPORT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_REPORT_SCHED_LOG_DETAILS.SCHEDULED_DATE
     *
     * @return the value of IRP_REPORT_SCHED_LOG_DETAILS.SCHEDULED_DATE
     */
    public Date getSCHEDULED_DATE() {
        return SCHEDULED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_REPORT_SCHED_LOG_DETAILS.SCHEDULED_DATE
     *
     * @param SCHEDULED_DATE the value for IRP_REPORT_SCHED_LOG_DETAILS.SCHEDULED_DATE
     */
    public void setSCHEDULED_DATE(Date SCHEDULED_DATE) {
        this.SCHEDULED_DATE = SCHEDULED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_REPORT_SCHED_LOG_DETAILS.SCHED_ID
     *
     * @return the value of IRP_REPORT_SCHED_LOG_DETAILS.SCHED_ID
     */
    public BigDecimal getSCHED_ID() {
        return SCHED_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_REPORT_SCHED_LOG_DETAILS.SCHED_ID
     *
     * @param SCHED_ID the value for IRP_REPORT_SCHED_LOG_DETAILS.SCHED_ID
     */
    public void setSCHED_ID(BigDecimal SCHED_ID) {
        this.SCHED_ID = SCHED_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_REPORT_SCHED_LOG_DETAILS.START_DATE
     *
     * @return the value of IRP_REPORT_SCHED_LOG_DETAILS.START_DATE
     */
    public Date getSTART_DATE() {
        return START_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_REPORT_SCHED_LOG_DETAILS.START_DATE
     *
     * @param START_DATE the value for IRP_REPORT_SCHED_LOG_DETAILS.START_DATE
     */
    public void setSTART_DATE(Date START_DATE) {
        this.START_DATE = START_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_REPORT_SCHED_LOG_DETAILS.FROM_EMAIL_VAL
     *
     * @return the value of IRP_REPORT_SCHED_LOG_DETAILS.FROM_EMAIL_VAL
     */
    public String getFROM_EMAIL_VAL() {
        return FROM_EMAIL_VAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_REPORT_SCHED_LOG_DETAILS.FROM_EMAIL_VAL
     *
     * @param FROM_EMAIL_VAL the value for IRP_REPORT_SCHED_LOG_DETAILS.FROM_EMAIL_VAL
     */
    public void setFROM_EMAIL_VAL(String FROM_EMAIL_VAL) {
        this.FROM_EMAIL_VAL = FROM_EMAIL_VAL == null ? null : FROM_EMAIL_VAL.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_REPORT_SCHED_LOG_DETAILS.RECEIVER_TYPE
     *
     * @return the value of IRP_REPORT_SCHED_LOG_DETAILS.RECEIVER_TYPE
     */
    public BigDecimal getRECEIVER_TYPE() {
        return RECEIVER_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_REPORT_SCHED_LOG_DETAILS.RECEIVER_TYPE
     *
     * @param RECEIVER_TYPE the value for IRP_REPORT_SCHED_LOG_DETAILS.RECEIVER_TYPE
     */
    public void setRECEIVER_TYPE(BigDecimal RECEIVER_TYPE) {
        this.RECEIVER_TYPE = RECEIVER_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_REPORT_SCHED_LOG_DETAILS.RECEIVER_EMAIL_VAL
     *
     * @return the value of IRP_REPORT_SCHED_LOG_DETAILS.RECEIVER_EMAIL_VAL
     */
    public String getRECEIVER_EMAIL_VAL() {
        return RECEIVER_EMAIL_VAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_REPORT_SCHED_LOG_DETAILS.RECEIVER_EMAIL_VAL
     *
     * @param RECEIVER_EMAIL_VAL the value for IRP_REPORT_SCHED_LOG_DETAILS.RECEIVER_EMAIL_VAL
     */
    public void setRECEIVER_EMAIL_VAL(String RECEIVER_EMAIL_VAL) {
        this.RECEIVER_EMAIL_VAL = RECEIVER_EMAIL_VAL == null ? null : RECEIVER_EMAIL_VAL.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_REPORT_SCHED_LOG_DETAILS.STATUS
     *
     * @return the value of IRP_REPORT_SCHED_LOG_DETAILS.STATUS
     */
    public String getSTATUS() {
        return STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_REPORT_SCHED_LOG_DETAILS.STATUS
     *
     * @param STATUS the value for IRP_REPORT_SCHED_LOG_DETAILS.STATUS
     */
    public void setSTATUS(String STATUS) {
        this.STATUS = STATUS == null ? null : STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_REPORT_SCHED_LOG_DETAILS.REMARKS
     *
     * @return the value of IRP_REPORT_SCHED_LOG_DETAILS.REMARKS
     */
    public String getREMARKS() {
        return REMARKS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_REPORT_SCHED_LOG_DETAILS.REMARKS
     *
     * @param REMARKS the value for IRP_REPORT_SCHED_LOG_DETAILS.REMARKS
     */
    public void setREMARKS(String REMARKS) {
        this.REMARKS = REMARKS == null ? null : REMARKS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_REPORT_SCHED_LOG_DETAILS.EMAIL_SUBJECT
     *
     * @return the value of IRP_REPORT_SCHED_LOG_DETAILS.EMAIL_SUBJECT
     */
    public String getEMAIL_SUBJECT() {
        return EMAIL_SUBJECT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_REPORT_SCHED_LOG_DETAILS.EMAIL_SUBJECT
     *
     * @param EMAIL_SUBJECT the value for IRP_REPORT_SCHED_LOG_DETAILS.EMAIL_SUBJECT
     */
    public void setEMAIL_SUBJECT(String EMAIL_SUBJECT) {
        this.EMAIL_SUBJECT = EMAIL_SUBJECT == null ? null : EMAIL_SUBJECT.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_REPORT_SCHED_LOG_DETAILS.CIF_NO
     *
     * @return the value of IRP_REPORT_SCHED_LOG_DETAILS.CIF_NO
     */
    public BigDecimal getCIF_NO() {
        return CIF_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_REPORT_SCHED_LOG_DETAILS.CIF_NO
     *
     * @param CIF_NO the value for IRP_REPORT_SCHED_LOG_DETAILS.CIF_NO
     */
    public void setCIF_NO(BigDecimal CIF_NO) {
        this.CIF_NO = CIF_NO;
    }
}