package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;
import java.util.Date;

public class IRP_SCHEDULEVO extends BaseVO {
    /**
     * This field corresponds to the database column IRP_SCHEDULE.SCHED_ID
     */
    private BigDecimal SCHED_ID;

    /**
     * This field corresponds to the database column IRP_SCHEDULE.END_OF_MONTH
     */
    private String END_OF_MONTH;

    /**
     * This field corresponds to the database column IRP_SCHEDULE.SCHED_NAME
     */
    private String SCHED_NAME;

    /**
     * This field corresponds to the database column IRP_SCHEDULE.FIRST_RUN_DATE
     */
    private Date FIRST_RUN_DATE;

    /**
     * This field corresponds to the database column IRP_SCHEDULE.SCHED_EXPIRY_DATE
     */
    private Date SCHED_EXPIRY_DATE;

    /**
     * This field corresponds to the database column IRP_SCHEDULE.SCHED_FREQUENCY
     */
    private String SCHED_FREQUENCY;

    /**
     * This field corresponds to the database column IRP_SCHEDULE.NEXT_RUN_DATE
     */
    private Date NEXT_RUN_DATE;

    /**
     * This field corresponds to the database column IRP_SCHEDULE.DATE_UPDATED
     */
    private Date DATE_UPDATED;

    /**
     * This field corresponds to the database column IRP_SCHEDULE.SCHED_TYPE
     */
    private BigDecimal SCHED_TYPE;

    /**
     * This field corresponds to the database column IRP_SCHEDULE.FREQUENCY_HOUR
     */
    private BigDecimal FREQUENCY_HOUR;

    /**
     * This field corresponds to the database column IRP_SCHEDULE.FREQUENCY_MINUTE
     */
    private BigDecimal FREQUENCY_MINUTE;

    /**
     * This field corresponds to the database column IRP_SCHEDULE.BATCH_CODE
     */
    private BigDecimal BATCH_CODE;

    /**
     * This field corresponds to the database column IRP_SCHEDULE.EVT_ID
     */
    private BigDecimal EVT_ID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_SCHEDULE.SCHED_ID
     *
     * @return the value of IRP_SCHEDULE.SCHED_ID
     */
    public BigDecimal getSCHED_ID() {
        return SCHED_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_SCHEDULE.SCHED_ID
     *
     * @param SCHED_ID the value for IRP_SCHEDULE.SCHED_ID
     */
    public void setSCHED_ID(BigDecimal SCHED_ID) {
        this.SCHED_ID = SCHED_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_SCHEDULE.END_OF_MONTH
     *
     * @return the value of IRP_SCHEDULE.END_OF_MONTH
     */
    public String getEND_OF_MONTH() {
        return END_OF_MONTH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_SCHEDULE.END_OF_MONTH
     *
     * @param END_OF_MONTH the value for IRP_SCHEDULE.END_OF_MONTH
     */
    public void setEND_OF_MONTH(String END_OF_MONTH) {
        this.END_OF_MONTH = END_OF_MONTH == null ? null : END_OF_MONTH.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_SCHEDULE.SCHED_NAME
     *
     * @return the value of IRP_SCHEDULE.SCHED_NAME
     */
    public String getSCHED_NAME() {
        return SCHED_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_SCHEDULE.SCHED_NAME
     *
     * @param SCHED_NAME the value for IRP_SCHEDULE.SCHED_NAME
     */
    public void setSCHED_NAME(String SCHED_NAME) {
        this.SCHED_NAME = SCHED_NAME == null ? null : SCHED_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_SCHEDULE.FIRST_RUN_DATE
     *
     * @return the value of IRP_SCHEDULE.FIRST_RUN_DATE
     */
    public Date getFIRST_RUN_DATE() {
        return FIRST_RUN_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_SCHEDULE.FIRST_RUN_DATE
     *
     * @param FIRST_RUN_DATE the value for IRP_SCHEDULE.FIRST_RUN_DATE
     */
    public void setFIRST_RUN_DATE(Date FIRST_RUN_DATE) {
        this.FIRST_RUN_DATE = FIRST_RUN_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_SCHEDULE.SCHED_EXPIRY_DATE
     *
     * @return the value of IRP_SCHEDULE.SCHED_EXPIRY_DATE
     */
    public Date getSCHED_EXPIRY_DATE() {
        return SCHED_EXPIRY_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_SCHEDULE.SCHED_EXPIRY_DATE
     *
     * @param SCHED_EXPIRY_DATE the value for IRP_SCHEDULE.SCHED_EXPIRY_DATE
     */
    public void setSCHED_EXPIRY_DATE(Date SCHED_EXPIRY_DATE) {
        this.SCHED_EXPIRY_DATE = SCHED_EXPIRY_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_SCHEDULE.SCHED_FREQUENCY
     *
     * @return the value of IRP_SCHEDULE.SCHED_FREQUENCY
     */
    public String getSCHED_FREQUENCY() {
        return SCHED_FREQUENCY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_SCHEDULE.SCHED_FREQUENCY
     *
     * @param SCHED_FREQUENCY the value for IRP_SCHEDULE.SCHED_FREQUENCY
     */
    public void setSCHED_FREQUENCY(String SCHED_FREQUENCY) {
        this.SCHED_FREQUENCY = SCHED_FREQUENCY == null ? null : SCHED_FREQUENCY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_SCHEDULE.NEXT_RUN_DATE
     *
     * @return the value of IRP_SCHEDULE.NEXT_RUN_DATE
     */
    public Date getNEXT_RUN_DATE() {
        return NEXT_RUN_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_SCHEDULE.NEXT_RUN_DATE
     *
     * @param NEXT_RUN_DATE the value for IRP_SCHEDULE.NEXT_RUN_DATE
     */
    public void setNEXT_RUN_DATE(Date NEXT_RUN_DATE) {
        this.NEXT_RUN_DATE = NEXT_RUN_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_SCHEDULE.DATE_UPDATED
     *
     * @return the value of IRP_SCHEDULE.DATE_UPDATED
     */
    public Date getDATE_UPDATED() {
        return DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_SCHEDULE.DATE_UPDATED
     *
     * @param DATE_UPDATED the value for IRP_SCHEDULE.DATE_UPDATED
     */
    public void setDATE_UPDATED(Date DATE_UPDATED) {
        this.DATE_UPDATED = DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_SCHEDULE.SCHED_TYPE
     *
     * @return the value of IRP_SCHEDULE.SCHED_TYPE
     */
    public BigDecimal getSCHED_TYPE() {
        return SCHED_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_SCHEDULE.SCHED_TYPE
     *
     * @param SCHED_TYPE the value for IRP_SCHEDULE.SCHED_TYPE
     */
    public void setSCHED_TYPE(BigDecimal SCHED_TYPE) {
        this.SCHED_TYPE = SCHED_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_SCHEDULE.FREQUENCY_HOUR
     *
     * @return the value of IRP_SCHEDULE.FREQUENCY_HOUR
     */
    public BigDecimal getFREQUENCY_HOUR() {
        return FREQUENCY_HOUR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_SCHEDULE.FREQUENCY_HOUR
     *
     * @param FREQUENCY_HOUR the value for IRP_SCHEDULE.FREQUENCY_HOUR
     */
    public void setFREQUENCY_HOUR(BigDecimal FREQUENCY_HOUR) {
        this.FREQUENCY_HOUR = FREQUENCY_HOUR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_SCHEDULE.FREQUENCY_MINUTE
     *
     * @return the value of IRP_SCHEDULE.FREQUENCY_MINUTE
     */
    public BigDecimal getFREQUENCY_MINUTE() {
        return FREQUENCY_MINUTE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_SCHEDULE.FREQUENCY_MINUTE
     *
     * @param FREQUENCY_MINUTE the value for IRP_SCHEDULE.FREQUENCY_MINUTE
     */
    public void setFREQUENCY_MINUTE(BigDecimal FREQUENCY_MINUTE) {
        this.FREQUENCY_MINUTE = FREQUENCY_MINUTE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_SCHEDULE.BATCH_CODE
     *
     * @return the value of IRP_SCHEDULE.BATCH_CODE
     */
    public BigDecimal getBATCH_CODE() {
        return BATCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_SCHEDULE.BATCH_CODE
     *
     * @param BATCH_CODE the value for IRP_SCHEDULE.BATCH_CODE
     */
    public void setBATCH_CODE(BigDecimal BATCH_CODE) {
        this.BATCH_CODE = BATCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_SCHEDULE.EVT_ID
     *
     * @return the value of IRP_SCHEDULE.EVT_ID
     */
    public BigDecimal getEVT_ID() {
        return EVT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_SCHEDULE.EVT_ID
     *
     * @param EVT_ID the value for IRP_SCHEDULE.EVT_ID
     */
    public void setEVT_ID(BigDecimal EVT_ID) {
        this.EVT_ID = EVT_ID;
    }
}