package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

import com.path.lib.vo.BaseVO;

public class IRP_FILE_MAINVO extends BaseVO {
    /**
     * This field corresponds to the database column IRP_FILE_MAIN.FILE_ID
     */
    private BigDecimal FILE_ID;

    /**
     * This field corresponds to the database column IRP_FILE_MAIN.FILE_NAME
     */
    private String FILE_NAME;

    /**
     * This field corresponds to the database column IRP_FILE_MAIN.DATE_UPDATED
     */
    private Date DATE_UPDATED;

    /**
     * This field corresponds to the database column IRP_FILE_MAIN.FILE_CONTENT
     */
    private byte[] FILE_CONTENT;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_FILE_MAIN.FILE_ID
     *
     * @return the value of IRP_FILE_MAIN.FILE_ID
     */
    public BigDecimal getFILE_ID() {
        return FILE_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_FILE_MAIN.FILE_ID
     *
     * @param FILE_ID the value for IRP_FILE_MAIN.FILE_ID
     */
    public void setFILE_ID(BigDecimal FILE_ID) {
        this.FILE_ID = FILE_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_FILE_MAIN.FILE_NAME
     *
     * @return the value of IRP_FILE_MAIN.FILE_NAME
     */
    public String getFILE_NAME() {
        return FILE_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_FILE_MAIN.FILE_NAME
     *
     * @param FILE_NAME the value for IRP_FILE_MAIN.FILE_NAME
     */
    public void setFILE_NAME(String FILE_NAME) {
        this.FILE_NAME = FILE_NAME == null ? null : FILE_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_FILE_MAIN.DATE_UPDATED
     *
     * @return the value of IRP_FILE_MAIN.DATE_UPDATED
     */
    public Date getDATE_UPDATED() {
        return DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_FILE_MAIN.DATE_UPDATED
     *
     * @param DATE_UPDATED the value for IRP_FILE_MAIN.DATE_UPDATED
     */
    public void setDATE_UPDATED(Date DATE_UPDATED) {
        this.DATE_UPDATED = DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_FILE_MAIN.FILE_CONTENT
     *
     * @return the value of IRP_FILE_MAIN.FILE_CONTENT
     */
    public byte[] getFILE_CONTENT() {
        return FILE_CONTENT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_FILE_MAIN.FILE_CONTENT
     *
     * @param FILE_CONTENT the value for IRP_FILE_MAIN.FILE_CONTENT
     */
    public void setFILE_CONTENT(byte[] FILE_CONTENT) {
        this.FILE_CONTENT = FILE_CONTENT;
    }
    
   
}