package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;
import java.util.Date;

public class IRP_FOLDERVO extends BaseVO {
    /**
     * This field corresponds to the database column IRP_FOLDER.FOLDER_CODE
     */
    private BigDecimal FOLDER_CODE;

    /**
     * This field corresponds to the database column IRP_FOLDER.FOLDER_REF
     */
    private String FOLDER_REF;

    /**
     * This field corresponds to the database column IRP_FOLDER.PARENT_REF
     */
    private String PARENT_REF;

    /**
     * This field corresponds to the database column IRP_FOLDER.DATE_UPDATED
     */
    private Date DATE_UPDATED;

    /**
     * This field corresponds to the database column IRP_FOLDER.DISP_ORDER
     */
    private BigDecimal DISP_ORDER;

    /**
     * This field corresponds to the database column IRP_FOLDER.BRIEF_NAME_ENG
     */
    private String BRIEF_NAME_ENG;

    /**
     * This field corresponds to the database column IRP_FOLDER.BRIEF_NAME_ARAB
     */
    private String BRIEF_NAME_ARAB;

    /**
     * This field corresponds to the database column IRP_FOLDER.APP_NAME
     */
    private String APP_NAME;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_FOLDER.FOLDER_CODE
     *
     * @return the value of IRP_FOLDER.FOLDER_CODE
     */
    public BigDecimal getFOLDER_CODE() {
        return FOLDER_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_FOLDER.FOLDER_CODE
     *
     * @param FOLDER_CODE the value for IRP_FOLDER.FOLDER_CODE
     */
    public void setFOLDER_CODE(BigDecimal FOLDER_CODE) {
        this.FOLDER_CODE = FOLDER_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_FOLDER.FOLDER_REF
     *
     * @return the value of IRP_FOLDER.FOLDER_REF
     */
    public String getFOLDER_REF() {
        return FOLDER_REF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_FOLDER.FOLDER_REF
     *
     * @param FOLDER_REF the value for IRP_FOLDER.FOLDER_REF
     */
    public void setFOLDER_REF(String FOLDER_REF) {
        this.FOLDER_REF = FOLDER_REF == null ? null : FOLDER_REF.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_FOLDER.PARENT_REF
     *
     * @return the value of IRP_FOLDER.PARENT_REF
     */
    public String getPARENT_REF() {
        return PARENT_REF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_FOLDER.PARENT_REF
     *
     * @param PARENT_REF the value for IRP_FOLDER.PARENT_REF
     */
    public void setPARENT_REF(String PARENT_REF) {
        this.PARENT_REF = PARENT_REF == null ? null : PARENT_REF.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_FOLDER.DATE_UPDATED
     *
     * @return the value of IRP_FOLDER.DATE_UPDATED
     */
    public Date getDATE_UPDATED() {
        return DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_FOLDER.DATE_UPDATED
     *
     * @param DATE_UPDATED the value for IRP_FOLDER.DATE_UPDATED
     */
    public void setDATE_UPDATED(Date DATE_UPDATED) {
        this.DATE_UPDATED = DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_FOLDER.DISP_ORDER
     *
     * @return the value of IRP_FOLDER.DISP_ORDER
     */
    public BigDecimal getDISP_ORDER() {
        return DISP_ORDER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_FOLDER.DISP_ORDER
     *
     * @param DISP_ORDER the value for IRP_FOLDER.DISP_ORDER
     */
    public void setDISP_ORDER(BigDecimal DISP_ORDER) {
        this.DISP_ORDER = DISP_ORDER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_FOLDER.BRIEF_NAME_ENG
     *
     * @return the value of IRP_FOLDER.BRIEF_NAME_ENG
     */
    public String getBRIEF_NAME_ENG() {
        return BRIEF_NAME_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_FOLDER.BRIEF_NAME_ENG
     *
     * @param BRIEF_NAME_ENG the value for IRP_FOLDER.BRIEF_NAME_ENG
     */
    public void setBRIEF_NAME_ENG(String BRIEF_NAME_ENG) {
        this.BRIEF_NAME_ENG = BRIEF_NAME_ENG == null ? null : BRIEF_NAME_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_FOLDER.BRIEF_NAME_ARAB
     *
     * @return the value of IRP_FOLDER.BRIEF_NAME_ARAB
     */
    public String getBRIEF_NAME_ARAB() {
        return BRIEF_NAME_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_FOLDER.BRIEF_NAME_ARAB
     *
     * @param BRIEF_NAME_ARAB the value for IRP_FOLDER.BRIEF_NAME_ARAB
     */
    public void setBRIEF_NAME_ARAB(String BRIEF_NAME_ARAB) {
        this.BRIEF_NAME_ARAB = BRIEF_NAME_ARAB == null ? null : BRIEF_NAME_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_FOLDER.APP_NAME
     *
     * @return the value of IRP_FOLDER.APP_NAME
     */
    public String getAPP_NAME() {
        return APP_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_FOLDER.APP_NAME
     *
     * @param APP_NAME the value for IRP_FOLDER.APP_NAME
     */
    public void setAPP_NAME(String APP_NAME) {
        this.APP_NAME = APP_NAME == null ? null : APP_NAME.trim();
    }
}