package com.path.dbmaps.vo;

import java.math.BigDecimal;

import com.path.lib.vo.BaseVO;

public class IRP_REP_SCHED_MAIL_RECEIVERSVO extends BaseVO {
    /**
     * This field corresponds to the database column IRP_REP_SCHED_MAIL_RECEIVERS.SCHED_ID
     */
    private BigDecimal SCHED_ID;

    /**
     * This field corresponds to the database column IRP_REP_SCHED_MAIL_RECEIVERS.REPORT_ID
     */
    private BigDecimal REPORT_ID;

    /**
     * This field corresponds to the database column IRP_REP_SCHED_MAIL_RECEIVERS.USER_ID
     */
    private String USER_ID;

    /**
     * This field corresponds to the database column IRP_REP_SCHED_MAIL_RECEIVERS.RECEIVER_TYPE
     */
    private BigDecimal RECEIVER_TYPE;
    
    /**
     * This field corresponds to the database column IRP_REP_SCHED_MAIL_RECEIVERS.REPORT_REF
     */
    private String REPORT_REF;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_REP_SCHED_MAIL_RECEIVERS.SCHED_ID
     *
     * @return the value of IRP_REP_SCHED_MAIL_RECEIVERS.SCHED_ID
     */
    public BigDecimal getSCHED_ID() {
        return SCHED_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_REP_SCHED_MAIL_RECEIVERS.SCHED_ID
     *
     * @param SCHED_ID the value for IRP_REP_SCHED_MAIL_RECEIVERS.SCHED_ID
     */
    public void setSCHED_ID(BigDecimal SCHED_ID) {
        this.SCHED_ID = SCHED_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_REP_SCHED_MAIL_RECEIVERS.REPORT_ID
     *
     * @return the value of IRP_REP_SCHED_MAIL_RECEIVERS.REPORT_ID
     */
    public BigDecimal getREPORT_ID() {
        return REPORT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_REP_SCHED_MAIL_RECEIVERS.REPORT_ID
     *
     * @param REPORT_ID the value for IRP_REP_SCHED_MAIL_RECEIVERS.REPORT_ID
     */
    public void setREPORT_ID(BigDecimal REPORT_ID) {
        this.REPORT_ID = REPORT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_REP_SCHED_MAIL_RECEIVERS.USER_ID
     *
     * @return the value of IRP_REP_SCHED_MAIL_RECEIVERS.USER_ID
     */
    public String getUSER_ID() {
        return USER_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_REP_SCHED_MAIL_RECEIVERS.USER_ID
     *
     * @param USER_ID the value for IRP_REP_SCHED_MAIL_RECEIVERS.USER_ID
     */
    public void setUSER_ID(String USER_ID) {
        this.USER_ID = USER_ID == null ? null : USER_ID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_REP_SCHED_MAIL_RECEIVERS.RECEIVER_TYPE
     *
     * @return the value of IRP_REP_SCHED_MAIL_RECEIVERS.RECEIVER_TYPE
     */
    public BigDecimal getRECEIVER_TYPE() {
        return RECEIVER_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_REP_SCHED_MAIL_RECEIVERS.RECEIVER_TYPE
     *
     * @param RECEIVER_TYPE the value for IRP_REP_SCHED_MAIL_RECEIVERS.RECEIVER_TYPE
     */
    public void setRECEIVER_TYPE(BigDecimal RECEIVER_TYPE) {
        this.RECEIVER_TYPE = RECEIVER_TYPE;
    }
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_REP_SCHED_MAIL_RECEIVERS.REPORT_REF
     *
     * @return the value of IRP_REP_SCHED_MAIL_RECEIVERS.REPORT_REF
     */
    public String getREPORT_REF() {
        return REPORT_REF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_REP_SCHED_MAIL_RECEIVERS.REPORT_REF
     *
     * @param REPORT_REF the value for IRP_REP_SCHED_MAIL_RECEIVERS.REPORT_REF
     */
    public void setREPORT_REF(String REPORT_REF) {
        this.REPORT_REF = REPORT_REF == null ? null : REPORT_REF.trim();
    }
}