package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class IRP_PROCVO extends BaseVO {
    /**
     * This field corresponds to the database column IRP_PROC.PROC_ID
     */
    private BigDecimal PROC_ID;

    /**
     * This field corresponds to the database column IRP_PROC.PROC_NAME
     */
    private String PROC_NAME;

    /**
     * This field corresponds to the database column IRP_PROC.PROC_DESC
     */
    private String PROC_DESC;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_PROC.PROC_ID
     *
     * @return the value of IRP_PROC.PROC_ID
     */
    public BigDecimal getPROC_ID() {
        return PROC_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_PROC.PROC_ID
     *
     * @param PROC_ID the value for IRP_PROC.PROC_ID
     */
    public void setPROC_ID(BigDecimal PROC_ID) {
        this.PROC_ID = PROC_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_PROC.PROC_NAME
     *
     * @return the value of IRP_PROC.PROC_NAME
     */
    public String getPROC_NAME() {
        return PROC_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_PROC.PROC_NAME
     *
     * @param PROC_NAME the value for IRP_PROC.PROC_NAME
     */
    public void setPROC_NAME(String PROC_NAME) {
        this.PROC_NAME = PROC_NAME == null ? null : PROC_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_PROC.PROC_DESC
     *
     * @return the value of IRP_PROC.PROC_DESC
     */
    public String getPROC_DESC() {
        return PROC_DESC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_PROC.PROC_DESC
     *
     * @param PROC_DESC the value for IRP_PROC.PROC_DESC
     */
    public void setPROC_DESC(String PROC_DESC) {
        this.PROC_DESC = PROC_DESC == null ? null : PROC_DESC.trim();
    }
}