package com.path.dbmaps.vo;

public class IRP_REPORT_PAGINATIONVOWithBLOBs extends IRP_REPORT_PAGINATIONVOKey {
    /**
     * This field corresponds to the database column IRP_REPORT_PAGINATION.REPORT_CONTENT
     */
    private byte[] REPORT_CONTENT;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_REPORT_PAGINATION.REPORT_CONTENT
     *
     * @return the value of IRP_REPORT_PAGINATION.REPORT_CONTENT
     */
    public byte[] getREPORT_CONTENT() {
        return REPORT_CONTENT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_REPORT_PAGINATION.REPORT_CONTENT
     *
     * @param REPORT_CONTENT the value for IRP_REPORT_PAGINATION.REPORT_CONTENT
     */
    public void setREPORT_CONTENT(byte[] REPORT_CONTENT) {
        this.REPORT_CONTENT = REPORT_CONTENT;
    }
}