package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class IRP_TEMPLATE_COLUMNS_DETVOKey extends BaseVO {
    /**
     * This field corresponds to the database column IRP_TEMPLATE_COLUMNS_DET.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column IRP_TEMPLATE_COLUMNS_DET.TEMPLATE_CODE
     */
    private BigDecimal TEMPLATE_CODE;

    /**
     * This field corresponds to the database column IRP_TEMPLATE_COLUMNS_DET.TEMPLATE_COL_NO
     */
    private BigDecimal TEMPLATE_COL_NO;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_TEMPLATE_COLUMNS_DET.COMP_CODE
     *
     * @return the value of IRP_TEMPLATE_COLUMNS_DET.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_TEMPLATE_COLUMNS_DET.COMP_CODE
     *
     * @param COMP_CODE the value for IRP_TEMPLATE_COLUMNS_DET.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_TEMPLATE_COLUMNS_DET.TEMPLATE_CODE
     *
     * @return the value of IRP_TEMPLATE_COLUMNS_DET.TEMPLATE_CODE
     */
    public BigDecimal getTEMPLATE_CODE() {
        return TEMPLATE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_TEMPLATE_COLUMNS_DET.TEMPLATE_CODE
     *
     * @param TEMPLATE_CODE the value for IRP_TEMPLATE_COLUMNS_DET.TEMPLATE_CODE
     */
    public void setTEMPLATE_CODE(BigDecimal TEMPLATE_CODE) {
        this.TEMPLATE_CODE = TEMPLATE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_TEMPLATE_COLUMNS_DET.TEMPLATE_COL_NO
     *
     * @return the value of IRP_TEMPLATE_COLUMNS_DET.TEMPLATE_COL_NO
     */
    public BigDecimal getTEMPLATE_COL_NO() {
        return TEMPLATE_COL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_TEMPLATE_COLUMNS_DET.TEMPLATE_COL_NO
     *
     * @param TEMPLATE_COL_NO the value for IRP_TEMPLATE_COLUMNS_DET.TEMPLATE_COL_NO
     */
    public void setTEMPLATE_COL_NO(BigDecimal TEMPLATE_COL_NO) {
        this.TEMPLATE_COL_NO = TEMPLATE_COL_NO;
    }
}