package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;
import java.util.Date;

public class IRP_APP_CONNECTIONVO extends BaseVO {
    /**
     * This field corresponds to the database column IRP_APP_CONNECTION.APP_NAME
     */
    private String APP_NAME;

    /**
     * This field corresponds to the database column IRP_APP_CONNECTION.CON_ID
     */
    private BigDecimal CON_ID;

    /**
     * This field corresponds to the database column IRP_APP_CONNECTION.DATE_UPDATED
     */
    private Date DATE_UPDATED;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_APP_CONNECTION.APP_NAME
     *
     * @return the value of IRP_APP_CONNECTION.APP_NAME
     */
    public String getAPP_NAME() {
        return APP_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_APP_CONNECTION.APP_NAME
     *
     * @param APP_NAME the value for IRP_APP_CONNECTION.APP_NAME
     */
    public void setAPP_NAME(String APP_NAME) {
        this.APP_NAME = APP_NAME == null ? null : APP_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_APP_CONNECTION.CON_ID
     *
     * @return the value of IRP_APP_CONNECTION.CON_ID
     */
    public BigDecimal getCON_ID() {
        return CON_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_APP_CONNECTION.CON_ID
     *
     * @param CON_ID the value for IRP_APP_CONNECTION.CON_ID
     */
    public void setCON_ID(BigDecimal CON_ID) {
        this.CON_ID = CON_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_APP_CONNECTION.DATE_UPDATED
     *
     * @return the value of IRP_APP_CONNECTION.DATE_UPDATED
     */
    public Date getDATE_UPDATED() {
        return DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_APP_CONNECTION.DATE_UPDATED
     *
     * @param DATE_UPDATED the value for IRP_APP_CONNECTION.DATE_UPDATED
     */
    public void setDATE_UPDATED(Date DATE_UPDATED) {
        this.DATE_UPDATED = DATE_UPDATED;
    }
}