package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;

public class IRP_CTRLVO extends BaseVO {
    /**
     * This field corresponds to the database column IRP_CTRL.OVERSIZE_LIMIT
     */
    private String OVERSIZE_LIMIT;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_CTRL.OVERSIZE_LIMIT
     *
     * @return the value of IRP_CTRL.OVERSIZE_LIMIT
     */
    public String getOVERSIZE_LIMIT() {
        return OVERSIZE_LIMIT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_CTRL.OVERSIZE_LIMIT
     *
     * @param OVERSIZE_LIMIT the value for IRP_CTRL.OVERSIZE_LIMIT
     */
    public void setOVERSIZE_LIMIT(String OVERSIZE_LIMIT) {
        this.OVERSIZE_LIMIT = OVERSIZE_LIMIT == null ? null : OVERSIZE_LIMIT.trim();
    }
}