package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class IRP_REPORT_PAGINATIONVOKey extends BaseVO {
    /**
     * This field corresponds to the database column IRP_REPORT_PAGINATION.APP_NAME
     */
    private String APP_NAME;

    /**
     * This field corresponds to the database column IRP_REPORT_PAGINATION.FROM_PAGE
     */
    private BigDecimal FROM_PAGE;

    /**
     * This field corresponds to the database column IRP_REPORT_PAGINATION.PAGE_COUNTER
     */
    private BigDecimal PAGE_COUNTER;

    /**
     * This field corresponds to the database column IRP_REPORT_PAGINATION.PROG_REF
     */
    private String PROG_REF;

    /**
     * This field corresponds to the database column IRP_REPORT_PAGINATION.TO_PAGE
     */
    private BigDecimal TO_PAGE;

    /**
     * This field corresponds to the database column IRP_REPORT_PAGINATION.USER_ID
     */
    private String USER_ID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_REPORT_PAGINATION.APP_NAME
     *
     * @return the value of IRP_REPORT_PAGINATION.APP_NAME
     */
    public String getAPP_NAME() {
        return APP_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_REPORT_PAGINATION.APP_NAME
     *
     * @param APP_NAME the value for IRP_REPORT_PAGINATION.APP_NAME
     */
    public void setAPP_NAME(String APP_NAME) {
        this.APP_NAME = APP_NAME == null ? null : APP_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_REPORT_PAGINATION.FROM_PAGE
     *
     * @return the value of IRP_REPORT_PAGINATION.FROM_PAGE
     */
    public BigDecimal getFROM_PAGE() {
        return FROM_PAGE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_REPORT_PAGINATION.FROM_PAGE
     *
     * @param FROM_PAGE the value for IRP_REPORT_PAGINATION.FROM_PAGE
     */
    public void setFROM_PAGE(BigDecimal FROM_PAGE) {
        this.FROM_PAGE = FROM_PAGE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_REPORT_PAGINATION.PAGE_COUNTER
     *
     * @return the value of IRP_REPORT_PAGINATION.PAGE_COUNTER
     */
    public BigDecimal getPAGE_COUNTER() {
        return PAGE_COUNTER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_REPORT_PAGINATION.PAGE_COUNTER
     *
     * @param PAGE_COUNTER the value for IRP_REPORT_PAGINATION.PAGE_COUNTER
     */
    public void setPAGE_COUNTER(BigDecimal PAGE_COUNTER) {
        this.PAGE_COUNTER = PAGE_COUNTER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_REPORT_PAGINATION.PROG_REF
     *
     * @return the value of IRP_REPORT_PAGINATION.PROG_REF
     */
    public String getPROG_REF() {
        return PROG_REF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_REPORT_PAGINATION.PROG_REF
     *
     * @param PROG_REF the value for IRP_REPORT_PAGINATION.PROG_REF
     */
    public void setPROG_REF(String PROG_REF) {
        this.PROG_REF = PROG_REF == null ? null : PROG_REF.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_REPORT_PAGINATION.TO_PAGE
     *
     * @return the value of IRP_REPORT_PAGINATION.TO_PAGE
     */
    public BigDecimal getTO_PAGE() {
        return TO_PAGE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_REPORT_PAGINATION.TO_PAGE
     *
     * @param TO_PAGE the value for IRP_REPORT_PAGINATION.TO_PAGE
     */
    public void setTO_PAGE(BigDecimal TO_PAGE) {
        this.TO_PAGE = TO_PAGE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_REPORT_PAGINATION.USER_ID
     *
     * @return the value of IRP_REPORT_PAGINATION.USER_ID
     */
    public String getUSER_ID() {
        return USER_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_REPORT_PAGINATION.USER_ID
     *
     * @param USER_ID the value for IRP_REPORT_PAGINATION.USER_ID
     */
    public void setUSER_ID(String USER_ID) {
        this.USER_ID = USER_ID == null ? null : USER_ID.trim();
    }
}