package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;
import java.util.Date;

public class IRP_MAIL_SERVER_CONFIGVO extends BaseVO {
    /**
     * This field corresponds to the database column IRP_MAIL_SERVER_CONFIG.MAIL_SERVER_CODE
     */
    private BigDecimal MAIL_SERVER_CODE;

    /**
     * This field corresponds to the database column IRP_MAIL_SERVER_CONFIG.HOST
     */
    private String HOST;

    /**
     * This field corresponds to the database column IRP_MAIL_SERVER_CONFIG.PORT
     */
    private BigDecimal PORT;

    /**
     * This field corresponds to the database column IRP_MAIL_SERVER_CONFIG.SERVER_USER_NAME
     */
    private String SERVER_USER_NAME;

    /**
     * This field corresponds to the database column IRP_MAIL_SERVER_CONFIG.SERVER_PASS
     */
    private String SERVER_PASS;

    /**
     * This field corresponds to the database column IRP_MAIL_SERVER_CONFIG.MAIL_FROM
     */
    private String MAIL_FROM;

    /**
     * This field corresponds to the database column IRP_MAIL_SERVER_CONFIG.DATE_UPDATED
     */
    private Date DATE_UPDATED;

    /**
     * This field corresponds to the database column IRP_MAIL_SERVER_CONFIG.SSL_ENABLE_YN
     */
    private BigDecimal SSL_ENABLE_YN;

    /**
     * This field corresponds to the database column IRP_MAIL_SERVER_CONFIG.SSL_PORT_NBR
     */
    private BigDecimal SSL_PORT_NBR;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_MAIL_SERVER_CONFIG.MAIL_SERVER_CODE
     *
     * @return the value of IRP_MAIL_SERVER_CONFIG.MAIL_SERVER_CODE
     */
    public BigDecimal getMAIL_SERVER_CODE() {
        return MAIL_SERVER_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_MAIL_SERVER_CONFIG.MAIL_SERVER_CODE
     *
     * @param MAIL_SERVER_CODE the value for IRP_MAIL_SERVER_CONFIG.MAIL_SERVER_CODE
     */
    public void setMAIL_SERVER_CODE(BigDecimal MAIL_SERVER_CODE) {
        this.MAIL_SERVER_CODE = MAIL_SERVER_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_MAIL_SERVER_CONFIG.HOST
     *
     * @return the value of IRP_MAIL_SERVER_CONFIG.HOST
     */
    public String getHOST() {
        return HOST;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_MAIL_SERVER_CONFIG.HOST
     *
     * @param HOST the value for IRP_MAIL_SERVER_CONFIG.HOST
     */
    public void setHOST(String HOST) {
        this.HOST = HOST == null ? null : HOST.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_MAIL_SERVER_CONFIG.PORT
     *
     * @return the value of IRP_MAIL_SERVER_CONFIG.PORT
     */
    public BigDecimal getPORT() {
        return PORT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_MAIL_SERVER_CONFIG.PORT
     *
     * @param PORT the value for IRP_MAIL_SERVER_CONFIG.PORT
     */
    public void setPORT(BigDecimal PORT) {
        this.PORT = PORT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_MAIL_SERVER_CONFIG.SERVER_USER_NAME
     *
     * @return the value of IRP_MAIL_SERVER_CONFIG.SERVER_USER_NAME
     */
    public String getSERVER_USER_NAME() {
        return SERVER_USER_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_MAIL_SERVER_CONFIG.SERVER_USER_NAME
     *
     * @param SERVER_USER_NAME the value for IRP_MAIL_SERVER_CONFIG.SERVER_USER_NAME
     */
    public void setSERVER_USER_NAME(String SERVER_USER_NAME) {
        this.SERVER_USER_NAME = SERVER_USER_NAME == null ? null : SERVER_USER_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_MAIL_SERVER_CONFIG.SERVER_PASS
     *
     * @return the value of IRP_MAIL_SERVER_CONFIG.SERVER_PASS
     */
    public String getSERVER_PASS() {
        return SERVER_PASS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_MAIL_SERVER_CONFIG.SERVER_PASS
     *
     * @param SERVER_PASS the value for IRP_MAIL_SERVER_CONFIG.SERVER_PASS
     */
    public void setSERVER_PASS(String SERVER_PASS) {
        this.SERVER_PASS = SERVER_PASS == null ? null : SERVER_PASS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_MAIL_SERVER_CONFIG.MAIL_FROM
     *
     * @return the value of IRP_MAIL_SERVER_CONFIG.MAIL_FROM
     */
    public String getMAIL_FROM() {
        return MAIL_FROM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_MAIL_SERVER_CONFIG.MAIL_FROM
     *
     * @param MAIL_FROM the value for IRP_MAIL_SERVER_CONFIG.MAIL_FROM
     */
    public void setMAIL_FROM(String MAIL_FROM) {
        this.MAIL_FROM = MAIL_FROM == null ? null : MAIL_FROM.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_MAIL_SERVER_CONFIG.DATE_UPDATED
     *
     * @return the value of IRP_MAIL_SERVER_CONFIG.DATE_UPDATED
     */
    public Date getDATE_UPDATED() {
        return DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_MAIL_SERVER_CONFIG.DATE_UPDATED
     *
     * @param DATE_UPDATED the value for IRP_MAIL_SERVER_CONFIG.DATE_UPDATED
     */
    public void setDATE_UPDATED(Date DATE_UPDATED) {
        this.DATE_UPDATED = DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_MAIL_SERVER_CONFIG.SSL_ENABLE_YN
     *
     * @return the value of IRP_MAIL_SERVER_CONFIG.SSL_ENABLE_YN
     */
    public BigDecimal getSSL_ENABLE_YN() {
        return SSL_ENABLE_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_MAIL_SERVER_CONFIG.SSL_ENABLE_YN
     *
     * @param SSL_ENABLE_YN the value for IRP_MAIL_SERVER_CONFIG.SSL_ENABLE_YN
     */
    public void setSSL_ENABLE_YN(BigDecimal SSL_ENABLE_YN) {
        this.SSL_ENABLE_YN = SSL_ENABLE_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_MAIL_SERVER_CONFIG.SSL_PORT_NBR
     *
     * @return the value of IRP_MAIL_SERVER_CONFIG.SSL_PORT_NBR
     */
    public BigDecimal getSSL_PORT_NBR() {
        return SSL_PORT_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_MAIL_SERVER_CONFIG.SSL_PORT_NBR
     *
     * @param SSL_PORT_NBR the value for IRP_MAIL_SERVER_CONFIG.SSL_PORT_NBR
     */
    public void setSSL_PORT_NBR(BigDecimal SSL_PORT_NBR) {
        this.SSL_PORT_NBR = SSL_PORT_NBR;
    }
}