package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;

public class IRP_REP_SCHED_SESSION_PARAMVO extends BaseVO {
    /**
     * This field corresponds to the database column IRP_REP_SCHED_SESSION_PARAM.SESSION_NAME
     */
    private String SESSION_NAME;

    /**
     * This field corresponds to the database column IRP_REP_SCHED_SESSION_PARAM.SESSION_VAL
     */
    private String SESSION_VAL;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_REP_SCHED_SESSION_PARAM.SESSION_NAME
     *
     * @return the value of IRP_REP_SCHED_SESSION_PARAM.SESSION_NAME
     */
    public String getSESSION_NAME() {
        return SESSION_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_REP_SCHED_SESSION_PARAM.SESSION_NAME
     *
     * @param SESSION_NAME the value for IRP_REP_SCHED_SESSION_PARAM.SESSION_NAME
     */
    public void setSESSION_NAME(String SESSION_NAME) {
        this.SESSION_NAME = SESSION_NAME == null ? null : SESSION_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_REP_SCHED_SESSION_PARAM.SESSION_VAL
     *
     * @return the value of IRP_REP_SCHED_SESSION_PARAM.SESSION_VAL
     */
    public String getSESSION_VAL() {
        return SESSION_VAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_REP_SCHED_SESSION_PARAM.SESSION_VAL
     *
     * @param SESSION_VAL the value for IRP_REP_SCHED_SESSION_PARAM.SESSION_VAL
     */
    public void setSESSION_VAL(String SESSION_VAL) {
        this.SESSION_VAL = SESSION_VAL == null ? null : SESSION_VAL.trim();
    }
}