package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;

public class IRP_CRITERIA_TYPEVOKey extends BaseVO {
    /**
     * This field corresponds to the database column IRP_CRITERIA_TYPE.CRITERIA_TYPE_CODE
     */
    private String CRITERIA_TYPE_CODE;

    /**
     * This field corresponds to the database column IRP_CRITERIA_TYPE.LANG_CODE
     */
    private String LANG_CODE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_CRITERIA_TYPE.CRITERIA_TYPE_CODE
     *
     * @return the value of IRP_CRITERIA_TYPE.CRITERIA_TYPE_CODE
     */
    public String getCRITERIA_TYPE_CODE() {
        return CRITERIA_TYPE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_CRITERIA_TYPE.CRITERIA_TYPE_CODE
     *
     * @param CRITERIA_TYPE_CODE the value for IRP_CRITERIA_TYPE.CRITERIA_TYPE_CODE
     */
    public void setCRITERIA_TYPE_CODE(String CRITERIA_TYPE_CODE) {
        this.CRITERIA_TYPE_CODE = CRITERIA_TYPE_CODE == null ? null : CRITERIA_TYPE_CODE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_CRITERIA_TYPE.LANG_CODE
     *
     * @return the value of IRP_CRITERIA_TYPE.LANG_CODE
     */
    public String getLANG_CODE() {
        return LANG_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_CRITERIA_TYPE.LANG_CODE
     *
     * @param LANG_CODE the value for IRP_CRITERIA_TYPE.LANG_CODE
     */
    public void setLANG_CODE(String LANG_CODE) {
        this.LANG_CODE = LANG_CODE == null ? null : LANG_CODE.trim();
    }
}