package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class REP_SNAPSHOT_PARAM_MAPPINGVO extends BaseVO {
    /**
     * This field corresponds to the database column REP_SNAPSHOT_PARAM_MAPPING.REP_ID
     */
    private BigDecimal REP_ID;

    /**
     * This field corresponds to the database column REP_SNAPSHOT_PARAM_MAPPING.MAPPING_CODE
     */
    private BigDecimal MAPPING_CODE;

    /**
     * This field corresponds to the database column REP_SNAPSHOT_PARAM_MAPPING.PARAM_NAME
     */
    private String PARAM_NAME;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REP_SNAPSHOT_PARAM_MAPPING.REP_ID
     *
     * @return the value of REP_SNAPSHOT_PARAM_MAPPING.REP_ID
     */
    public BigDecimal getREP_ID() {
        return REP_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REP_SNAPSHOT_PARAM_MAPPING.REP_ID
     *
     * @param REP_ID the value for REP_SNAPSHOT_PARAM_MAPPING.REP_ID
     */
    public void setREP_ID(BigDecimal REP_ID) {
        this.REP_ID = REP_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REP_SNAPSHOT_PARAM_MAPPING.MAPPING_CODE
     *
     * @return the value of REP_SNAPSHOT_PARAM_MAPPING.MAPPING_CODE
     */
    public BigDecimal getMAPPING_CODE() {
        return MAPPING_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REP_SNAPSHOT_PARAM_MAPPING.MAPPING_CODE
     *
     * @param MAPPING_CODE the value for REP_SNAPSHOT_PARAM_MAPPING.MAPPING_CODE
     */
    public void setMAPPING_CODE(BigDecimal MAPPING_CODE) {
        this.MAPPING_CODE = MAPPING_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REP_SNAPSHOT_PARAM_MAPPING.PARAM_NAME
     *
     * @return the value of REP_SNAPSHOT_PARAM_MAPPING.PARAM_NAME
     */
    public String getPARAM_NAME() {
        return PARAM_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REP_SNAPSHOT_PARAM_MAPPING.PARAM_NAME
     *
     * @param PARAM_NAME the value for REP_SNAPSHOT_PARAM_MAPPING.PARAM_NAME
     */
    public void setPARAM_NAME(String PARAM_NAME) {
        this.PARAM_NAME = PARAM_NAME == null ? null : PARAM_NAME.trim();
    }
}