package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;
import java.util.Date;

public class REP_SITCOM_FILEVO extends BaseVO {
    /**
     * This field corresponds to the database column REP_SITCOM_FILE.SITCOM_FILE_ID
     */
    private BigDecimal SITCOM_FILE_ID;

    /**
     * This field corresponds to the database column REP_SITCOM_FILE.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column REP_SITCOM_FILE.SITCOM_DATE
     */
    private Date SITCOM_DATE;

    /**
     * This field corresponds to the database column REP_SITCOM_FILE.SITCOM_FREQUENCY
     */
    private String SITCOM_FREQUENCY;

    /**
     * This field corresponds to the database column REP_SITCOM_FILE.SITCOM_FILE
     */
    private byte[] SITCOM_FILE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REP_SITCOM_FILE.SITCOM_FILE_ID
     *
     * @return the value of REP_SITCOM_FILE.SITCOM_FILE_ID
     */
    public BigDecimal getSITCOM_FILE_ID() {
        return SITCOM_FILE_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REP_SITCOM_FILE.SITCOM_FILE_ID
     *
     * @param SITCOM_FILE_ID the value for REP_SITCOM_FILE.SITCOM_FILE_ID
     */
    public void setSITCOM_FILE_ID(BigDecimal SITCOM_FILE_ID) {
        this.SITCOM_FILE_ID = SITCOM_FILE_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REP_SITCOM_FILE.COMP_CODE
     *
     * @return the value of REP_SITCOM_FILE.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REP_SITCOM_FILE.COMP_CODE
     *
     * @param COMP_CODE the value for REP_SITCOM_FILE.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REP_SITCOM_FILE.SITCOM_DATE
     *
     * @return the value of REP_SITCOM_FILE.SITCOM_DATE
     */
    public Date getSITCOM_DATE() {
        return SITCOM_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REP_SITCOM_FILE.SITCOM_DATE
     *
     * @param SITCOM_DATE the value for REP_SITCOM_FILE.SITCOM_DATE
     */
    public void setSITCOM_DATE(Date SITCOM_DATE) {
        this.SITCOM_DATE = SITCOM_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REP_SITCOM_FILE.SITCOM_FREQUENCY
     *
     * @return the value of REP_SITCOM_FILE.SITCOM_FREQUENCY
     */
    public String getSITCOM_FREQUENCY() {
        return SITCOM_FREQUENCY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REP_SITCOM_FILE.SITCOM_FREQUENCY
     *
     * @param SITCOM_FREQUENCY the value for REP_SITCOM_FILE.SITCOM_FREQUENCY
     */
    public void setSITCOM_FREQUENCY(String SITCOM_FREQUENCY) {
        this.SITCOM_FREQUENCY = SITCOM_FREQUENCY == null ? null : SITCOM_FREQUENCY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REP_SITCOM_FILE.SITCOM_FILE
     *
     * @return the value of REP_SITCOM_FILE.SITCOM_FILE
     */
    public byte[] getSITCOM_FILE() {
        return SITCOM_FILE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REP_SITCOM_FILE.SITCOM_FILE
     *
     * @param SITCOM_FILE the value for REP_SITCOM_FILE.SITCOM_FILE
     */
    public void setSITCOM_FILE(byte[] SITCOM_FILE) {
        this.SITCOM_FILE = SITCOM_FILE;
    }
}