package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

import com.path.lib.vo.BaseVO;

public class REP_SNAPSHOT_PARAMVO extends BaseVO {
    /**
     * This field corresponds to the database column REP_SNAPSHOT_PARAM.REP_ID
     */
    private BigDecimal REP_ID;

    /**
     * This field corresponds to the database column REP_SNAPSHOT_PARAM.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column REP_SNAPSHOT_PARAM.REP_REFERENCE
     */
    private String REP_REFERENCE;

    /**
     * This field corresponds to the database column REP_SNAPSHOT_PARAM.SNAPSHOT_FREQUENCY
     */
    private String SNAPSHOT_FREQUENCY;

    /**
     * This field corresponds to the database column REP_SNAPSHOT_PARAM.ADDITIONAL_REFERENCE
     */
    private String ADDITIONAL_REFERENCE;

    /**
     * This field corresponds to the database column REP_SNAPSHOT_PARAM.SAVE_REP_YN
     */
    private String SAVE_REP_YN;

    /**
     * This field corresponds to the database column REP_SNAPSHOT_PARAM.REP_TYPE
     */
    private String REP_TYPE;

    /**
     * This field corresponds to the database column REP_SNAPSHOT_PARAM.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column REP_SNAPSHOT_PARAM.CREATED_DATE
     */
    private Date CREATED_DATE;

    /**
     * This field corresponds to the database column REP_SNAPSHOT_PARAM.SITCOM_ENABLE_YN
     */
    private String SITCOM_ENABLE_YN;

    /**
     * This field corresponds to the database column REP_SNAPSHOT_PARAM.SITCOM_ORDER
     */
    private BigDecimal SITCOM_ORDER;

    /**
     * This field corresponds to the database column REP_SNAPSHOT_PARAM.SAVE_REP_DETAILS_YN
     */
    private String SAVE_REP_DETAILS_YN;

    /**
     * This field corresponds to the database column REP_SNAPSHOT_PARAM.REP_MODIFY_ENABLE_YN
     */
    private String REP_MODIFY_ENABLE_YN;

    /**
     * This field corresponds to the database column REP_SNAPSHOT_PARAM.REP_AUDIT_YN
     */
    private String REP_AUDIT_YN;

    /**
     * This field corresponds to the database column REP_SNAPSHOT_PARAM.REP_COMMENTS_YN
     */
    private String REP_COMMENTS_YN;

    /**
     * This field corresponds to the database column REP_SNAPSHOT_PARAM.DATE_UPDATED
     */
    private Date DATE_UPDATED;

    /**
     * This field corresponds to the database column REP_SNAPSHOT_PARAM.SITCOM_FORMULA
     */
    private String SITCOM_FORMULA;

    /**
     * This field corresponds to the database column REP_SNAPSHOT_PARAM.SITCOM_FORMULA_HEADER
     */
    private String SITCOM_FORMULA_HEADER;

    /**
     * This field corresponds to the database column REP_SNAPSHOT_PARAM.SITCOM_FORMULA_FOOTER
     */
    private String SITCOM_FORMULA_FOOTER;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REP_SNAPSHOT_PARAM.REP_ID
     *
     * @return the value of REP_SNAPSHOT_PARAM.REP_ID
     */
    public BigDecimal getREP_ID() {
        return REP_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REP_SNAPSHOT_PARAM.REP_ID
     *
     * @param REP_ID the value for REP_SNAPSHOT_PARAM.REP_ID
     */
    public void setREP_ID(BigDecimal REP_ID) {
        this.REP_ID = REP_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REP_SNAPSHOT_PARAM.COMP_CODE
     *
     * @return the value of REP_SNAPSHOT_PARAM.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REP_SNAPSHOT_PARAM.COMP_CODE
     *
     * @param COMP_CODE the value for REP_SNAPSHOT_PARAM.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REP_SNAPSHOT_PARAM.REP_REFERENCE
     *
     * @return the value of REP_SNAPSHOT_PARAM.REP_REFERENCE
     */
    public String getREP_REFERENCE() {
        return REP_REFERENCE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REP_SNAPSHOT_PARAM.REP_REFERENCE
     *
     * @param REP_REFERENCE the value for REP_SNAPSHOT_PARAM.REP_REFERENCE
     */
    public void setREP_REFERENCE(String REP_REFERENCE) {
        this.REP_REFERENCE = REP_REFERENCE == null ? null : REP_REFERENCE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REP_SNAPSHOT_PARAM.SNAPSHOT_FREQUENCY
     *
     * @return the value of REP_SNAPSHOT_PARAM.SNAPSHOT_FREQUENCY
     */
    public String getSNAPSHOT_FREQUENCY() {
        return SNAPSHOT_FREQUENCY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REP_SNAPSHOT_PARAM.SNAPSHOT_FREQUENCY
     *
     * @param SNAPSHOT_FREQUENCY the value for REP_SNAPSHOT_PARAM.SNAPSHOT_FREQUENCY
     */
    public void setSNAPSHOT_FREQUENCY(String SNAPSHOT_FREQUENCY) {
        this.SNAPSHOT_FREQUENCY = SNAPSHOT_FREQUENCY == null ? null : SNAPSHOT_FREQUENCY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REP_SNAPSHOT_PARAM.ADDITIONAL_REFERENCE
     *
     * @return the value of REP_SNAPSHOT_PARAM.ADDITIONAL_REFERENCE
     */
    public String getADDITIONAL_REFERENCE() {
        return ADDITIONAL_REFERENCE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REP_SNAPSHOT_PARAM.ADDITIONAL_REFERENCE
     *
     * @param ADDITIONAL_REFERENCE the value for REP_SNAPSHOT_PARAM.ADDITIONAL_REFERENCE
     */
    public void setADDITIONAL_REFERENCE(String ADDITIONAL_REFERENCE) {
        this.ADDITIONAL_REFERENCE = ADDITIONAL_REFERENCE == null ? null : ADDITIONAL_REFERENCE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REP_SNAPSHOT_PARAM.SAVE_REP_YN
     *
     * @return the value of REP_SNAPSHOT_PARAM.SAVE_REP_YN
     */
    public String getSAVE_REP_YN() {
        return SAVE_REP_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REP_SNAPSHOT_PARAM.SAVE_REP_YN
     *
     * @param SAVE_REP_YN the value for REP_SNAPSHOT_PARAM.SAVE_REP_YN
     */
    public void setSAVE_REP_YN(String SAVE_REP_YN) {
        this.SAVE_REP_YN = SAVE_REP_YN == null ? null : SAVE_REP_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REP_SNAPSHOT_PARAM.REP_TYPE
     *
     * @return the value of REP_SNAPSHOT_PARAM.REP_TYPE
     */
    public String getREP_TYPE() {
        return REP_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REP_SNAPSHOT_PARAM.REP_TYPE
     *
     * @param REP_TYPE the value for REP_SNAPSHOT_PARAM.REP_TYPE
     */
    public void setREP_TYPE(String REP_TYPE) {
        this.REP_TYPE = REP_TYPE == null ? null : REP_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REP_SNAPSHOT_PARAM.CREATED_BY
     *
     * @return the value of REP_SNAPSHOT_PARAM.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REP_SNAPSHOT_PARAM.CREATED_BY
     *
     * @param CREATED_BY the value for REP_SNAPSHOT_PARAM.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REP_SNAPSHOT_PARAM.CREATED_DATE
     *
     * @return the value of REP_SNAPSHOT_PARAM.CREATED_DATE
     */
    public Date getCREATED_DATE() {
        return CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REP_SNAPSHOT_PARAM.CREATED_DATE
     *
     * @param CREATED_DATE the value for REP_SNAPSHOT_PARAM.CREATED_DATE
     */
    public void setCREATED_DATE(Date CREATED_DATE) {
        this.CREATED_DATE = CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REP_SNAPSHOT_PARAM.SITCOM_ENABLE_YN
     *
     * @return the value of REP_SNAPSHOT_PARAM.SITCOM_ENABLE_YN
     */
    public String getSITCOM_ENABLE_YN() {
        return SITCOM_ENABLE_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REP_SNAPSHOT_PARAM.SITCOM_ENABLE_YN
     *
     * @param SITCOM_ENABLE_YN the value for REP_SNAPSHOT_PARAM.SITCOM_ENABLE_YN
     */
    public void setSITCOM_ENABLE_YN(String SITCOM_ENABLE_YN) {
        this.SITCOM_ENABLE_YN = SITCOM_ENABLE_YN == null ? null : SITCOM_ENABLE_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REP_SNAPSHOT_PARAM.SITCOM_ORDER
     *
     * @return the value of REP_SNAPSHOT_PARAM.SITCOM_ORDER
     */
    public BigDecimal getSITCOM_ORDER() {
        return SITCOM_ORDER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REP_SNAPSHOT_PARAM.SITCOM_ORDER
     *
     * @param SITCOM_ORDER the value for REP_SNAPSHOT_PARAM.SITCOM_ORDER
     */
    public void setSITCOM_ORDER(BigDecimal SITCOM_ORDER) {
        this.SITCOM_ORDER = SITCOM_ORDER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REP_SNAPSHOT_PARAM.SAVE_REP_DETAILS_YN
     *
     * @return the value of REP_SNAPSHOT_PARAM.SAVE_REP_DETAILS_YN
     */
    public String getSAVE_REP_DETAILS_YN() {
        return SAVE_REP_DETAILS_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REP_SNAPSHOT_PARAM.SAVE_REP_DETAILS_YN
     *
     * @param SAVE_REP_DETAILS_YN the value for REP_SNAPSHOT_PARAM.SAVE_REP_DETAILS_YN
     */
    public void setSAVE_REP_DETAILS_YN(String SAVE_REP_DETAILS_YN) {
        this.SAVE_REP_DETAILS_YN = SAVE_REP_DETAILS_YN == null ? null : SAVE_REP_DETAILS_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REP_SNAPSHOT_PARAM.REP_MODIFY_ENABLE_YN
     *
     * @return the value of REP_SNAPSHOT_PARAM.REP_MODIFY_ENABLE_YN
     */
    public String getREP_MODIFY_ENABLE_YN() {
        return REP_MODIFY_ENABLE_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REP_SNAPSHOT_PARAM.REP_MODIFY_ENABLE_YN
     *
     * @param REP_MODIFY_ENABLE_YN the value for REP_SNAPSHOT_PARAM.REP_MODIFY_ENABLE_YN
     */
    public void setREP_MODIFY_ENABLE_YN(String REP_MODIFY_ENABLE_YN) {
        this.REP_MODIFY_ENABLE_YN = REP_MODIFY_ENABLE_YN == null ? null : REP_MODIFY_ENABLE_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REP_SNAPSHOT_PARAM.REP_AUDIT_YN
     *
     * @return the value of REP_SNAPSHOT_PARAM.REP_AUDIT_YN
     */
    public String getREP_AUDIT_YN() {
        return REP_AUDIT_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REP_SNAPSHOT_PARAM.REP_AUDIT_YN
     *
     * @param REP_AUDIT_YN the value for REP_SNAPSHOT_PARAM.REP_AUDIT_YN
     */
    public void setREP_AUDIT_YN(String REP_AUDIT_YN) {
        this.REP_AUDIT_YN = REP_AUDIT_YN == null ? null : REP_AUDIT_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REP_SNAPSHOT_PARAM.REP_COMMENTS_YN
     *
     * @return the value of REP_SNAPSHOT_PARAM.REP_COMMENTS_YN
     */
    public String getREP_COMMENTS_YN() {
        return REP_COMMENTS_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REP_SNAPSHOT_PARAM.REP_COMMENTS_YN
     *
     * @param REP_COMMENTS_YN the value for REP_SNAPSHOT_PARAM.REP_COMMENTS_YN
     */
    public void setREP_COMMENTS_YN(String REP_COMMENTS_YN) {
        this.REP_COMMENTS_YN = REP_COMMENTS_YN == null ? null : REP_COMMENTS_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REP_SNAPSHOT_PARAM.DATE_UPDATED
     *
     * @return the value of REP_SNAPSHOT_PARAM.DATE_UPDATED
     */
    public Date getDATE_UPDATED() {
        return DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REP_SNAPSHOT_PARAM.DATE_UPDATED
     *
     * @param DATE_UPDATED the value for REP_SNAPSHOT_PARAM.DATE_UPDATED
     */
    public void setDATE_UPDATED(Date DATE_UPDATED) {
        this.DATE_UPDATED = DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REP_SNAPSHOT_PARAM.SITCOM_FORMULA
     *
     * @return the value of REP_SNAPSHOT_PARAM.SITCOM_FORMULA
     */
    public String getSITCOM_FORMULA() {
        return SITCOM_FORMULA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REP_SNAPSHOT_PARAM.SITCOM_FORMULA
     *
     * @param SITCOM_FORMULA the value for REP_SNAPSHOT_PARAM.SITCOM_FORMULA
     */
    public void setSITCOM_FORMULA(String SITCOM_FORMULA) {
        this.SITCOM_FORMULA = SITCOM_FORMULA == null ? null : SITCOM_FORMULA.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REP_SNAPSHOT_PARAM.SITCOM_FORMULA_HEADER
     *
     * @return the value of REP_SNAPSHOT_PARAM.SITCOM_FORMULA_HEADER
     */
    public String getSITCOM_FORMULA_HEADER() {
        return SITCOM_FORMULA_HEADER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REP_SNAPSHOT_PARAM.SITCOM_FORMULA_HEADER
     *
     * @param SITCOM_FORMULA_HEADER the value for REP_SNAPSHOT_PARAM.SITCOM_FORMULA_HEADER
     */
    public void setSITCOM_FORMULA_HEADER(String SITCOM_FORMULA_HEADER) {
        this.SITCOM_FORMULA_HEADER = SITCOM_FORMULA_HEADER == null ? null : SITCOM_FORMULA_HEADER.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REP_SNAPSHOT_PARAM.SITCOM_FORMULA_FOOTER
     *
     * @return the value of REP_SNAPSHOT_PARAM.SITCOM_FORMULA_FOOTER
     */
    public String getSITCOM_FORMULA_FOOTER() {
        return SITCOM_FORMULA_FOOTER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REP_SNAPSHOT_PARAM.SITCOM_FORMULA_FOOTER
     *
     * @param SITCOM_FORMULA_FOOTER the value for REP_SNAPSHOT_PARAM.SITCOM_FORMULA_FOOTER
     */
    public void setSITCOM_FORMULA_FOOTER(String SITCOM_FORMULA_FOOTER) {
        this.SITCOM_FORMULA_FOOTER = SITCOM_FORMULA_FOOTER == null ? null : SITCOM_FORMULA_FOOTER.trim();
    }
}