package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

import com.path.lib.vo.BaseVO;

public class REP_SNAPSHOT_INFOVO extends BaseVO {
    /**
     * This field corresponds to the database column REP_SNAPSHOT_INFO.REP_SNAPSHOT_ID
     */
    private BigDecimal REP_SNAPSHOT_ID;

    /**
     * This field corresponds to the database column REP_SNAPSHOT_INFO.REP_ID
     */
    private BigDecimal REP_ID;

    /**
     * This field corresponds to the database column REP_SNAPSHOT_INFO.DESCRIPTION
     */
    private String DESCRIPTION;

    /**
     * This field corresponds to the database column REP_SNAPSHOT_INFO.SNAPSHOT_USER
     */
    private String SNAPSHOT_USER;

    /**
     * This field corresponds to the database column REP_SNAPSHOT_INFO.SNAPSHOT_DATE
     */
    private Date SNAPSHOT_DATE;

    /**
     * This field corresponds to the database column REP_SNAPSHOT_INFO.DECLARED_YN
     */
    private String DECLARED_YN;

    /**
     * This field corresponds to the database column REP_SNAPSHOT_INFO.DECLARED_BY
     */
    private String DECLARED_BY;

    /**
     * This field corresponds to the database column REP_SNAPSHOT_INFO.DECLARED_DATE
     */
    private Date DECLARED_DATE;

    /**
     * This field corresponds to the database column REP_SNAPSHOT_INFO.RETREIVE_DATE
     */
    private Date RETREIVE_DATE;

    /**
     * This field corresponds to the database column REP_SNAPSHOT_INFO.SITCOM_FILE_ID
     */
    private BigDecimal SITCOM_FILE_ID;

    /**
     * This field corresponds to the database column REP_SNAPSHOT_INFO.DATE_UPDATED
     */
    private Date DATE_UPDATED;

    /**
     * This field corresponds to the database column REP_SNAPSHOT_INFO.REP_BLOB
     */
    private byte[] REP_BLOB;

    /**
     * This field corresponds to the database column REP_SNAPSHOT_INFO.JRXML_FILE
     */
    private byte[] JRXML_FILE;

    /**
     * This field corresponds to the database column REP_SNAPSHOT_INFO.SNAPSHOT_PARAMS
     */
    private byte[] SNAPSHOT_PARAMS;

    /**
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REP_SNAPSHOT_INFO.REP_SNAPSHOT_ID
     *
     * @return the value of REP_SNAPSHOT_INFO.REP_SNAPSHOT_ID
     */
    public BigDecimal getREP_SNAPSHOT_ID() {
        return REP_SNAPSHOT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REP_SNAPSHOT_INFO.REP_SNAPSHOT_ID
     *
     * @param REP_SNAPSHOT_ID the value for REP_SNAPSHOT_INFO.REP_SNAPSHOT_ID
     */
    public void setREP_SNAPSHOT_ID(BigDecimal REP_SNAPSHOT_ID) {
        this.REP_SNAPSHOT_ID = REP_SNAPSHOT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REP_SNAPSHOT_INFO.REP_ID
     *
     * @return the value of REP_SNAPSHOT_INFO.REP_ID
     */
    public BigDecimal getREP_ID() {
        return REP_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REP_SNAPSHOT_INFO.REP_ID
     *
     * @param REP_ID the value for REP_SNAPSHOT_INFO.REP_ID
     */
    public void setREP_ID(BigDecimal REP_ID) {
        this.REP_ID = REP_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REP_SNAPSHOT_INFO.DESCRIPTION
     *
     * @return the value of REP_SNAPSHOT_INFO.DESCRIPTION
     */
    public String getDESCRIPTION() {
        return DESCRIPTION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REP_SNAPSHOT_INFO.DESCRIPTION
     *
     * @param DESCRIPTION the value for REP_SNAPSHOT_INFO.DESCRIPTION
     */
    public void setDESCRIPTION(String DESCRIPTION) {
        this.DESCRIPTION = DESCRIPTION == null ? null : DESCRIPTION.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REP_SNAPSHOT_INFO.SNAPSHOT_USER
     *
     * @return the value of REP_SNAPSHOT_INFO.SNAPSHOT_USER
     */
    public String getSNAPSHOT_USER() {
        return SNAPSHOT_USER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REP_SNAPSHOT_INFO.SNAPSHOT_USER
     *
     * @param SNAPSHOT_USER the value for REP_SNAPSHOT_INFO.SNAPSHOT_USER
     */
    public void setSNAPSHOT_USER(String SNAPSHOT_USER) {
        this.SNAPSHOT_USER = SNAPSHOT_USER == null ? null : SNAPSHOT_USER.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REP_SNAPSHOT_INFO.SNAPSHOT_DATE
     *
     * @return the value of REP_SNAPSHOT_INFO.SNAPSHOT_DATE
     */
    public Date getSNAPSHOT_DATE() {
        return SNAPSHOT_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REP_SNAPSHOT_INFO.SNAPSHOT_DATE
     *
     * @param SNAPSHOT_DATE the value for REP_SNAPSHOT_INFO.SNAPSHOT_DATE
     */
    public void setSNAPSHOT_DATE(Date SNAPSHOT_DATE) {
        this.SNAPSHOT_DATE = SNAPSHOT_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REP_SNAPSHOT_INFO.DECLARED_YN
     *
     * @return the value of REP_SNAPSHOT_INFO.DECLARED_YN
     */
    public String getDECLARED_YN() {
        return DECLARED_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REP_SNAPSHOT_INFO.DECLARED_YN
     *
     * @param DECLARED_YN the value for REP_SNAPSHOT_INFO.DECLARED_YN
     */
    public void setDECLARED_YN(String DECLARED_YN) {
        this.DECLARED_YN = DECLARED_YN == null ? null : DECLARED_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REP_SNAPSHOT_INFO.DECLARED_BY
     *
     * @return the value of REP_SNAPSHOT_INFO.DECLARED_BY
     */
    public String getDECLARED_BY() {
        return DECLARED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REP_SNAPSHOT_INFO.DECLARED_BY
     *
     * @param DECLARED_BY the value for REP_SNAPSHOT_INFO.DECLARED_BY
     */
    public void setDECLARED_BY(String DECLARED_BY) {
        this.DECLARED_BY = DECLARED_BY == null ? null : DECLARED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REP_SNAPSHOT_INFO.DECLARED_DATE
     *
     * @return the value of REP_SNAPSHOT_INFO.DECLARED_DATE
     */
    public Date getDECLARED_DATE() {
        return DECLARED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REP_SNAPSHOT_INFO.DECLARED_DATE
     *
     * @param DECLARED_DATE the value for REP_SNAPSHOT_INFO.DECLARED_DATE
     */
    public void setDECLARED_DATE(Date DECLARED_DATE) {
        this.DECLARED_DATE = DECLARED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REP_SNAPSHOT_INFO.RETREIVE_DATE
     *
     * @return the value of REP_SNAPSHOT_INFO.RETREIVE_DATE
     */
    public Date getRETREIVE_DATE() {
        return RETREIVE_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REP_SNAPSHOT_INFO.RETREIVE_DATE
     *
     * @param RETREIVE_DATE the value for REP_SNAPSHOT_INFO.RETREIVE_DATE
     */
    public void setRETREIVE_DATE(Date RETREIVE_DATE) {
        this.RETREIVE_DATE = RETREIVE_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REP_SNAPSHOT_INFO.SITCOM_FILE_ID
     *
     * @return the value of REP_SNAPSHOT_INFO.SITCOM_FILE_ID
     */
    public BigDecimal getSITCOM_FILE_ID() {
        return SITCOM_FILE_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REP_SNAPSHOT_INFO.SITCOM_FILE_ID
     *
     * @param SITCOM_FILE_ID the value for REP_SNAPSHOT_INFO.SITCOM_FILE_ID
     */
    public void setSITCOM_FILE_ID(BigDecimal SITCOM_FILE_ID) {
        this.SITCOM_FILE_ID = SITCOM_FILE_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REP_SNAPSHOT_INFO.DATE_UPDATED
     *
     * @return the value of REP_SNAPSHOT_INFO.DATE_UPDATED
     */
    public Date getDATE_UPDATED() {
        return DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REP_SNAPSHOT_INFO.DATE_UPDATED
     *
     * @param DATE_UPDATED the value for REP_SNAPSHOT_INFO.DATE_UPDATED
     */
    public void setDATE_UPDATED(Date DATE_UPDATED) {
        this.DATE_UPDATED = DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REP_SNAPSHOT_INFO.REP_BLOB
     *
     * @return the value of REP_SNAPSHOT_INFO.REP_BLOB
     */
    public byte[] getREP_BLOB() {
        return REP_BLOB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REP_SNAPSHOT_INFO.REP_BLOB
     *
     * @param REP_BLOB the value for REP_SNAPSHOT_INFO.REP_BLOB
     */
    public void setREP_BLOB(byte[] REP_BLOB) {
        this.REP_BLOB = REP_BLOB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REP_SNAPSHOT_INFO.JRXML_FILE
     *
     * @return the value of REP_SNAPSHOT_INFO.JRXML_FILE
     */
    public byte[] getJRXML_FILE() {
        return JRXML_FILE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REP_SNAPSHOT_INFO.JRXML_FILE
     *
     * @param JRXML_FILE the value for REP_SNAPSHOT_INFO.JRXML_FILE
     */
    public void setJRXML_FILE(byte[] JRXML_FILE) {
        this.JRXML_FILE = JRXML_FILE;
    }
    

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REP_SNAPSHOT_INFO.SNAPSHOT_PARAMS
     *
     * @return the value of REP_SNAPSHOT_INFO.SNAPSHOT_PARAMS
     */
    public byte[] getSNAPSHOT_PARAMS() {
        return SNAPSHOT_PARAMS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REP_SNAPSHOT_INFO.SNAPSHOT_PARAMS
     *
     * @param SNAPSHOT_PARAMS the value for REP_SNAPSHOT_INFO.SNAPSHOT_PARAMS
     */
    public void setSNAPSHOT_PARAMS(byte[] SNAPSHOT_PARAMS) {
        this.SNAPSHOT_PARAMS = SNAPSHOT_PARAMS;
    }

}