package com.path.vo.rep.report;
import java.math.BigDecimal;
import java.util.HashMap;

import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.path.vo.common.ImBaseRequest;
import com.path.vo.common.header.ResponseContextVO;
import com.path.vo.common.header.ResponseServiceContextVO;
import com.path.vo.common.header.ServiceResponseVO;

/**
 * @AutoGenerated Code
 * @description class GenerateReportResp extends ImBaseRequest
 */
@XmlType(propOrder={})
@XmlRootElement(name="generateReportResp")
public class GenerateReportResp extends ImBaseRequest
{
	private ServiceResponseVO serviceResponse = new ServiceResponseVO();
	private ResponseContextVO responseContext = new ResponseContextVO();
	private ResponseServiceContextVO responseServiceContext = new ResponseServiceContextVO();
	private BigDecimal branchCode;
	private BigDecimal companyCode;
	private String applicationName;
	private ReportDetails reportDetail;
	private String report;
	private BigDecimal reportSize;
	private HashMap<String,String> reportParametersList = new HashMap<String,String>();

	public void setServiceResponse(ServiceResponseVO serviceResponse)
	{
	   this.serviceResponse = serviceResponse;
	}
	public ServiceResponseVO getServiceResponse()
	{
	   return serviceResponse;
	}
	public void setResponseContext(ResponseContextVO responseContext)
	{
	   this.responseContext = responseContext;
	}
	public ResponseContextVO getResponseContext()
	{
	   return responseContext;
	}
	public void setResponseServiceContext(ResponseServiceContextVO responseServiceContext)
	{
	   this.responseServiceContext = responseServiceContext;
	}
	public ResponseServiceContextVO getResponseServiceContext()
	{
	   return responseServiceContext;
	}
	public void setBranchCode(BigDecimal branchCode)
	{
	   this.branchCode = branchCode;
	}
	public BigDecimal getBranchCode()
	{
	   return branchCode;
	}
	public void setCompanyCode(BigDecimal companyCode)
	{
	   this.companyCode = companyCode;
	}
	public BigDecimal getCompanyCode()
	{
	   return companyCode;
	}
	public void setApplicationName(String applicationName)
	{
	   this.applicationName = applicationName;
	}
	public String getApplicationName()
	{
	   return applicationName;
	}
	public void setReportDetail(ReportDetails reportDetail)
	{
	   this.reportDetail = reportDetail;
	}
	public ReportDetails getReportDetail()
	{
	   return reportDetail;
	}
	public void setReport(String report)
	{
	   this.report = report;
	}
	public String getReport()
	{
	   return report;
	}
	public void setReportSize(BigDecimal reportSize)
	{
	   this.reportSize = reportSize;
	}
	public BigDecimal getReportSize()
	{
	   return reportSize;
	}
	public HashMap<String, String> getReportParametersList()
	{
	    return reportParametersList;
	}
	public void setReportParametersList(HashMap<String, String> reportParametersList)
	{
	    this.reportParametersList = reportParametersList;
	}
	
}
