package com.path.vo.rep.report;
import java.math.BigDecimal;

import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * @AutoGenerated Code
 * @description class ReportDetails
 */
@XmlType(propOrder={})
@XmlRootElement(name="reportDetails")
public class ReportDetails 
{
	private String progRef;
	private String reportApplicationName;
	private BigDecimal reportId;
	private BigDecimal oldReportId;
	private String language;
	private String format;
	private BigDecimal sourceId;
	private String reportName;
	private BigDecimal numberCopiesToPrint;
	private String reportingPath;
	private BigDecimal databaseConn;
	private String printerName;
	private Boolean noHeaderAndFooter;
	private String csvSepartor;

	public void setProgRef(String progRef)
	{
	   this.progRef = progRef;
	}
	public String getProgRef()
	{
	   return progRef;
	}
	public void setReportApplicationName(String reportApplicationName)
	{
	   this.reportApplicationName = reportApplicationName;
	}
	public String getReportApplicationName()
	{
	   return reportApplicationName;
	}
	public void setReportId(BigDecimal reportId)
	{
	   this.reportId = reportId;
	}
	public BigDecimal getReportId()
	{
	   return reportId;
	}
	public void setOldReportId(BigDecimal oldReportId)
	{
	   this.oldReportId = oldReportId;
	}
	public BigDecimal getOldReportId()
	{
	   return oldReportId;
	}
	public void setLanguage(String language)
	{
	   this.language = language;
	}
	public String getLanguage()
	{
	   return language;
	}
	public void setFormat(String format)
	{
	   this.format = format;
	}
	public String getFormat()
	{
	   return format;
	}
	public void setSourceId(BigDecimal sourceId)
	{
	   this.sourceId = sourceId;
	}
	public BigDecimal getSourceId()
	{
	   return sourceId;
	}
	public void setReportName(String reportName)
	{
	   this.reportName = reportName;
	}
	public String getReportName()
	{
	   return reportName;
	}
	public void setNumberCopiesToPrint(BigDecimal numberCopiesToPrint)
	{
	   this.numberCopiesToPrint = numberCopiesToPrint;
	}
	public BigDecimal getNumberCopiesToPrint()
	{
	   return numberCopiesToPrint;
	}
	public void setReportingPath(String reportingPath)
	{
	   this.reportingPath = reportingPath;
	}
	public String getReportingPath()
	{
	   return reportingPath;
	}
	public void setDatabaseConn(BigDecimal databaseConn)
	{
	   this.databaseConn = databaseConn;
	}
	public BigDecimal getDatabaseConn()
	{
	   return databaseConn;
	}
	public void setPrinterName(String printerName)
	{
	   this.printerName = printerName;
	}
	public String getPrinterName()
	{
	   return printerName;
	}
	public void setNoHeaderAndFooter(Boolean noHeaderAndFooter)
	{
	   this.noHeaderAndFooter = noHeaderAndFooter;
	}
	public Boolean getNoHeaderAndFooter()
	{
	   return noHeaderAndFooter;
	}
	public void setCsvSepartor(String csvSepartor)
	{
	   this.csvSepartor = csvSepartor;
	}
	public String getCsvSepartor()
	{
	   return csvSepartor;
	}
}
