package com.path.vo.rep.report;
import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * @AutoGenerated Code
 * @description class SessionParameters
 */
@XmlType(propOrder={})
@XmlRootElement(name="sessionParameters")
public class SessionParameters 
{
	private BigDecimal branchCode;
	private BigDecimal companyCode;
	private String applicationName;

	public void setBranchCode(BigDecimal branchCode)
	{
	   this.branchCode = branchCode;
	}
	public BigDecimal getBranchCode()
	{
	   return branchCode;
	}
	public void setCompanyCode(BigDecimal companyCode)
	{
	   this.companyCode = companyCode;
	}
	public BigDecimal getCompanyCode()
	{
	   return companyCode;
	}
	public void setApplicationName(String applicationName)
	{
	   this.applicationName = applicationName;
	}
	public String getApplicationName()
	{
	   return applicationName;
	}
}
