package com.path.vo.rep.report;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * @AutoGenerated Code
 * @description class ReportParameters
 */
@XmlType(propOrder={})
@XmlRootElement(name="reportParameters")
public class ReportParameters 
{
	private String value;

	public void setValue(String value)
	{
	   this.value = value;
	}
	public String getValue()
	{
	   return value;
	}
}
