package com.path.vo.common;
import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlType;

/**
 * @AutoGenerated Code
 * @description class Pagination
 */

@XmlType(propOrder={})
public class Pagination 
{
	private BigDecimal pageSize;
	private BigDecimal pageNumber;
	private BigDecimal totalCount;

	public void setPageSize(BigDecimal pageSize)
	{
	   this.pageSize = pageSize;
	}
	public BigDecimal getPageSize()
	{
	   return pageSize;
	}
	public void setPageNumber(BigDecimal pageNumber)
	{
	   this.pageNumber = pageNumber;
	}
	public BigDecimal getPageNumber()
	{
	   return pageNumber;
	}
	public void setTotalCount(BigDecimal totalCount)
	{
	   this.totalCount = totalCount;
	}
	public BigDecimal getTotalCount()
	{
	   return totalCount;
	}
}
