package com.path.vo.common;
import javax.xml.bind.annotation.XmlType;

/**
 * @AutoGenerated Code
 * @description class SortOrder
 */

@XmlType(propOrder={})
public class SortOrder 
{
	private String sord;
	private String sidx;

	public void setSord(String sord)
	{
	   this.sord = sord;
	}
	public String getSord()
	{
	   return sord;
	}
	public void setSidx(String sidx)
	{
	   this.sidx = sidx;
	}
	public String getSidx()
	{
	   return sidx;
	}
}
